// Code generated by onvifgen; DO NOT EDIT.

package tth

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type GetConfiguration struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetConfigurationOptions struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetConfigurationOptionsResponse struct {
	ConfigurationOptions ConfigurationOptions `xml:"ConfigurationOptions"`
}

type GetConfigurationResponse struct {
	Configuration Configuration `xml:"Configuration"`
}

type GetConfigurations struct {
}

type GetConfigurationsResponse struct {
	Configurations []Configurations `xml:"Configurations,omitempty"`
}

type GetRadiometryConfiguration struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetRadiometryConfigurationOptions struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetRadiometryConfigurationOptionsResponse struct {
	ConfigurationOptions RadiometryConfigurationOptions `xml:"ConfigurationOptions"`
}

type GetRadiometryConfigurationResponse struct {
	Configuration RadiometryConfiguration `xml:"Configuration"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type SetConfiguration struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	Configuration Configuration `xml:"Configuration"`
}

type SetConfigurationResponse struct {
}

type SetRadiometryConfiguration struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	Configuration RadiometryConfiguration `xml:"Configuration"`
}

type SetRadiometryConfigurationResponse struct {
}

