// Code generated by onvifgen; DO NOT EDIT.

package wsa

type Action AttributedURIType

type EndpointReference EndpointReferenceType

type FaultTo EndpointReferenceType

type From EndpointReferenceType

type MessageID AttributedURIType

type Metadata MetadataType

type ProblemAction ProblemActionType

type ProblemHeader AttributedAnyType

type ProblemHeaderQName AttributedQNameType

type ProblemIRI AttributedURIType

type RelatesTo RelatesToType

type ReplyTo EndpointReferenceType

type RetryAfter AttributedUnsignedLongType

type To AttributedURIType

