// Code generated by onvifgen; DO NOT EDIT.

package tas

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

// An identifier of an algorithm.
type AlgorithmIdentifier struct {
	Xalgorithm DotDecimalOID `xml:"algorithm"`
	Xparameters *Base64DERencodedASN1Value `xml:"parameters,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type AuthorizationServerConfiguration struct {
	Base11 tt.DeviceEntity `xml:",omitempty"`
	Data AuthorizationServerConfigurationData `xml:"Data"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type AuthorizationServerConfigurationCapabilities struct {
	MaxConfigurations int32 `xml:"MaxConfigurations,omitempty,attr"`
	ConfigurationTypesSupported tt.StringList `xml:"ConfigurationTypesSupported,omitempty,attr"`
	ClientAuthenticationMethodsSupported tt.StringList `xml:"ClientAuthenticationMethodsSupported,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type AuthorizationServerConfigurationData struct {
	ServerUri string `xml:"ServerUri"`
	ClientID *string `xml:"ClientID,omitempty"`
	ClientSecret *string `xml:"ClientSecret,omitempty"`
	Scope *string `xml:"Scope,omitempty"`
	KeyID *KeyID `xml:"KeyID,omitempty"`
	CertificateID *CertificateID `xml:"CertificateID,omitempty"`
	CertPathValidationPolicyID *CertPathValidationPolicyID `xml:"CertPathValidationPolicyID,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	Type string `xml:"Type,attr"`
	ClientAuth string `xml:"ClientAuth,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// A CSR attribute as specified in RFC 2986.
type BasicRequestAttribute struct {
	OID DotDecimalOID `xml:"OID"`
	Xvalue Base64DERencodedASN1Value `xml:"value"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CRL struct {
	CRLID CRLID `xml:"CRLID"`
	Alias string `xml:"Alias"`
	CRLContent Base64DERencodedASN1Value `xml:"CRLContent"`
	Any core.Extension `xml:"Any,omitempty"`
}

// A CSR attribute as specified in PKCS#10.
type CSRAttribute struct {
	X509v3Extension *X509v3Extension `xml:"X509v3Extension,omitempty"`
	BasicRequestAttribute *BasicRequestAttribute `xml:"BasicRequestAttribute,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The capabilities of a Security Configuration Service implementation on a device.
type Capabilities struct {
	KeystoreCapabilities KeystoreCapabilities `xml:"KeystoreCapabilities"`
	TLSServerCapabilities TLSServerCapabilities `xml:"TLSServerCapabilities"`
	Dot1XCapabilities *Dot1XCapabilities `xml:"Dot1XCapabilities,omitempty"`
	AuthorizationServer *AuthorizationServerConfigurationCapabilities `xml:"AuthorizationServer,omitempty"`
	MediaSigning *MediaSigningCapabilities `xml:"MediaSigning,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CertPathValidationParameters struct {
	RequireTLSWWWClientAuthExtendedKeyUsage *bool `xml:"RequireTLSWWWClientAuthExtendedKeyUsage,omitempty"`
	UseDeltaCRLs *bool `xml:"UseDeltaCRLs,omitempty"`
}

type CertPathValidationPolicy struct {
	CertPathValidationPolicyID CertPathValidationPolicyID `xml:"CertPathValidationPolicyID"`
	Alias *string `xml:"Alias,omitempty"`
	Parameters CertPathValidationParameters `xml:"Parameters"`
	TrustAnchor []TrustAnchor `xml:"TrustAnchor,omitempty"`
}

// A sequence of certificate IDs.
type CertificateIDs struct {
	CertificateID []CertificateID `xml:"CertificateID,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// An X.509 certification path as defined in RFC 5280.
type CertificationPath struct {
	CertificateID []CertificateID `xml:"CertificateID,omitempty"`
	Alias *string `xml:"Alias,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CustomClaim struct {
	Name string `xml:"Name"`
	SupportedValues tt.StringList `xml:"SupportedValues"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// A distinguished name attribute type and value pair.
type DNAttributeTypeAndValue struct {
	Type DNAttributeType `xml:"Type"`
	Value DNAttributeValue `xml:"Value"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type DistinguishedName struct {
	Country []DNAttributeValue `xml:"Country,omitempty"`
	Organization []DNAttributeValue `xml:"Organization,omitempty"`
	OrganizationalUnit []DNAttributeValue `xml:"OrganizationalUnit,omitempty"`
	DistinguishedNameQualifier []DNAttributeValue `xml:"DistinguishedNameQualifier,omitempty"`
	StateOrProvinceName []DNAttributeValue `xml:"StateOrProvinceName,omitempty"`
	CommonName []DNAttributeValue `xml:"CommonName,omitempty"`
	SerialNumber []DNAttributeValue `xml:"SerialNumber,omitempty"`
	Locality []DNAttributeValue `xml:"Locality,omitempty"`
	Title []DNAttributeValue `xml:"Title,omitempty"`
	Surname []DNAttributeValue `xml:"Surname,omitempty"`
	GivenName []DNAttributeValue `xml:"GivenName,omitempty"`
	Initials []DNAttributeValue `xml:"Initials,omitempty"`
	Pseudonym []DNAttributeValue `xml:"Pseudonym,omitempty"`
	GenerationQualifier []DNAttributeValue `xml:"GenerationQualifier,omitempty"`
	GenericAttribute []DNAttributeTypeAndValue `xml:"GenericAttribute,omitempty"`
	MultiValuedRDN []MultiValuedRDN `xml:"MultiValuedRDN,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The capabilities of the 802.1X implementation on a device.
type Dot1XCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MaximumNumberOfDot1XConfigurations int32 `xml:"MaximumNumberOfDot1XConfigurations,omitempty,attr"`
	Dot1XMethods Dot1XMethods `xml:"Dot1XMethods,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Dot1XConfiguration struct {
	Dot1XID *Dot1XID `xml:"Dot1XID,omitempty"`
	Alias *string `xml:"Alias,omitempty"`
	Outer Dot1XStage `xml:"Outer"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The configuration parameters required for a particular authentication method.
type Dot1XStage struct {
	Identity *string `xml:"Identity,omitempty"`
	CertificationPathID *CertificationPathID `xml:"CertificationPathID,omitempty"`
	PassphraseID *PassphraseID `xml:"PassphraseID,omitempty"`
	Inner *Dot1XStage `xml:"Inner,omitempty"`
	Extension *Dot1XStageExtension `xml:"Extension,omitempty"`
	Method string `xml:"Method,attr"`
	CertPathValidationPolicyID CertPathValidationPolicyID `xml:"CertPathValidationPolicyID,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Dot1XStageExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type JWTConfiguration struct {
	Audiences tt.StringList `xml:"Audiences"`
	TrustedIssuers []string `xml:"TrustedIssuers,omitempty"`
	KeyID []KeyID `xml:"KeyID,omitempty"`
	ValidationPolicy *CertPathValidationPolicyID `xml:"ValidationPolicy,omitempty"`
	CustomClaims []CustomClaim `xml:"CustomClaims,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The attributes of a key in the keystore.
type KeyAttribute struct {
	KeyID KeyID `xml:"KeyID"`
	Alias *string `xml:"Alias,omitempty"`
	XhasPrivateKey *bool `xml:"hasPrivateKey,omitempty"`
	KeyStatus string `xml:"KeyStatus"`
	Any core.Extension `xml:"Any,omitempty"`
	XexternallyGenerated *bool `xml:"externallyGenerated,omitempty"`
	XsecurelyStored *bool `xml:"securelyStored,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The capabilities of a keystore implementation on a device.
type KeystoreCapabilities struct {
	SignatureAlgorithms []AlgorithmIdentifier `xml:"SignatureAlgorithms,omitempty"`
	MaximumNumberOfKeys int32 `xml:"MaximumNumberOfKeys,omitempty,attr"`
	MaximumNumberOfCertificates int32 `xml:"MaximumNumberOfCertificates,omitempty,attr"`
	MaximumNumberOfCertificationPaths int32 `xml:"MaximumNumberOfCertificationPaths,omitempty,attr"`
	SetCertPath bool `xml:"SetCertPath,omitempty,attr"`
	RSAKeyPairGeneration bool `xml:"RSAKeyPairGeneration,omitempty,attr"`
	ECCKeyPairGeneration bool `xml:"ECCKeyPairGeneration,omitempty,attr"`
	KeyPairGeneration tt.StringList `xml:"KeyPairGeneration,omitempty,attr"`
	RSAKeyLengths RSAKeyLengths `xml:"RSAKeyLengths,omitempty,attr"`
	EllipticCurves EllipticCurves `xml:"EllipticCurves,omitempty,attr"`
	PKCS10ExternalCertificationWithRSA bool `xml:"PKCS10ExternalCertificationWithRSA,omitempty,attr"`
	PKCS10 bool `xml:"PKCS10,omitempty,attr"`
	SelfSignedCertificateCreationWithRSA bool `xml:"SelfSignedCertificateCreationWithRSA,omitempty,attr"`
	SelfSignedCertificateCreation bool `xml:"SelfSignedCertificateCreation,omitempty,attr"`
	X509Versions X509Versions `xml:"X509Versions,omitempty,attr"`
	MaximumNumberOfPassphrases int32 `xml:"MaximumNumberOfPassphrases,omitempty,attr"`
	PKCS8RSAKeyPairUpload bool `xml:"PKCS8RSAKeyPairUpload,omitempty,attr"`
	PKCS8 bool `xml:"PKCS8,omitempty,attr"`
	PKCS12CertificateWithRSAPrivateKeyUpload bool `xml:"PKCS12CertificateWithRSAPrivateKeyUpload,omitempty,attr"`
	PKCS12 bool `xml:"PKCS12,omitempty,attr"`
	PasswordBasedEncryptionAlgorithms PasswordBasedEncryptionAlgorithms `xml:"PasswordBasedEncryptionAlgorithms,omitempty,attr"`
	PasswordBasedMACAlgorithms PasswordBasedMACAlgorithms `xml:"PasswordBasedMACAlgorithms,omitempty,attr"`
	MaximumNumberOfCRLs int32 `xml:"MaximumNumberOfCRLs,omitempty,attr"`
	MaximumNumberOfCertificationPathValidationPolicies int32 `xml:"MaximumNumberOfCertificationPathValidationPolicies,omitempty,attr"`
	EnforceTLSWebClientAuthExtKeyUsage bool `xml:"EnforceTLSWebClientAuthExtKeyUsage,omitempty,attr"`
	NoPrivateKeySharing bool `xml:"NoPrivateKeySharing,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The capabilities for signing media on a device.
type MediaSigningCapabilities struct {
	MediaSigningSupported bool `xml:"MediaSigningSupported,omitempty,attr"`
	UserMediaSigningKeySupported bool `xml:"UserMediaSigningKeySupported,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// A multi-valued RDN
type MultiValuedRDN struct {
	Attribute []DNAttributeTypeAndValue `xml:"Attribute,omitempty"`
}

type PassphraseAttribute struct {
	PassphraseID PassphraseID `xml:"PassphraseID"`
	Alias *string `xml:"Alias,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The capabilities of a TLS server implementation on a device.
type TLSServerCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	TLSServerSupported TLSVersions `xml:"TLSServerSupported,omitempty,attr"`
	EnabledVersionsSupported bool `xml:"EnabledVersionsSupported,omitempty,attr"`
	MaximumNumberOfTLSCertificationPaths int32 `xml:"MaximumNumberOfTLSCertificationPaths,omitempty,attr"`
	TLSClientAuthSupported bool `xml:"TLSClientAuthSupported,omitempty,attr"`
	CnMapsToUserSupported bool `xml:"CnMapsToUserSupported,omitempty,attr"`
	MaximumNumberOfTLSCertificationPathValidationPolicies int32 `xml:"MaximumNumberOfTLSCertificationPathValidationPolicies,omitempty,attr"`
}

type TrustAnchor struct {
	CertificateID CertificateID `xml:"CertificateID"`
	Any core.Extension `xml:"Any,omitempty"`
}

// An X.509 cerficiate as specified in RFC 5280.
type X509Certificate struct {
	CertificateID CertificateID `xml:"CertificateID"`
	KeyID KeyID `xml:"KeyID"`
	Alias *string `xml:"Alias,omitempty"`
	CertificateContent Base64DERencodedASN1Value `xml:"CertificateContent"`
	HasPrivateKey *bool `xml:"HasPrivateKey,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// An X.509v3 extension field as specified in RFC 5280
type X509v3Extension struct {
	XextnOID DotDecimalOID `xml:"extnOID"`
	Xcritical bool `xml:"critical"`
	XextnValue Base64DERencodedASN1Value `xml:"extnValue"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

