// Code generated by onvifgen; DO NOT EDIT.

package tcr

import (
	"encoding/xml"
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/pacs"
)

// A structure containing anti-passback related state information.
type AntipassbackState struct {
	AntipassbackViolated bool `xml:"AntipassbackViolated"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// A Credential is a physical/tangible object, a piece of knowledge, or a facet of a person's
// physical being, that enables an individual access to a given physical facility or computer-based
// information system. A credential holds one or more credential identifiers. To gain access one or
// more identifiers may be required.
type Credential struct {
	Base50 CredentialInfo `xml:",omitempty"`
	CredentialIdentifier []CredentialIdentifier `xml:"CredentialIdentifier,omitempty"`
	CredentialAccessProfile []CredentialAccessProfile `xml:"CredentialAccessProfile,omitempty"`
	ExtendedGrantTime *bool `xml:"ExtendedGrantTime,omitempty"`
	Attribute []pacs.Attribute `xml:"Attribute,omitempty"`
	Extension *CredentialExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The association between a credential and an access profile.
type CredentialAccessProfile struct {
	AccessProfileToken pacs.ReferenceToken `xml:"AccessProfileToken"`
	ValidFrom *time.Time `xml:"ValidFrom,omitempty"`
	ValidTo *time.Time `xml:"ValidTo,omitempty"`
}

// Contains information about a format type.
type CredentialData struct {
	Credential Credential `xml:"Credential"`
	CredentialState CredentialState `xml:"CredentialState"`
	Extension *CredentialDataExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CredentialDataExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type CredentialExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

// A credential identifier is a card number, unique card information, PIN or
// biometric information such as fingerprint, iris, vein, face recognition, that can be validated
// in an access point.
type CredentialIdentifier struct {
	Type CredentialIdentifierType `xml:"Type"`
	ExemptedFromAuthentication bool `xml:"ExemptedFromAuthentication"`
	Value []byte `xml:"Value"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// Contains information about a format type.
type CredentialIdentifierFormatTypeInfo struct {
	FormatType string `xml:"FormatType"`
	Description pacs.Description `xml:"Description"`
	Extension *CredentialIdentifierFormatTypeInfoExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CredentialIdentifierFormatTypeInfoExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

// A credential identifier is a card number, unique card information, PIN or biometric information
// such as fingerprint, iris, vein, face recognition, that can be validated in an access point.
type CredentialIdentifierItem struct {
	Type CredentialIdentifierType `xml:"Type"`
	Value []byte `xml:"Value"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// Specifies the name of credential identifier type and its format for the credential
// value.
type CredentialIdentifierType struct {
	Name pacs.Name `xml:"Name"`
	FormatType string `xml:"FormatType"`
	Any core.Extension `xml:"Any,omitempty"`
}

// The CredentialInfo type represents the credential as a logical object. The structure contains
// the basic information of a specific credential instance. The device shall provide the following
// fields for each credential.
type CredentialInfo struct {
	Base51 pacs.DataEntity `xml:",omitempty"`
	Description *pacs.Description `xml:"Description,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The CredentialState structure contains information about the state of the credential and
// optionally the reason of why the credential was disabled.
type CredentialState struct {
	Enabled bool `xml:"Enabled"`
	Reason *pacs.Name `xml:"Reason,omitempty"`
	AntipassbackState *AntipassbackState `xml:"AntipassbackState,omitempty"`
	Extension *CredentialStateExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CredentialStateExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

// Contains information about a format type.
type FaultResponse struct {
	Token pacs.ReferenceToken `xml:"Token"`
	Fault string `xml:"Fault"`
	Extension *FaultResponseExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type FaultResponseExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

// The service capabilities reflect optional functionality of a service. The information is static
// and does not change during device operation. The following capabilities are available:
type ServiceCapabilities struct {
	SupportedIdentifierType []pacs.Name `xml:"SupportedIdentifierType,omitempty"`
	Extension *ServiceCapabilitiesExtension `xml:"Extension,omitempty"`
	MaxLimit pacs.PositiveInteger `xml:"MaxLimit,attr"`
	CredentialValiditySupported bool `xml:"CredentialValiditySupported,attr"`
	CredentialAccessProfileValiditySupported bool `xml:"CredentialAccessProfileValiditySupported,attr"`
	ValiditySupportsTimeValue bool `xml:"ValiditySupportsTimeValue,attr"`
	MaxCredentials int64 `xml:"MaxCredentials,attr"`
	MaxAccessProfilesPerCredential pacs.PositiveInteger `xml:"MaxAccessProfilesPerCredential,attr"`
	ResetAntipassbackSupported bool `xml:"ResetAntipassbackSupported,attr"`
	ClientSuppliedTokenSupported bool `xml:"ClientSuppliedTokenSupported,omitempty,attr"`
	DefaultCredentialSuspensionDuration *core.Duration `xml:"DefaultCredentialSuspensionDuration,omitempty,attr"`
	MaxWhitelistedItems int64 `xml:"MaxWhitelistedItems,omitempty,attr"`
	MaxBlacklistedItems int64 `xml:"MaxBlacklistedItems,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type ServiceCapabilitiesExtension struct {
	SupportedExemptionType []pacs.Name `xml:"SupportedExemptionType,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
}

