// Code generated by onvifgen; DO NOT EDIT.

// Package xmlns contains ONVIF-generated types for the
// http://www.w3.org/XML/1998/namespace namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package xmlns

const NS = "http://www.w3.org/XML/1998/namespace"
