// Code generated by onvifgen; DO NOT EDIT.

package tls

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type CreatePaneConfiguration struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	PaneConfiguration tt.PaneConfiguration `xml:"PaneConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type CreatePaneConfigurationResponse struct {
	PaneToken tt.ReferenceToken `xml:"PaneToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type DeletePaneConfiguration struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	PaneToken tt.ReferenceToken `xml:"PaneToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type DeletePaneConfigurationResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type GetDisplayOptions struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetDisplayOptionsResponse struct {
	LayoutOptions *tt.LayoutOptions `xml:"LayoutOptions,omitempty"`
	CodingCapabilities tt.CodingCapabilities `xml:"CodingCapabilities"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetLayout struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetLayoutResponse struct {
	Layout tt.Layout `xml:"Layout"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetPaneConfiguration struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	Pane tt.ReferenceToken `xml:"Pane"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetPaneConfigurationResponse struct {
	PaneConfiguration tt.PaneConfiguration `xml:"PaneConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetPaneConfigurations struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetPaneConfigurationsResponse struct {
	PaneConfiguration []tt.PaneConfiguration `xml:"PaneConfiguration,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type SetLayout struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	Layout tt.Layout `xml:"Layout"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetLayoutResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type SetPaneConfiguration struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	PaneConfiguration tt.PaneConfiguration `xml:"PaneConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetPaneConfigurationResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type SetPaneConfigurations struct {
	VideoOutput tt.ReferenceToken `xml:"VideoOutput"`
	PaneConfiguration []tt.PaneConfiguration `xml:"PaneConfiguration,omitempty"`
}

type SetPaneConfigurationsResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

