// Code generated by onvifgen; DO NOT EDIT.

package provisioning

import (
	"context"
	"net/http"

	"github.com/furrysalamander/onvif-go/onvif/soaphdr"
	"github.com/furrysalamander/onvif-go/onvif/schema/tpv"
)

const actionBase = "http://www.onvif.org/ver10/provisioning/wsdl"

type Client struct {
	c *soaphdr.Client
}

func NewClient(endpoint, username, password string) *Client {
	return &Client{c: soaphdr.New(endpoint, username, password)}
}

func NewClientWithTransport(c *soaphdr.Client) *Client {
	return &Client{c: c}
}

func (c *Client) HTTP() *http.Client { return c.c.HTTP }
func (c *Client) SetHTTP(h *http.Client) { c.c.HTTP = h }

func (c *Client) FocusMove(ctx context.Context) (*tpv.FocusMoveResponse, error) {
	out := &tpv.FocusMoveResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/FocusMove", &tpv.FocusMove{}, out)
	return out, err
}

func (c *Client) GetServiceCapabilities(ctx context.Context) (*tpv.GetServiceCapabilitiesResponse, error) {
	out := &tpv.GetServiceCapabilitiesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/GetServiceCapabilities", &tpv.GetServiceCapabilities{}, out)
	return out, err
}

func (c *Client) GetUsage(ctx context.Context) (*tpv.GetUsageResponse, error) {
	out := &tpv.GetUsageResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/Usage", &tpv.GetUsage{}, out)
	return out, err
}

func (c *Client) PanMove(ctx context.Context) (*tpv.PanMoveResponse, error) {
	out := &tpv.PanMoveResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/PanMove", &tpv.PanMove{}, out)
	return out, err
}

func (c *Client) RollMove(ctx context.Context) (*tpv.RollMoveResponse, error) {
	out := &tpv.RollMoveResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/RollMove", &tpv.RollMove{}, out)
	return out, err
}

func (c *Client) Stop(ctx context.Context) (*tpv.StopResponse, error) {
	out := &tpv.StopResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/Stop", &tpv.Stop{}, out)
	return out, err
}

func (c *Client) TiltMove(ctx context.Context) (*tpv.TiltMoveResponse, error) {
	out := &tpv.TiltMoveResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/TiltMove", &tpv.TiltMove{}, out)
	return out, err
}

func (c *Client) ZoomMove(ctx context.Context) (*tpv.ZoomMoveResponse, error) {
	out := &tpv.ZoomMoveResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/provisioning/wsdl/ZoomMove", &tpv.ZoomMove{}, out)
	return out, err
}

