// Code generated by onvifgen; DO NOT EDIT.

package bd

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type Bag struct {
	Category *string `xml:"Category,omitempty"`
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Behaviour struct {
	Smoking *string `xml:"Smoking,omitempty"`
	UsingMobile *string `xml:"UsingMobile,omitempty"`
	Activity *string `xml:"Activity,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Belonging struct {
	Bag *Bag `xml:"Bag,omitempty"`
	Umbrella *Umbrella `xml:"Umbrella,omitempty"`
	LiftSomething *bool `xml:"LiftSomething,omitempty"`
	Box *Box `xml:"Box,omitempty"`
	Cart *Cart `xml:"Cart,omitempty"`
	Weapon *bool `xml:"Weapon,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Belongings struct {
	Bag []Bag `xml:"Bag,omitempty"`
	Umbrella *Umbrella `xml:"Umbrella,omitempty"`
	Cart *Cart `xml:"Cart,omitempty"`
	Weapon []Weapon `xml:"Weapon,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type BodyMetric struct {
	Height *int32 `xml:"Height,omitempty"`
	BodyShape *string `xml:"BodyShape,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Bottoms struct {
	Category *string `xml:"Category,omitempty"`
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Grain *string `xml:"Grain,omitempty"`
	Style *string `xml:"Style,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Box struct {
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Lug *bool `xml:"Lug,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Cart struct {
	Category *string `xml:"Category,omitempty"`
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Clothing struct {
	Scarf *Scarf `xml:"Scarf,omitempty"`
	Gloves *Gloves `xml:"Gloves,omitempty"`
	Tops *Tops `xml:"Tops,omitempty"`
	Bottoms *Bottoms `xml:"Bottoms,omitempty"`
	Shoes *Shoes `xml:"Shoes,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Gloves struct {
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Wear *bool `xml:"Wear,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type HumanBody struct {
	BodyMetric *BodyMetric `xml:"BodyMetric,omitempty"`
	Clothing *Clothing `xml:"Clothing,omitempty"`
	Belonging *Belonging `xml:"Belonging,omitempty"`
	Behaviour *Behaviour `xml:"Behaviour,omitempty"`
	Belongings *Belongings `xml:"Belongings,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Scarf struct {
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Wear *bool `xml:"Wear,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Shoes struct {
	Category *string `xml:"Category,omitempty"`
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Tops struct {
	Category *string `xml:"Category,omitempty"`
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Grain *string `xml:"Grain,omitempty"`
	Style *string `xml:"Style,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Umbrella struct {
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Open *bool `xml:"Open,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Weapon struct {
	Category *string `xml:"Category,omitempty"`
	Color *tt.ColorDescriptor `xml:"Color,omitempty"`
	Pose *string `xml:"Pose,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

