// Code generated by onvifgen; DO NOT EDIT.

package xop

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
)

type Include struct {
	Any core.Extension `xml:"Any,omitempty"`
	Xhref string `xml:"href,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

