// Code generated by onvifgen; DO NOT EDIT.

// Package xop contains ONVIF-generated types for the
// http://www.w3.org/2004/08/xop/include namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package xop

const NS = "http://www.w3.org/2004/08/xop/include"
