// Code generated by onvifgen; DO NOT EDIT.

package tup

type AuthorizationModes string

const (
	AuthorizationModesMTLS AuthorizationModes = "mTLS"
	AuthorizationModesAccessToken AuthorizationModes = "AccessToken"
)

type ConnectionStatus string

const (
	ConnectionStatusOffline ConnectionStatus = "Offline"
	ConnectionStatusConnecting ConnectionStatus = "Connecting"
	ConnectionStatusConnected ConnectionStatus = "Connected"
)

type Protocols string

const (
	ProtocolsHttps Protocols = "https"
	ProtocolsWss Protocols = "wss"
)

