// Code generated by onvifgen; DO NOT EDIT.

package tds

import (
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type AddIPAddressFilter struct {
	IPAddressFilter tt.IPAddressFilter `xml:"IPAddressFilter"`
}

type AddIPAddressFilterResponse struct {
}

type AddScopes struct {
	ScopeItem []string `xml:"ScopeItem,omitempty"`
}

type AddScopesResponse struct {
}

type Capabilities DeviceServiceCapabilities

type CreateCertificate struct {
	CertificateID *string `xml:"CertificateID,omitempty"`
	Subject *string `xml:"Subject,omitempty"`
	ValidNotBefore *time.Time `xml:"ValidNotBefore,omitempty"`
	ValidNotAfter *time.Time `xml:"ValidNotAfter,omitempty"`
}

type CreateCertificateResponse struct {
	NvtCertificate tt.Certificate `xml:"NvtCertificate"`
}

type CreateDot1XConfiguration struct {
	Dot1XConfiguration tt.Dot1XConfiguration `xml:"Dot1XConfiguration"`
}

type CreateDot1XConfigurationResponse struct {
}

type CreateStorageConfiguration struct {
	StorageConfiguration StorageConfigurationData `xml:"StorageConfiguration"`
}

type CreateStorageConfigurationResponse struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type CreateUsers struct {
	User []tt.User `xml:"User,omitempty"`
}

type CreateUsersResponse struct {
}

type DeleteCertificates struct {
	CertificateID []string `xml:"CertificateID,omitempty"`
}

type DeleteCertificatesResponse struct {
}

type DeleteDot1XConfiguration struct {
	Dot1XConfigurationToken []tt.ReferenceToken `xml:"Dot1XConfigurationToken,omitempty"`
}

type DeleteDot1XConfigurationResponse struct {
}

type DeleteGeoLocation struct {
	Location []tt.LocationEntity `xml:"Location,omitempty"`
}

type DeleteGeoLocationResponse struct {
}

type DeleteStorageConfiguration struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type DeleteStorageConfigurationResponse struct {
}

type DeleteUserRole struct {
	UserRole string `xml:"UserRole"`
}

type DeleteUserRoleResponse struct {
}

type DeleteUsers struct {
	Username []string `xml:"Username,omitempty"`
}

type DeleteUsersResponse struct {
}

type GetAccessPolicy struct {
}

type GetAccessPolicyResponse struct {
	PolicyFile tt.BinaryData `xml:"PolicyFile"`
}

type GetAuthFailureWarningConfiguration struct {
}

type GetAuthFailureWarningConfigurationResponse struct {
	Enabled bool `xml:"Enabled"`
	MonitorPeriod int32 `xml:"MonitorPeriod"`
	MaxAuthFailures int32 `xml:"MaxAuthFailures"`
}

type GetAuthFailureWarningOptions struct {
}

type GetAuthFailureWarningOptionsResponse struct {
	MonitorPeriodRange tt.IntRange `xml:"MonitorPeriodRange"`
	AuthFailureRange tt.IntRange `xml:"AuthFailureRange"`
}

type GetCACertificates struct {
}

type GetCACertificatesResponse struct {
	CACertificate []tt.Certificate `xml:"CACertificate,omitempty"`
}

type GetCapabilities struct {
	Category []tt.CapabilityCategory `xml:"Category,omitempty"`
}

type GetCapabilitiesResponse struct {
	Capabilities tt.Capabilities `xml:"Capabilities"`
}

type GetCertificateInformation struct {
	CertificateID string `xml:"CertificateID"`
}

type GetCertificateInformationResponse struct {
	CertificateInformation tt.CertificateInformation `xml:"CertificateInformation"`
}

type GetCertificates struct {
}

type GetCertificatesResponse struct {
	NvtCertificate []tt.Certificate `xml:"NvtCertificate,omitempty"`
}

type GetCertificatesStatus struct {
}

type GetCertificatesStatusResponse struct {
	CertificateStatus []tt.CertificateStatus `xml:"CertificateStatus,omitempty"`
}

type GetClientCertificateMode struct {
}

type GetClientCertificateModeResponse struct {
	Enabled bool `xml:"Enabled"`
}

type GetDNS struct {
}

type GetDNSResponse struct {
	DNSInformation tt.DNSInformation `xml:"DNSInformation"`
}

type GetDPAddresses struct {
}

type GetDPAddressesResponse struct {
	DPAddress []tt.NetworkHost `xml:"DPAddress,omitempty"`
}

type GetDeviceInformation struct {
}

type GetDeviceInformationResponse struct {
	Manufacturer string `xml:"Manufacturer"`
	Model string `xml:"Model"`
	FirmwareVersion string `xml:"FirmwareVersion"`
	SerialNumber string `xml:"SerialNumber"`
	HardwareId string `xml:"HardwareId"`
}

type GetDiscoveryMode struct {
}

type GetDiscoveryModeResponse struct {
	DiscoveryMode tt.DiscoveryMode `xml:"DiscoveryMode"`
}

type GetDot11Capabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type GetDot11CapabilitiesResponse struct {
	Capabilities tt.Dot11Capabilities `xml:"Capabilities"`
}

type GetDot11Status struct {
	InterfaceToken tt.ReferenceToken `xml:"InterfaceToken"`
}

type GetDot11StatusResponse struct {
	Status tt.Dot11Status `xml:"Status"`
}

type GetDot1XConfiguration struct {
	Dot1XConfigurationToken tt.ReferenceToken `xml:"Dot1XConfigurationToken"`
}

type GetDot1XConfigurationResponse struct {
	Dot1XConfiguration tt.Dot1XConfiguration `xml:"Dot1XConfiguration"`
}

type GetDot1XConfigurations struct {
}

type GetDot1XConfigurationsResponse struct {
	Dot1XConfiguration []tt.Dot1XConfiguration `xml:"Dot1XConfiguration,omitempty"`
}

type GetDynamicDNS struct {
}

type GetDynamicDNSResponse struct {
	DynamicDNSInformation tt.DynamicDNSInformation `xml:"DynamicDNSInformation"`
}

type GetEndpointReference struct {
}

type GetEndpointReferenceResponse struct {
	GUID string `xml:"GUID"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetGeoLocation struct {
}

type GetGeoLocationResponse struct {
	Location []tt.LocationEntity `xml:"Location,omitempty"`
}

type GetHostname struct {
}

type GetHostnameResponse struct {
	HostnameInformation tt.HostnameInformation `xml:"HostnameInformation"`
}

type GetIPAddressFilter struct {
}

type GetIPAddressFilterResponse struct {
	IPAddressFilter tt.IPAddressFilter `xml:"IPAddressFilter"`
}

type GetNTP struct {
}

type GetNTPResponse struct {
	NTPInformation tt.NTPInformation `xml:"NTPInformation"`
}

type GetNetworkDefaultGateway struct {
}

type GetNetworkDefaultGatewayResponse struct {
	NetworkGateway tt.NetworkGateway `xml:"NetworkGateway"`
}

type GetNetworkInterfaces struct {
}

type GetNetworkInterfacesResponse struct {
	NetworkInterfaces []tt.NetworkInterface `xml:"NetworkInterfaces,omitempty"`
}

type GetNetworkProtocols struct {
}

type GetNetworkProtocolsResponse struct {
	NetworkProtocols []tt.NetworkProtocol `xml:"NetworkProtocols,omitempty"`
}

type GetPasswordComplexityConfiguration struct {
}

type GetPasswordComplexityConfigurationResponse struct {
	MinLen *int32 `xml:"MinLen,omitempty"`
	Uppercase *int32 `xml:"Uppercase,omitempty"`
	Number *int32 `xml:"Number,omitempty"`
	SpecialChars *int32 `xml:"SpecialChars,omitempty"`
	BlockUsernameOccurrence *bool `xml:"BlockUsernameOccurrence,omitempty"`
	PolicyConfigurationLocked *bool `xml:"PolicyConfigurationLocked,omitempty"`
}

type GetPasswordComplexityOptions struct {
}

type GetPasswordComplexityOptionsResponse struct {
	MinLenRange *tt.IntRange `xml:"MinLenRange,omitempty"`
	UppercaseRange *tt.IntRange `xml:"UppercaseRange,omitempty"`
	NumberRange *tt.IntRange `xml:"NumberRange,omitempty"`
	SpecialCharsRange *tt.IntRange `xml:"SpecialCharsRange,omitempty"`
	BlockUsernameOccurrenceSupported *bool `xml:"BlockUsernameOccurrenceSupported,omitempty"`
	PolicyConfigurationLockSupported *bool `xml:"PolicyConfigurationLockSupported,omitempty"`
}

type GetPasswordHistoryConfiguration struct {
}

type GetPasswordHistoryConfigurationResponse struct {
	Enabled bool `xml:"Enabled"`
	Length int32 `xml:"Length"`
}

type GetPkcs10Request struct {
	CertificateID string `xml:"CertificateID"`
	Subject *string `xml:"Subject,omitempty"`
	Attributes *tt.BinaryData `xml:"Attributes,omitempty"`
}

type GetPkcs10RequestResponse struct {
	Pkcs10Request tt.BinaryData `xml:"Pkcs10Request"`
}

type GetRelayOutputs struct {
}

type GetRelayOutputsResponse struct {
	RelayOutputs []tt.RelayOutput `xml:"RelayOutputs,omitempty"`
}

type GetRemoteDiscoveryMode struct {
}

type GetRemoteDiscoveryModeResponse struct {
	RemoteDiscoveryMode tt.DiscoveryMode `xml:"RemoteDiscoveryMode"`
}

type GetRemoteUser struct {
}

type GetRemoteUserResponse struct {
	RemoteUser *tt.RemoteUser `xml:"RemoteUser,omitempty"`
}

type GetScopes struct {
}

type GetScopesResponse struct {
	Scopes []tt.Scope `xml:"Scopes,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities DeviceServiceCapabilities `xml:"Capabilities"`
}

type GetServices struct {
	IncludeCapability bool `xml:"IncludeCapability"`
}

type GetServicesResponse struct {
	Service []Service `xml:"Service,omitempty"`
}

type GetStorageConfiguration struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type GetStorageConfigurationResponse struct {
	StorageConfiguration StorageConfiguration `xml:"StorageConfiguration"`
}

type GetStorageConfigurations struct {
}

type GetStorageConfigurationsResponse struct {
	StorageConfigurations []StorageConfiguration `xml:"StorageConfigurations,omitempty"`
}

type GetSystemBackup struct {
}

type GetSystemBackupResponse struct {
	BackupFiles []tt.BackupFile `xml:"BackupFiles,omitempty"`
}

type GetSystemDateAndTime struct {
}

type GetSystemDateAndTimeResponse struct {
	SystemDateAndTime tt.SystemDateTime `xml:"SystemDateAndTime"`
}

type GetSystemLog struct {
	LogType tt.SystemLogType `xml:"LogType"`
}

type GetSystemLogResponse struct {
	SystemLog tt.SystemLog `xml:"SystemLog"`
}

type GetSystemSupportInformation struct {
}

type GetSystemSupportInformationResponse struct {
	SupportInformation tt.SupportInformation `xml:"SupportInformation"`
}

type GetSystemUris struct {
}

type GetSystemUrisResponse struct {
	SystemLogUris *tt.SystemLogUriList `xml:"SystemLogUris,omitempty"`
	SupportInfoUri *string `xml:"SupportInfoUri,omitempty"`
	SystemBackupUri *string `xml:"SystemBackupUri,omitempty"`
}

type GetUserRoles struct {
	UserRole *string `xml:"UserRole,omitempty"`
}

type GetUserRolesResponse struct {
	UserRole []tt.UserRole `xml:"UserRole,omitempty"`
}

type GetUsers struct {
}

type GetUsersResponse struct {
	User []tt.User `xml:"User,omitempty"`
}

type GetWsdlUrl struct {
}

type GetWsdlUrlResponse struct {
	WsdlUrl string `xml:"WsdlUrl"`
}

type GetZeroConfiguration struct {
}

type GetZeroConfigurationResponse struct {
	ZeroConfiguration tt.NetworkZeroConfiguration `xml:"ZeroConfiguration"`
}

type LoadCACertificates struct {
	CACertificate []tt.Certificate `xml:"CACertificate,omitempty"`
}

type LoadCACertificatesResponse struct {
}

type LoadCertificateWithPrivateKey struct {
	CertificateWithPrivateKey []tt.CertificateWithPrivateKey `xml:"CertificateWithPrivateKey,omitempty"`
}

type LoadCertificateWithPrivateKeyResponse struct {
}

type LoadCertificates struct {
	NVTCertificate []tt.Certificate `xml:"NVTCertificate,omitempty"`
}

type LoadCertificatesResponse struct {
}

type RemoveIPAddressFilter struct {
	IPAddressFilter tt.IPAddressFilter `xml:"IPAddressFilter"`
}

type RemoveIPAddressFilterResponse struct {
}

type RemoveScopes struct {
	ScopeItem []string `xml:"ScopeItem,omitempty"`
}

type RemoveScopesResponse struct {
	ScopeItem []string `xml:"ScopeItem,omitempty"`
}

type RestoreSystem struct {
	BackupFiles []tt.BackupFile `xml:"BackupFiles,omitempty"`
}

type RestoreSystemResponse struct {
}

type ScanAvailableDot11Networks struct {
	InterfaceToken tt.ReferenceToken `xml:"InterfaceToken"`
}

type ScanAvailableDot11NetworksResponse struct {
	Networks []tt.Dot11AvailableNetworks `xml:"Networks,omitempty"`
}

type SendAuxiliaryCommand struct {
	AuxiliaryCommand tt.AuxiliaryData `xml:"AuxiliaryCommand"`
}

type SendAuxiliaryCommandResponse struct {
	AuxiliaryCommandResponse *tt.AuxiliaryData `xml:"AuxiliaryCommandResponse,omitempty"`
}

type SetAccessPolicy struct {
	PolicyFile tt.BinaryData `xml:"PolicyFile"`
}

type SetAccessPolicyResponse struct {
}

type SetAuthFailureWarningConfiguration struct {
	Enabled bool `xml:"Enabled"`
	MonitorPeriod int32 `xml:"MonitorPeriod"`
	MaxAuthFailures int32 `xml:"MaxAuthFailures"`
}

type SetAuthFailureWarningConfigurationResponse struct {
}

type SetCertificatesStatus struct {
	CertificateStatus []tt.CertificateStatus `xml:"CertificateStatus,omitempty"`
}

type SetCertificatesStatusResponse struct {
}

type SetClientCertificateMode struct {
	Enabled bool `xml:"Enabled"`
}

type SetClientCertificateModeResponse struct {
}

type SetDNS struct {
	FromDHCP bool `xml:"FromDHCP"`
	SearchDomain []string `xml:"SearchDomain,omitempty"`
	DNSManual []tt.IPAddress `xml:"DNSManual,omitempty"`
}

type SetDNSResponse struct {
}

type SetDPAddresses struct {
	DPAddress []tt.NetworkHost `xml:"DPAddress,omitempty"`
}

type SetDPAddressesResponse struct {
}

type SetDiscoveryMode struct {
	DiscoveryMode tt.DiscoveryMode `xml:"DiscoveryMode"`
}

type SetDiscoveryModeResponse struct {
}

type SetDot1XConfiguration struct {
	Dot1XConfiguration tt.Dot1XConfiguration `xml:"Dot1XConfiguration"`
}

type SetDot1XConfigurationResponse struct {
}

type SetDynamicDNS struct {
	Type tt.DynamicDNSType `xml:"Type"`
	Name *tt.DNSName `xml:"Name,omitempty"`
	TTL **core.Duration `xml:"TTL,omitempty"`
}

type SetDynamicDNSResponse struct {
}

type SetGeoLocation struct {
	Location []tt.LocationEntity `xml:"Location,omitempty"`
}

type SetGeoLocationResponse struct {
}

type SetHashingAlgorithm struct {
	Algorithm tt.StringList `xml:"Algorithm"`
}

type SetHashingAlgorithmResponse struct {
}

type SetHostname struct {
	Name string `xml:"Name"`
}

type SetHostnameFromDHCP struct {
	FromDHCP bool `xml:"FromDHCP"`
}

type SetHostnameFromDHCPResponse struct {
	RebootNeeded bool `xml:"RebootNeeded"`
}

type SetHostnameResponse struct {
}

type SetIPAddressFilter struct {
	IPAddressFilter tt.IPAddressFilter `xml:"IPAddressFilter"`
}

type SetIPAddressFilterResponse struct {
}

type SetNTP struct {
	FromDHCP bool `xml:"FromDHCP"`
	NTPManual []tt.NetworkHost `xml:"NTPManual,omitempty"`
}

type SetNTPResponse struct {
}

type SetNetworkDefaultGateway struct {
	IPv4Address []tt.IPv4Address `xml:"IPv4Address,omitempty"`
	IPv6Address []tt.IPv6Address `xml:"IPv6Address,omitempty"`
}

type SetNetworkDefaultGatewayResponse struct {
}

type SetNetworkInterfaces struct {
	InterfaceToken tt.ReferenceToken `xml:"InterfaceToken"`
	NetworkInterface tt.NetworkInterfaceSetConfiguration `xml:"NetworkInterface"`
}

type SetNetworkInterfacesResponse struct {
	RebootNeeded bool `xml:"RebootNeeded"`
}

type SetNetworkProtocols struct {
	NetworkProtocols []tt.NetworkProtocol `xml:"NetworkProtocols,omitempty"`
}

type SetNetworkProtocolsResponse struct {
}

type SetPasswordComplexityConfiguration struct {
	MinLen *int32 `xml:"MinLen,omitempty"`
	Uppercase *int32 `xml:"Uppercase,omitempty"`
	Number *int32 `xml:"Number,omitempty"`
	SpecialChars *int32 `xml:"SpecialChars,omitempty"`
	BlockUsernameOccurrence *bool `xml:"BlockUsernameOccurrence,omitempty"`
	PolicyConfigurationLocked *bool `xml:"PolicyConfigurationLocked,omitempty"`
}

type SetPasswordComplexityConfigurationResponse struct {
}

type SetPasswordHistoryConfiguration struct {
	Enabled bool `xml:"Enabled"`
	Length int32 `xml:"Length"`
}

type SetPasswordHistoryConfigurationResponse struct {
}

type SetRelayOutputSettings struct {
	RelayOutputToken tt.ReferenceToken `xml:"RelayOutputToken"`
	Properties tt.RelayOutputSettings `xml:"Properties"`
}

type SetRelayOutputSettingsResponse struct {
}

type SetRelayOutputState struct {
	RelayOutputToken tt.ReferenceToken `xml:"RelayOutputToken"`
	LogicalState tt.RelayLogicalState `xml:"LogicalState"`
}

type SetRelayOutputStateResponse struct {
}

type SetRemoteDiscoveryMode struct {
	RemoteDiscoveryMode tt.DiscoveryMode `xml:"RemoteDiscoveryMode"`
}

type SetRemoteDiscoveryModeResponse struct {
}

type SetRemoteUser struct {
	RemoteUser *tt.RemoteUser `xml:"RemoteUser,omitempty"`
}

type SetRemoteUserResponse struct {
}

type SetScopes struct {
	Scopes []string `xml:"Scopes,omitempty"`
}

type SetScopesResponse struct {
}

type SetStorageConfiguration struct {
	StorageConfiguration StorageConfiguration `xml:"StorageConfiguration"`
}

type SetStorageConfigurationResponse struct {
}

type SetSystemDateAndTime struct {
	DateTimeType tt.SetDateTimeType `xml:"DateTimeType"`
	DaylightSavings bool `xml:"DaylightSavings"`
	TimeZone *tt.TimeZone `xml:"TimeZone,omitempty"`
	UTCDateTime *tt.DateTime `xml:"UTCDateTime,omitempty"`
}

type SetSystemDateAndTimeResponse struct {
}

type SetSystemFactoryDefault struct {
	FactoryDefault tt.FactoryDefaultType `xml:"FactoryDefault"`
}

type SetSystemFactoryDefaultResponse struct {
}

type SetUser struct {
	User []tt.User `xml:"User,omitempty"`
}

type SetUserResponse struct {
}

type SetUserRole struct {
	UserRole tt.UserRole `xml:"UserRole"`
}

type SetUserRoleResponse struct {
}

type SetZeroConfiguration struct {
	InterfaceToken tt.ReferenceToken `xml:"InterfaceToken"`
	Enabled bool `xml:"Enabled"`
}

type SetZeroConfigurationResponse struct {
}

type StartFirmwareUpgrade struct {
}

type StartFirmwareUpgradeResponse struct {
	UploadUri string `xml:"UploadUri"`
	UploadDelay *core.Duration `xml:"UploadDelay"`
	ExpectedDownTime *core.Duration `xml:"ExpectedDownTime"`
}

type StartSystemRestore struct {
}

type StartSystemRestoreResponse struct {
	UploadUri string `xml:"UploadUri"`
	ExpectedDownTime *core.Duration `xml:"ExpectedDownTime"`
}

type SystemReboot struct {
}

type SystemRebootResponse struct {
	Message string `xml:"Message"`
}

type UpgradeFirmware struct {
	Version string `xml:"Version"`
}

type UpgradeFirmwareResponse struct {
	ExpectedDownTime *core.Duration `xml:"ExpectedDownTime"`
}

type UpgradeSystemFirmware struct {
	Firmware tt.AttachmentData `xml:"Firmware"`
}

type UpgradeSystemFirmwareResponse struct {
	Message *string `xml:"Message,omitempty"`
}

