// Code generated by onvifgen; DO NOT EDIT.

// Package bd contains ONVIF-generated types for the
// http://www.onvif.org/ver20/analytics/humanbody namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package bd

const NS = "http://www.onvif.org/ver20/analytics/humanbody"
