// Code generated by onvifgen; DO NOT EDIT.

package bd

type BagCategory string

const (
	BagCategoryShoulderBag BagCategory = "ShoulderBag"
	BagCategoryBackpack BagCategory = "Backpack"
	BagCategoryToteBag BagCategory = "ToteBag"
	BagCategoryBriefcase BagCategory = "Briefcase"
	BagCategorySuitcase BagCategory = "Suitcase"
	BagCategorySingleShoulderBag BagCategory = "SingleShoulderBag"
	BagCategoryOther BagCategory = "Other"
)

type BodyShape string

const (
	BodyShapeFat BodyShape = "Fat"
	BodyShapeThin BodyShape = "Thin"
	BodyShapeOther BodyShape = "Other"
)

type BottomsCategory string

const (
	BottomsCategoryTrousers BottomsCategory = "Trousers"
	BottomsCategoryShorts BottomsCategory = "Shorts"
	BottomsCategorySkirt BottomsCategory = "Skirt"
	BottomsCategoryOther BottomsCategory = "Other"
)

type BottomsStyle string

const (
	BottomsStyleFormalPants BottomsStyle = "FormalPants"
	BottomsStyleJeans BottomsStyle = "Jeans"
	BottomsStyleOther BottomsStyle = "Other"
)

type CartCategory string

const (
	CartCategoryBabyCarriage CartCategory = "BabyCarriage"
	CartCategoryTwoWheelVehicle CartCategory = "TwoWheelVehicle"
	CartCategoryTricyle CartCategory = "Tricyle"
	CartCategoryOther CartCategory = "Other"
)

type Grain string

const (
	GrainStria Grain = "Stria"
	GrainPlaid Grain = "Plaid"
	GrainPureColour Grain = "PureColour"
	GrainDecal Grain = "Decal"
	GrainOther Grain = "Other"
)

type HumanActivity string

const (
	HumanActivityWalking HumanActivity = "Walking"
	HumanActivityRunning HumanActivity = "Running"
	HumanActivityFallen HumanActivity = "Fallen"
	HumanActivitySquatting HumanActivity = "Squatting"
	HumanActivitySitting HumanActivity = "Sitting"
	HumanActivityStanding HumanActivity = "Standing"
	HumanActivityDriving HumanActivity = "Driving"
	HumanActivityOther HumanActivity = "Other"
)

type ShoesCategory string

const (
	ShoesCategoryBoots ShoesCategory = "Boots"
	ShoesCategoryLeatherShoes ShoesCategory = "LeatherShoes"
	ShoesCategorySneakers ShoesCategory = "Sneakers"
	ShoesCategorySandal ShoesCategory = "Sandal"
	ShoesCategorySlipper ShoesCategory = "Slipper"
	ShoesCategoryOther ShoesCategory = "Other"
)

type Smoking string

const (
	SmokingNoSmoking Smoking = "NoSmoking"
	SmokingCigar Smoking = "Cigar"
	SmokingElectronicCigarettes Smoking = "ElectronicCigarettes"
	SmokingOther Smoking = "Other"
)

type TopsCategory string

const (
	TopsCategoryLongSleeve TopsCategory = "LongSleeve"
	TopsCategoryShortSleeve TopsCategory = "ShortSleeve"
	TopsCategorySleeveless TopsCategory = "Sleeveless"
	TopsCategoryOther TopsCategory = "Other"
)

type TopsStyle string

const (
	TopsStyleTailor TopsStyle = "Tailor"
	TopsStyleJacket TopsStyle = "Jacket"
	TopsStyleShirt TopsStyle = "Shirt"
	TopsStyleSweater TopsStyle = "Sweater"
	TopsStyleOvercoat TopsStyle = "Overcoat"
	TopsStyleDress TopsStyle = "Dress"
	TopsStyleVest TopsStyle = "Vest"
	TopsStyleSafetyVest TopsStyle = "SafetyVest"
	TopsStyleOther TopsStyle = "Other"
)

type UsingMobile string

const (
	UsingMobileByLeftHand UsingMobile = "ByLeftHand"
	UsingMobileByRightHand UsingMobile = "ByRightHand"
	UsingMobileOther UsingMobile = "Other"
)

type WeaponCategory string

const (
	WeaponCategoryKnife WeaponCategory = "Knife"
	WeaponCategoryRifle WeaponCategory = "Rifle"
	WeaponCategoryPistol WeaponCategory = "Pistol"
	WeaponCategoryRevolver WeaponCategory = "Revolver"
)

type WeaponPose string

const (
	WeaponPoseInHolster WeaponPose = "InHolster"
	WeaponPoseInHand WeaponPose = "InHand"
	WeaponPoseAiming WeaponPose = "Aiming"
)

