// Code generated by onvifgen; DO NOT EDIT.

package trt

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type Capabilities struct {
	ProfileCapabilities ProfileCapabilities `xml:"ProfileCapabilities"`
	StreamingCapabilities StreamingCapabilities `xml:"StreamingCapabilities"`
	Any core.Extension `xml:"Any,omitempty"`
	SnapshotUri bool `xml:"SnapshotUri,omitempty,attr"`
	Rotation bool `xml:"Rotation,omitempty,attr"`
	VideoSourceMode bool `xml:"VideoSourceMode,omitempty,attr"`
	OSD bool `xml:"OSD,omitempty,attr"`
	TemporaryOSDText bool `xml:"TemporaryOSDText,omitempty,attr"`
	EXICompression bool `xml:"EXICompression,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type ProfileCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MaximumNumberOfProfiles int32 `xml:"MaximumNumberOfProfiles,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type StreamingCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	RTPMulticast bool `xml:"RTPMulticast,omitempty,attr"`
	RTP_TCP bool `xml:"RTP_TCP,omitempty,attr"`
	RTP_RTSP_TCP bool `xml:"RTP_RTSP_TCP,omitempty,attr"`
	NonAggregateControl bool `xml:"NonAggregateControl,omitempty,attr"`
	NoRTSPStreaming bool `xml:"NoRTSPStreaming,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type VideoSourceMode struct {
	MaxFramerate float32 `xml:"MaxFramerate"`
	MaxResolution tt.VideoResolution `xml:"MaxResolution"`
	Encodings tt.StringList `xml:"Encodings"`
	Reboot bool `xml:"Reboot"`
	Description *tt.Description `xml:"Description,omitempty"`
	Extension *VideoSourceModeExtension `xml:"Extension,omitempty"`
	Xtoken tt.ReferenceToken `xml:"token,attr"`
	Enabled bool `xml:"Enabled,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type VideoSourceModeExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

