// Code generated by onvifgen; DO NOT EDIT.

package timg

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type Capabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	ImageStabilization bool `xml:"ImageStabilization,omitempty,attr"`
	Presets bool `xml:"Presets,omitempty,attr"`
	AdaptablePreset bool `xml:"AdaptablePreset,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// Type describing the Imaging Preset settings.
type ImagingPreset struct {
	Name tt.Name `xml:"Name"`
	Xtoken tt.ReferenceToken `xml:"token,attr"`
	Xtype string `xml:"type,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

