// Code generated by onvifgen; DO NOT EDIT.

package timg

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type GetCurrentPreset struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetCurrentPresetResponse struct {
	Preset *ImagingPreset `xml:"Preset,omitempty"`
}

type GetImagingSettings struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetImagingSettingsResponse struct {
	ImagingSettings tt.ImagingSettings20 `xml:"ImagingSettings"`
}

type GetMoveOptions struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetMoveOptionsResponse struct {
	MoveOptions tt.MoveOptions20 `xml:"MoveOptions"`
}

type GetOptions struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetOptionsResponse struct {
	ImagingOptions tt.ImagingOptions20 `xml:"ImagingOptions"`
}

type GetPresets struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetPresetsResponse struct {
	Preset []ImagingPreset `xml:"Preset,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type GetStatus struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetStatusResponse struct {
	Status tt.ImagingStatus20 `xml:"Status"`
}

type Move struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	Focus tt.FocusMove `xml:"Focus"`
}

type MoveResponse struct {
}

type SetCurrentPreset struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	PresetToken tt.ReferenceToken `xml:"PresetToken"`
}

type SetCurrentPresetResponse struct {
}

type SetImagingSettings struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	ImagingSettings tt.ImagingSettings20 `xml:"ImagingSettings"`
	ForcePersistence *bool `xml:"ForcePersistence,omitempty"`
}

type SetImagingSettingsResponse struct {
}

type Stop struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type StopResponse struct {
}

