// Code generated by onvifgen; DO NOT EDIT.

package trp

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type Capabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	ReversePlayback bool `xml:"ReversePlayback,omitempty,attr"`
	SessionTimeoutRange tt.FloatList `xml:"SessionTimeoutRange,omitempty,attr"`
	RTP_RTSP_TCP bool `xml:"RTP_RTSP_TCP,omitempty,attr"`
	RTSPWebSocketUri string `xml:"RTSPWebSocketUri,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

