// Code generated by onvifgen; DO NOT EDIT.

package advancedsecurity

import (
	"context"
	"net/http"

	"github.com/furrysalamander/onvif-go/onvif/soaphdr"
	"github.com/furrysalamander/onvif-go/onvif/schema/tas"
)

const actionBase = "http://www.onvif.org/ver10/advancedsecurity/wsdl"

type Client struct {
	c *soaphdr.Client
}

func NewClient(endpoint, username, password string) *Client {
	return &Client{c: soaphdr.New(endpoint, username, password)}
}

func NewClientWithTransport(c *soaphdr.Client) *Client {
	return &Client{c: c}
}

func (c *Client) HTTP() *http.Client { return c.c.HTTP }
func (c *Client) SetHTTP(h *http.Client) { c.c.HTTP = h }

func (c *Client) AddCertPathValidationPolicyAssignment(ctx context.Context) (*tas.AddCertPathValidationPolicyAssignmentResponse, error) {
	out := &tas.AddCertPathValidationPolicyAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/AddCertPathValidationPolicyAssignment", &tas.AddCertPathValidationPolicyAssignment{}, out)
	return out, err
}

func (c *Client) AddDot1XConfiguration(ctx context.Context) (*tas.AddDot1XConfigurationResponse, error) {
	out := &tas.AddDot1XConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/AddDot1XConfiguration", &tas.AddDot1XConfiguration{}, out)
	return out, err
}

func (c *Client) AddMediaSigningCertificateAssignment(ctx context.Context) (*tas.AddMediaSigningCertificateAssignmentResponse, error) {
	out := &tas.AddMediaSigningCertificateAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/AddMediaSigningCertificateAssignment", &tas.AddMediaSigningCertificateAssignment{}, out)
	return out, err
}

func (c *Client) AddServerCertificateAssignment(ctx context.Context) (*tas.AddServerCertificateAssignmentResponse, error) {
	out := &tas.AddServerCertificateAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/AddServerCertificateAssignment", &tas.AddServerCertificateAssignment{}, out)
	return out, err
}

func (c *Client) CreateAuthorizationServerConfiguration(ctx context.Context) (*tas.CreateAuthorizationServerConfigurationResponse, error) {
	out := &tas.CreateAuthorizationServerConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreateAuthorizationServerConfiguration", &tas.CreateAuthorizationServerConfiguration{}, out)
	return out, err
}

func (c *Client) CreateCertPathValidationPolicy(ctx context.Context) (*tas.CreateCertPathValidationPolicyResponse, error) {
	out := &tas.CreateCertPathValidationPolicyResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreateCertPathValidationPolicy", &tas.CreateCertPathValidationPolicy{}, out)
	return out, err
}

func (c *Client) CreateCertificationPath(ctx context.Context) (*tas.CreateCertificationPathResponse, error) {
	out := &tas.CreateCertificationPathResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreateCertificationPath", &tas.CreateCertificationPath{}, out)
	return out, err
}

func (c *Client) CreateECCKeyPair(ctx context.Context) (*tas.CreateECCKeyPairResponse, error) {
	out := &tas.CreateECCKeyPairResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreateECCKeyPair", &tas.CreateECCKeyPair{}, out)
	return out, err
}

func (c *Client) CreatePKCS10CSR(ctx context.Context) (*tas.CreatePKCS10CSRResponse, error) {
	out := &tas.CreatePKCS10CSRResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreatePKCS10CSR", &tas.CreatePKCS10CSR{}, out)
	return out, err
}

func (c *Client) CreateRSAKeyPair(ctx context.Context) (*tas.CreateRSAKeyPairResponse, error) {
	out := &tas.CreateRSAKeyPairResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreateRSAKeyPair", &tas.CreateRSAKeyPair{}, out)
	return out, err
}

func (c *Client) CreateSelfSignedCertificate(ctx context.Context) (*tas.CreateSelfSignedCertificateResponse, error) {
	out := &tas.CreateSelfSignedCertificateResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/CreateSelfSignedCertificate", &tas.CreateSelfSignedCertificate{}, out)
	return out, err
}

func (c *Client) DeleteAuthorizationServerConfiguration(ctx context.Context) (*tas.DeleteAuthorizationServerConfigurationResponse, error) {
	out := &tas.DeleteAuthorizationServerConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteAuthorizationServerConfiguration", &tas.DeleteAuthorizationServerConfiguration{}, out)
	return out, err
}

func (c *Client) DeleteCRL(ctx context.Context) (*tas.DeleteCRLResponse, error) {
	out := &tas.DeleteCRLResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteCRL", &tas.DeleteCRL{}, out)
	return out, err
}

func (c *Client) DeleteCertPathValidationPolicy(ctx context.Context) (*tas.DeleteCertPathValidationPolicyResponse, error) {
	out := &tas.DeleteCertPathValidationPolicyResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteCertPathValidationPolicy", &tas.DeleteCertPathValidationPolicy{}, out)
	return out, err
}

func (c *Client) DeleteCertificate(ctx context.Context) (*tas.DeleteCertificateResponse, error) {
	out := &tas.DeleteCertificateResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteCertificate", &tas.DeleteCertificate{}, out)
	return out, err
}

func (c *Client) DeleteCertificationPath(ctx context.Context) (*tas.DeleteCertificationPathResponse, error) {
	out := &tas.DeleteCertificationPathResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteCertificationPath", &tas.DeleteCertificationPath{}, out)
	return out, err
}

func (c *Client) DeleteDot1XConfiguration(ctx context.Context) (*tas.DeleteDot1XConfigurationResponse, error) {
	out := &tas.DeleteDot1XConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteDot1XConfiguration", &tas.DeleteDot1XConfiguration{}, out)
	return out, err
}

func (c *Client) DeleteKey(ctx context.Context) (*tas.DeleteKeyResponse, error) {
	out := &tas.DeleteKeyResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteKey", &tas.DeleteKey{}, out)
	return out, err
}

func (c *Client) DeleteNetworkInterfaceDot1XConfiguration(ctx context.Context) (*tas.DeleteNetworkInterfaceDot1XConfigurationResponse, error) {
	out := &tas.DeleteNetworkInterfaceDot1XConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeleteNetworkInterfaceDot1XConfiguration", &tas.DeleteNetworkInterfaceDot1XConfiguration{}, out)
	return out, err
}

func (c *Client) DeletePassphrase(ctx context.Context) (*tas.DeletePassphraseResponse, error) {
	out := &tas.DeletePassphraseResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/DeletePassphrase", &tas.DeletePassphrase{}, out)
	return out, err
}

func (c *Client) GetAllCRLs(ctx context.Context) (*tas.GetAllCRLsResponse, error) {
	out := &tas.GetAllCRLsResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllCRLs", &tas.GetAllCRLs{}, out)
	return out, err
}

func (c *Client) GetAllCertPathValidationPolicies(ctx context.Context) (*tas.GetAllCertPathValidationPoliciesResponse, error) {
	out := &tas.GetAllCertPathValidationPoliciesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllCertPathValidationPolicies", &tas.GetAllCertPathValidationPolicies{}, out)
	return out, err
}

func (c *Client) GetAllCertificates(ctx context.Context) (*tas.GetAllCertificatesResponse, error) {
	out := &tas.GetAllCertificatesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllCertificates", &tas.GetAllCertificates{}, out)
	return out, err
}

func (c *Client) GetAllCertificationPaths(ctx context.Context) (*tas.GetAllCertificationPathsResponse, error) {
	out := &tas.GetAllCertificationPathsResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllCertificationPaths", &tas.GetAllCertificationPaths{}, out)
	return out, err
}

func (c *Client) GetAllDot1XConfigurations(ctx context.Context) (*tas.GetAllDot1XConfigurationsResponse, error) {
	out := &tas.GetAllDot1XConfigurationsResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllDot1XConfigurations", &tas.GetAllDot1XConfigurations{}, out)
	return out, err
}

func (c *Client) GetAllKeys(ctx context.Context) (*tas.GetAllKeysResponse, error) {
	out := &tas.GetAllKeysResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllKeys", &tas.GetAllKeys{}, out)
	return out, err
}

func (c *Client) GetAllPassphrases(ctx context.Context) (*tas.GetAllPassphrasesResponse, error) {
	out := &tas.GetAllPassphrasesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAllPassphrases", &tas.GetAllPassphrases{}, out)
	return out, err
}

func (c *Client) GetAssignedCertPathValidationPolicies(ctx context.Context) (*tas.GetAssignedCertPathValidationPoliciesResponse, error) {
	out := &tas.GetAssignedCertPathValidationPoliciesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAssignedCertPathValidationPolicies", &tas.GetAssignedCertPathValidationPolicies{}, out)
	return out, err
}

func (c *Client) GetAssignedMediaSigningCertificates(ctx context.Context) (*tas.GetAssignedMediaSigningCertificatesResponse, error) {
	out := &tas.GetAssignedMediaSigningCertificatesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAssignedMediaSigningCertificates", &tas.GetAssignedMediaSigningCertificates{}, out)
	return out, err
}

func (c *Client) GetAssignedServerCertificates(ctx context.Context) (*tas.GetAssignedServerCertificatesResponse, error) {
	out := &tas.GetAssignedServerCertificatesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAssignedServerCertificates", &tas.GetAssignedServerCertificates{}, out)
	return out, err
}

func (c *Client) GetAuthorizationServerConfigurations(ctx context.Context) (*tas.GetAuthorizationServerConfigurationsResponse, error) {
	out := &tas.GetAuthorizationServerConfigurationsResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetAuthorizationServerConfigurations", &tas.GetAuthorizationServerConfigurations{}, out)
	return out, err
}

func (c *Client) GetCRL(ctx context.Context) (*tas.GetCRLResponse, error) {
	out := &tas.GetCRLResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetCRL", &tas.GetCRL{}, out)
	return out, err
}

func (c *Client) GetCertPathValidationPolicy(ctx context.Context) (*tas.GetCertPathValidationPolicyResponse, error) {
	out := &tas.GetCertPathValidationPolicyResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetCertPathValidationPolicy", &tas.GetCertPathValidationPolicy{}, out)
	return out, err
}

func (c *Client) GetCertificate(ctx context.Context) (*tas.GetCertificateResponse, error) {
	out := &tas.GetCertificateResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetCertificate", &tas.GetCertificate{}, out)
	return out, err
}

func (c *Client) GetCertificationPath(ctx context.Context) (*tas.GetCertificationPathResponse, error) {
	out := &tas.GetCertificationPathResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetCertificationPath", &tas.GetCertificationPath{}, out)
	return out, err
}

func (c *Client) GetClientAuthenticationRequired(ctx context.Context) (*tas.GetClientAuthenticationRequiredResponse, error) {
	out := &tas.GetClientAuthenticationRequiredResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetClientAuthenticationRequired", &tas.GetClientAuthenticationRequired{}, out)
	return out, err
}

func (c *Client) GetCnMapsToUser(ctx context.Context) (*tas.GetCnMapsToUserResponse, error) {
	out := &tas.GetCnMapsToUserResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetCnMapsToUser", &tas.GetCnMapsToUser{}, out)
	return out, err
}

func (c *Client) GetDot1XConfiguration(ctx context.Context) (*tas.GetDot1XConfigurationResponse, error) {
	out := &tas.GetDot1XConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetDot1XConfiguration", &tas.GetDot1XConfiguration{}, out)
	return out, err
}

func (c *Client) GetEnabledTLSVersions(ctx context.Context) (*tas.GetEnabledTLSVersionsResponse, error) {
	out := &tas.GetEnabledTLSVersionsResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetEnabledTLSVersions", &tas.GetEnabledTLSVersions{}, out)
	return out, err
}

func (c *Client) GetJWTConfiguration(ctx context.Context) (*tas.GetJWTConfigurationResponse, error) {
	out := &tas.GetJWTConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetJWTConfiguration", &tas.GetJWTConfiguration{}, out)
	return out, err
}

func (c *Client) GetKeyStatus(ctx context.Context) (*tas.GetKeyStatusResponse, error) {
	out := &tas.GetKeyStatusResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetKeyStatus", &tas.GetKeyStatus{}, out)
	return out, err
}

func (c *Client) GetNetworkInterfaceDot1XConfiguration(ctx context.Context) (*tas.GetNetworkInterfaceDot1XConfigurationResponse, error) {
	out := &tas.GetNetworkInterfaceDot1XConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetNetworkInterfaceDot1XConfiguration", &tas.GetNetworkInterfaceDot1XConfiguration{}, out)
	return out, err
}

func (c *Client) GetPrivateKeyStatus(ctx context.Context) (*tas.GetPrivateKeyStatusResponse, error) {
	out := &tas.GetPrivateKeyStatusResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetPrivateKeyStatus", &tas.GetPrivateKeyStatus{}, out)
	return out, err
}

func (c *Client) GetServiceCapabilities(ctx context.Context) (*tas.GetServiceCapabilitiesResponse, error) {
	out := &tas.GetServiceCapabilitiesResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/GetServiceCapabilities", &tas.GetServiceCapabilities{}, out)
	return out, err
}

func (c *Client) RemoveCertPathValidationPolicyAssignment(ctx context.Context) (*tas.RemoveCertPathValidationPolicyAssignmentResponse, error) {
	out := &tas.RemoveCertPathValidationPolicyAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/RemoveCertPathValidationPolicyAssignment", &tas.RemoveCertPathValidationPolicyAssignment{}, out)
	return out, err
}

func (c *Client) RemoveMediaSigningCertificateAssignment(ctx context.Context) (*tas.RemoveMediaSigningCertificateAssignmentResponse, error) {
	out := &tas.RemoveMediaSigningCertificateAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/RemoveMediaSigningCertificateAssignment", &tas.RemoveMediaSigningCertificateAssignment{}, out)
	return out, err
}

func (c *Client) RemoveServerCertificateAssignment(ctx context.Context) (*tas.RemoveServerCertificateAssignmentResponse, error) {
	out := &tas.RemoveServerCertificateAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/RemoveServerCertificateAssignment", &tas.RemoveServerCertificateAssignment{}, out)
	return out, err
}

func (c *Client) ReplaceCertPathValidationPolicyAssignment(ctx context.Context) (*tas.ReplaceCertPathValidationPolicyAssignmentResponse, error) {
	out := &tas.ReplaceCertPathValidationPolicyAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/ReplaceCertPathValidationPolicyAssignment", &tas.ReplaceCertPathValidationPolicyAssignment{}, out)
	return out, err
}

func (c *Client) ReplaceServerCertificateAssignment(ctx context.Context) (*tas.ReplaceServerCertificateAssignmentResponse, error) {
	out := &tas.ReplaceServerCertificateAssignmentResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/ReplaceServerCertificateAssignment", &tas.ReplaceServerCertificateAssignment{}, out)
	return out, err
}

func (c *Client) SetAuthorizationServerConfiguration(ctx context.Context) (*tas.SetAuthorizationServerConfigurationResponse, error) {
	out := &tas.SetAuthorizationServerConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetAuthorizationServerConfiguration", &tas.SetAuthorizationServerConfiguration{}, out)
	return out, err
}

func (c *Client) SetCertPathValidationPolicy(ctx context.Context) (*tas.SetCertPathValidationPolicyResponse, error) {
	out := &tas.SetCertPathValidationPolicyResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetCertPathValidationPolicy", &tas.SetCertPathValidationPolicy{}, out)
	return out, err
}

func (c *Client) SetCertificationPath(ctx context.Context) (*tas.SetCertificationPathResponse, error) {
	out := &tas.SetCertificationPathResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetCertificationPath", &tas.SetCertificationPath{}, out)
	return out, err
}

func (c *Client) SetClientAuthenticationRequired(ctx context.Context) (*tas.SetClientAuthenticationRequiredResponse, error) {
	out := &tas.SetClientAuthenticationRequiredResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetClientAuthenticationRequired", &tas.SetClientAuthenticationRequired{}, out)
	return out, err
}

func (c *Client) SetCnMapsToUser(ctx context.Context) (*tas.SetCnMapsToUserResponse, error) {
	out := &tas.SetCnMapsToUserResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetCnMapsToUser", &tas.SetCnMapsToUser{}, out)
	return out, err
}

func (c *Client) SetEnabledTLSVersions(ctx context.Context) (*tas.SetEnabledTLSVersionsResponse, error) {
	out := &tas.SetEnabledTLSVersionsResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetEnabledTLSVersions", &tas.SetEnabledTLSVersions{}, out)
	return out, err
}

func (c *Client) SetJWTConfiguration(ctx context.Context) (*tas.SetJWTConfigurationResponse, error) {
	out := &tas.SetJWTConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetJWTConfiguration", &tas.SetJWTConfiguration{}, out)
	return out, err
}

func (c *Client) SetNetworkInterfaceDot1XConfiguration(ctx context.Context) (*tas.SetNetworkInterfaceDot1XConfigurationResponse, error) {
	out := &tas.SetNetworkInterfaceDot1XConfigurationResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/SetNetworkInterfaceDot1XConfiguration", &tas.SetNetworkInterfaceDot1XConfiguration{}, out)
	return out, err
}

func (c *Client) UploadCRL(ctx context.Context) (*tas.UploadCRLResponse, error) {
	out := &tas.UploadCRLResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/UploadCRL", &tas.UploadCRL{}, out)
	return out, err
}

func (c *Client) UploadCertificate(ctx context.Context) (*tas.UploadCertificateResponse, error) {
	out := &tas.UploadCertificateResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/UploadCertificate", &tas.UploadCertificate{}, out)
	return out, err
}

func (c *Client) UploadCertificateWithPrivateKeyInPKCS12(ctx context.Context) (*tas.UploadCertificateWithPrivateKeyInPKCS12Response, error) {
	out := &tas.UploadCertificateWithPrivateKeyInPKCS12Response{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/UploadCertificateWithPrivateKeyInPKCS12", &tas.UploadCertificateWithPrivateKeyInPKCS12{}, out)
	return out, err
}

func (c *Client) UploadKeyPairInPKCS8(ctx context.Context) (*tas.UploadKeyPairInPKCS8Response, error) {
	out := &tas.UploadKeyPairInPKCS8Response{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/UploadKeyPairInPKCS8", &tas.UploadKeyPairInPKCS8{}, out)
	return out, err
}

func (c *Client) UploadPassphrase(ctx context.Context) (*tas.UploadPassphraseResponse, error) {
	out := &tas.UploadPassphraseResponse{}
	err := c.c.Do("http://www.onvif.org/ver10/advancedsecurity/wsdl/UploadPassphrase", &tas.UploadPassphrase{}, out)
	return out, err
}

