// Code generated by onvifgen; DO NOT EDIT.

package tev

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsn"
)

type Capabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	WSSubscriptionPolicySupport bool `xml:"WSSubscriptionPolicySupport,omitempty,attr"`
	WSPausableSubscriptionManagerInterfaceSupport bool `xml:"WSPausableSubscriptionManagerInterfaceSupport,omitempty,attr"`
	MaxNotificationProducers int32 `xml:"MaxNotificationProducers,omitempty,attr"`
	MaxPullPoints int32 `xml:"MaxPullPoints,omitempty,attr"`
	PersistentNotificationStorage bool `xml:"PersistentNotificationStorage,omitempty,attr"`
	EventBrokerProtocols string `xml:"EventBrokerProtocols,omitempty,attr"`
	MaxEventBrokers int32 `xml:"MaxEventBrokers,omitempty,attr"`
	MetadataOverMQTT bool `xml:"MetadataOverMQTT,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type EventBrokerConfig struct {
	Address string `xml:"Address"`
	TopicPrefix string `xml:"TopicPrefix"`
	UserName *string `xml:"UserName,omitempty"`
	Password *string `xml:"Password,omitempty"`
	CertificateID *string `xml:"CertificateID,omitempty"`
	PublishFilter *wsn.FilterType `xml:"PublishFilter,omitempty"`
	QoS *int32 `xml:"QoS,omitempty"`
	Status *string `xml:"Status,omitempty"`
	CertPathValidationPolicyID *string `xml:"CertPathValidationPolicyID,omitempty"`
	MetadataFilter *wsn.FilterType `xml:"MetadataFilter,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

