// Code generated by onvifgen; DO NOT EDIT.

package tev

import (
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsa"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsn"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsnt"
)

type AddEventBroker struct {
	EventBroker EventBrokerConfig `xml:"EventBroker"`
}

type AddEventBrokerResponse struct {
}

// When this element is included in the SubscriptionPolicy, the pullpoint shall not provide Initialized or Deleted events for Properties.
type ChangedOnly struct{}

type CreatePullPointSubscription struct {
	Filter *wsn.FilterType `xml:"Filter,omitempty"`
	InitialTerminationTime *wsn.AbsoluteOrRelativeTimeType `xml:"InitialTerminationTime,omitempty"`
}

type CreatePullPointSubscriptionResponse struct {
	SubscriptionReference wsa.EndpointReferenceType `xml:"SubscriptionReference"`
	Base37 time.Time `xml:""`
	Base38 time.Time `xml:""`
	Any core.Extension `xml:"Any,omitempty"`
}

type DeleteEventBroker struct {
	Address string `xml:"Address"`
}

type DeleteEventBrokerResponse struct {
}

type GetEventBrokers struct {
	Address *string `xml:"Address,omitempty"`
}

type GetEventBrokersResponse struct {
	EventBroker []EventBrokerConfig `xml:"EventBroker,omitempty"`
}

type GetEventProperties struct {
}

type GetEventPropertiesResponse struct {
	TopicNamespaceLocation []string `xml:"TopicNamespaceLocation,omitempty"`
	Base39 bool `xml:""`
	Base40 wsnt.TopicSetType `xml:""`
	Base41 []string `xml:",omitempty"`
	MessageContentFilterDialect []string `xml:"MessageContentFilterDialect,omitempty"`
	ProducerPropertiesFilterDialect []string `xml:"ProducerPropertiesFilterDialect,omitempty"`
	MessageContentSchemaLocation []string `xml:"MessageContentSchemaLocation,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type PullMessages struct {
	Timeout *core.Duration `xml:"Timeout"`
	MessageLimit int32 `xml:"MessageLimit"`
	Any core.Extension `xml:"Any,omitempty"`
}

type PullMessagesFaultResponse struct {
	MaxTimeout *core.Duration `xml:"MaxTimeout"`
	MaxMessageLimit int32 `xml:"MaxMessageLimit"`
	Any core.Extension `xml:"Any,omitempty"`
}

type PullMessagesResponse struct {
	CurrentTime time.Time `xml:"CurrentTime"`
	TerminationTime time.Time `xml:"TerminationTime"`
	Base42 []wsn.NotificationMessageHolderType `xml:",omitempty"`
}

type Seek struct {
	UtcTime time.Time `xml:"UtcTime"`
	Reverse *bool `xml:"Reverse,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SeekResponse struct {
}

type SetSynchronizationPoint struct {
}

type SetSynchronizationPointResponse struct {
}

