// Code generated by onvifgen; DO NOT EDIT.

// Package tab contains ONVIF-generated types for the
// http://www.onvif.org/ver10/authenticationbehavior/wsdl namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package tab

const NS = "http://www.onvif.org/ver10/authenticationbehavior/wsdl"
