// Code generated by onvifgen; DO NOT EDIT.

package tt

type AFModes string

const (
	AFModesOnceAfterMove AFModes = "OnceAfterMove"
)

// AudioClassType acceptable values are;
// gun_shot, scream, glass_breaking, tire_screech
type AudioClassType string

const (
	AudioClassTypeGun_shot AudioClassType = "gun_shot"
	AudioClassTypeScream AudioClassType = "scream"
	AudioClassTypeGlass_breaking AudioClassType = "glass_breaking"
	AudioClassTypeTire_screech AudioClassType = "tire_screech"
)

type AudioClassification string

const (
	AudioClassificationGunShot AudioClassification = "GunShot"
	AudioClassificationScream AudioClassification = "Scream"
	AudioClassificationGlassBreaking AudioClassification = "GlassBreaking"
	AudioClassificationTireScreech AudioClassification = "TireScreech"
	AudioClassificationAlarm AudioClassification = "Alarm"
)

type AudioEncoding string

const (
	AudioEncodingG711 AudioEncoding = "G711"
	AudioEncodingG726 AudioEncoding = "G726"
	AudioEncodingAAC AudioEncoding = "AAC"
)

// Audio Media Subtypes as referenced by IANA (without the leading "audio/" Audio Media Type and except for the audio types defined in the restriction).  See also .
type AudioEncodingMimeNames string

const (
	AudioEncodingMimeNamesPCMU AudioEncodingMimeNames = "PCMU"
	AudioEncodingMimeNamesG726 AudioEncodingMimeNames = "G726"
	AudioEncodingMimeNamesMP4A_LATM AudioEncodingMimeNames = "MP4A-LATM"
	AudioEncodingMimeNamesMpeg4_generic AudioEncodingMimeNames = "mpeg4-generic"
)

type AutoFocusMode string

const (
	AutoFocusModeAUTO AutoFocusMode = "AUTO"
	AutoFocusModeMANUAL AutoFocusMode = "MANUAL"
)

type AuxiliaryData string

// Enumeration describing the available backlight compenstation modes.
type BacklightCompensationMode string

const (
	BacklightCompensationModeOFF BacklightCompensationMode = "OFF"
	BacklightCompensationModeON BacklightCompensationMode = "ON"
)

type CapabilityCategory string

const (
	CapabilityCategoryAll CapabilityCategory = "All"
	CapabilityCategoryAnalytics CapabilityCategory = "Analytics"
	CapabilityCategoryDevice CapabilityCategory = "Device"
	CapabilityCategoryEvents CapabilityCategory = "Events"
	CapabilityCategoryImaging CapabilityCategory = "Imaging"
	CapabilityCategoryMedia CapabilityCategory = "Media"
	CapabilityCategoryPTZ CapabilityCategory = "PTZ"
)

type DNSName string

type DefoggingMode string

const (
	DefoggingModeOFF DefoggingMode = "OFF"
	DefoggingModeON DefoggingMode = "ON"
	DefoggingModeAUTO DefoggingMode = "AUTO"
)

type Description string

type DigitalIdleState string

const (
	DigitalIdleStateClosed DigitalIdleState = "closed"
	DigitalIdleStateOpen DigitalIdleState = "open"
)

type Direction ExtendedDirection

type DiscoveryMode string

const (
	DiscoveryModeDiscoverable DiscoveryMode = "Discoverable"
	DiscoveryModeNonDiscoverable DiscoveryMode = "NonDiscoverable"
)

type Domain string

type Dot11AuthAndMangementSuite string

const (
	Dot11AuthAndMangementSuiteNone Dot11AuthAndMangementSuite = "None"
	Dot11AuthAndMangementSuiteDot1X Dot11AuthAndMangementSuite = "Dot1X"
	Dot11AuthAndMangementSuitePSK Dot11AuthAndMangementSuite = "PSK"
	Dot11AuthAndMangementSuiteExtended Dot11AuthAndMangementSuite = "Extended"
)

type Dot11Cipher string

const (
	Dot11CipherCCMP Dot11Cipher = "CCMP"
	Dot11CipherTKIP Dot11Cipher = "TKIP"
	Dot11CipherAny Dot11Cipher = "Any"
	Dot11CipherExtended Dot11Cipher = "Extended"
)

type Dot11PSK []byte

type Dot11PSKPassphrase string

type Dot11SSIDType []byte

type Dot11SecurityMode string

const (
	Dot11SecurityModeNone Dot11SecurityMode = "None"
	Dot11SecurityModeWEP Dot11SecurityMode = "WEP"
	Dot11SecurityModePSK Dot11SecurityMode = "PSK"
	Dot11SecurityModeDot1X Dot11SecurityMode = "Dot1X"
	Dot11SecurityModeExtended Dot11SecurityMode = "Extended"
)

type Dot11SignalStrength string

const (
	Dot11SignalStrengthNone Dot11SignalStrength = "None"
	Dot11SignalStrengthVery_Bad Dot11SignalStrength = "Very Bad"
	Dot11SignalStrengthBad Dot11SignalStrength = "Bad"
	Dot11SignalStrengthGood Dot11SignalStrength = "Good"
	Dot11SignalStrengthVery_Good Dot11SignalStrength = "Very Good"
	Dot11SignalStrengthExtended Dot11SignalStrength = "Extended"
)

type Dot11StationMode string

const (
	Dot11StationModeAd_hoc Dot11StationMode = "Ad-hoc"
	Dot11StationModeInfrastructure Dot11StationMode = "Infrastructure"
	Dot11StationModeExtended Dot11StationMode = "Extended"
)

type Duplex string

const (
	DuplexFull Duplex = "Full"
	DuplexHalf Duplex = "Half"
)

type DynamicDNSType string

const (
	DynamicDNSTypeNoUpdate DynamicDNSType = "NoUpdate"
	DynamicDNSTypeClientUpdates DynamicDNSType = "ClientUpdates"
	DynamicDNSTypeServerUpdates DynamicDNSType = "ServerUpdates"
)

type EFlipMode string

const (
	EFlipModeOFF EFlipMode = "OFF"
	EFlipModeON EFlipMode = "ON"
	EFlipModeExtended EFlipMode = "Extended"
)

type Enabled string

const (
	EnabledENABLED Enabled = "ENABLED"
	EnabledDISABLED Enabled = "DISABLED"
)

type EncryptionMode string

const (
	EncryptionModeCENC EncryptionMode = "CENC"
	EncryptionModeCBCS EncryptionMode = "CBCS"
)

type Entity string

const (
	EntityDevice Entity = "Device"
	EntityVideoSource Entity = "VideoSource"
	EntityAudioSource Entity = "AudioSource"
)

type ExposureMode string

const (
	ExposureModeAUTO ExposureMode = "AUTO"
	ExposureModeMANUAL ExposureMode = "MANUAL"
)

type ExposurePriority string

const (
	ExposurePriorityLowNoise ExposurePriority = "LowNoise"
	ExposurePriorityFrameRate ExposurePriority = "FrameRate"
)

// Entering represents object coming into the polygon boundary.
// Exiting represents object going out of the polygon boundary.
// Approaching represents distance of object to camera sensor decreasing over time.
// Departing represents distance of object to camera sensor increasing over time.
type ExtendedDirection string

const (
	ExtendedDirectionLeft ExtendedDirection = "Left"
	ExtendedDirectionRight ExtendedDirection = "Right"
	ExtendedDirectionAny ExtendedDirection = "Any"
	ExtendedDirectionEntering ExtendedDirection = "Entering"
	ExtendedDirectionExiting ExtendedDirection = "Exiting"
	ExtendedDirectionApproaching ExtendedDirection = "Approaching"
	ExtendedDirectionDeparting ExtendedDirection = "Departing"
)

// Enumeration describing the available factory default modes.
type FactoryDefaultType string

const (
	FactoryDefaultTypeHard FactoryDefaultType = "Hard"
	FactoryDefaultTypeSoft FactoryDefaultType = "Soft"
)

type FloatList []float32

type H264Profile string

const (
	H264ProfileBaseline H264Profile = "Baseline"
	H264ProfileMain H264Profile = "Main"
	H264ProfileExtended H264Profile = "Extended"
	H264ProfileHigh H264Profile = "High"
)

type HwAddress string

type IANAIfTypes int32

type IPAddressFilterType string

const (
	IPAddressFilterTypeAllow IPAddressFilterType = "Allow"
	IPAddressFilterTypeDeny IPAddressFilterType = "Deny"
)

type IPType string

const (
	IPTypeIPv4 IPType = "IPv4"
	IPTypeIPv6 IPType = "IPv6"
)

type IPv4Address string

type IPv6Address string

type IPv6DHCPConfiguration string

const (
	IPv6DHCPConfigurationAuto IPv6DHCPConfiguration = "Auto"
	IPv6DHCPConfigurationStateful IPv6DHCPConfiguration = "Stateful"
	IPv6DHCPConfigurationStateless IPv6DHCPConfiguration = "Stateless"
	IPv6DHCPConfigurationOff IPv6DHCPConfiguration = "Off"
)

type ImageSendingType string

const (
	ImageSendingTypeEmbedded ImageSendingType = "Embedded"
	ImageSendingTypeLocalStorage ImageSendingType = "LocalStorage"
	ImageSendingTypeRemoteStorage ImageSendingType = "RemoteStorage"
)

type ImageStabilizationMode string

const (
	ImageStabilizationModeOFF ImageStabilizationMode = "OFF"
	ImageStabilizationModeON ImageStabilizationMode = "ON"
	ImageStabilizationModeAUTO ImageStabilizationMode = "AUTO"
	ImageStabilizationModeExtended ImageStabilizationMode = "Extended"
)

type IntList []int32

type IrCutFilterAutoBoundaryType string

const (
	IrCutFilterAutoBoundaryTypeCommon IrCutFilterAutoBoundaryType = "Common"
	IrCutFilterAutoBoundaryTypeToOn IrCutFilterAutoBoundaryType = "ToOn"
	IrCutFilterAutoBoundaryTypeToOff IrCutFilterAutoBoundaryType = "ToOff"
	IrCutFilterAutoBoundaryTypeExtended IrCutFilterAutoBoundaryType = "Extended"
)

type IrCutFilterMode string

const (
	IrCutFilterModeON IrCutFilterMode = "ON"
	IrCutFilterModeOFF IrCutFilterMode = "OFF"
	IrCutFilterModeAUTO IrCutFilterMode = "AUTO"
)

type JobToken ReferenceToken

type MetadataCompressionType string

const (
	MetadataCompressionTypeNone MetadataCompressionType = "None"
	MetadataCompressionTypeGZIP MetadataCompressionType = "GZIP"
	MetadataCompressionTypeEXI MetadataCompressionType = "EXI"
)

type ModeOfOperation string

const (
	ModeOfOperationIdle ModeOfOperation = "Idle"
	ModeOfOperationActive ModeOfOperation = "Active"
	ModeOfOperationUnknown ModeOfOperation = "Unknown"
)

type MoveAndTrackMethod string

const (
	MoveAndTrackMethodPresetToken MoveAndTrackMethod = "PresetToken"
	MoveAndTrackMethodGeoLocation MoveAndTrackMethod = "GeoLocation"
	MoveAndTrackMethodPTZVector MoveAndTrackMethod = "PTZVector"
	MoveAndTrackMethodObjectID MoveAndTrackMethod = "ObjectID"
)

type MoveStatus string

const (
	MoveStatusIDLE MoveStatus = "IDLE"
	MoveStatusMOVING MoveStatus = "MOVING"
	MoveStatusUNKNOWN MoveStatus = "UNKNOWN"
)

type Mpeg4Profile string

const (
	Mpeg4ProfileSP Mpeg4Profile = "SP"
	Mpeg4ProfileASP Mpeg4Profile = "ASP"
)

// User readable name. Length up to 64 characters.
type Name string

type NetworkHostType string

const (
	NetworkHostTypeIPv4 NetworkHostType = "IPv4"
	NetworkHostTypeIPv6 NetworkHostType = "IPv6"
	NetworkHostTypeDNS NetworkHostType = "DNS"
)

type NetworkInterfaceConfigPriority int32

type NetworkProtocolType string

const (
	NetworkProtocolTypeHTTP NetworkProtocolType = "HTTP"
	NetworkProtocolTypeHTTPS NetworkProtocolType = "HTTPS"
	NetworkProtocolTypeRTSP NetworkProtocolType = "RTSP"
)

type OSDType string

const (
	OSDTypeText OSDType = "Text"
	OSDTypeImage OSDType = "Image"
	OSDTypeExtended OSDType = "Extended"
)

type PTZPresetTourDirection string

const (
	PTZPresetTourDirectionForward PTZPresetTourDirection = "Forward"
	PTZPresetTourDirectionBackward PTZPresetTourDirection = "Backward"
	PTZPresetTourDirectionExtended PTZPresetTourDirection = "Extended"
)

type PTZPresetTourOperation string

const (
	PTZPresetTourOperationStart PTZPresetTourOperation = "Start"
	PTZPresetTourOperationStop PTZPresetTourOperation = "Stop"
	PTZPresetTourOperationPause PTZPresetTourOperation = "Pause"
	PTZPresetTourOperationExtended PTZPresetTourOperation = "Extended"
)

type PTZPresetTourState string

const (
	PTZPresetTourStateIdle PTZPresetTourState = "Idle"
	PTZPresetTourStateTouring PTZPresetTourState = "Touring"
	PTZPresetTourStatePaused PTZPresetTourState = "Paused"
	PTZPresetTourStateExtended PTZPresetTourState = "Extended"
)

type PropertyOperation string

const (
	PropertyOperationInitialized PropertyOperation = "Initialized"
	PropertyOperationDeleted PropertyOperation = "Deleted"
	PropertyOperationChanged PropertyOperation = "Changed"
)

// Specifies a receiver connection mode.
type ReceiverMode string

const (
	ReceiverModeAutoConnect ReceiverMode = "AutoConnect"
	ReceiverModeAlwaysConnect ReceiverMode = "AlwaysConnect"
	ReceiverModeNeverConnect ReceiverMode = "NeverConnect"
	ReceiverModeUnknown ReceiverMode = "Unknown"
)

type ReceiverReference ReferenceToken

// Specifies the current connection state of the receiver.
type ReceiverState string

const (
	ReceiverStateNotConnected ReceiverState = "NotConnected"
	ReceiverStateConnecting ReceiverState = "Connecting"
	ReceiverStateConnected ReceiverState = "Connected"
	ReceiverStateUnknown ReceiverState = "Unknown"
)

type RecordingJobMode string

type RecordingJobReference ReferenceToken

type RecordingJobState string

type RecordingReference ReferenceToken

type RecordingStatus string

const (
	RecordingStatusInitiated RecordingStatus = "Initiated"
	RecordingStatusRecording RecordingStatus = "Recording"
	RecordingStatusStopped RecordingStatus = "Stopped"
	RecordingStatusRemoving RecordingStatus = "Removing"
	RecordingStatusRemoved RecordingStatus = "Removed"
	RecordingStatusUnknown RecordingStatus = "Unknown"
)

// Unique identifier for a physical or logical resource.
// Tokens should be assigned such that they are unique within a device. Tokens must be at least unique within its class.
// Length up to 64 characters. Token may be extended by intermediate terminal with adding prefix to make it global unique.
// The length should be within 36 characters for generating at local device. See "Remote Token" section in Resource Query specification.
type ReferenceToken string

type ReferenceTokenList []ReferenceToken

type RelayIdleState string

const (
	RelayIdleStateClosed RelayIdleState = "closed"
	RelayIdleStateOpen RelayIdleState = "open"
)

type RelayLogicalState string

const (
	RelayLogicalStateActive RelayLogicalState = "active"
	RelayLogicalStateInactive RelayLogicalState = "inactive"
)

type RelayMode string

const (
	RelayModeMonostable RelayMode = "Monostable"
	RelayModeBistable RelayMode = "Bistable"
)

type ReverseMode string

const (
	ReverseModeOFF ReverseMode = "OFF"
	ReverseModeON ReverseMode = "ON"
	ReverseModeAUTO ReverseMode = "AUTO"
	ReverseModeExtended ReverseMode = "Extended"
)

type RotateMode string

const (
	RotateModeOFF RotateMode = "OFF"
	RotateModeON RotateMode = "ON"
	RotateModeAUTO RotateMode = "AUTO"
)

type SceneOrientationMode string

const (
	SceneOrientationModeMANUAL SceneOrientationMode = "MANUAL"
	SceneOrientationModeAUTO SceneOrientationMode = "AUTO"
)

type SceneOrientationOption string

const (
	SceneOrientationOptionBelow SceneOrientationOption = "Below"
	SceneOrientationOptionHorizon SceneOrientationOption = "Horizon"
	SceneOrientationOptionAbove SceneOrientationOption = "Above"
)

type ScopeDefinition string

const (
	ScopeDefinitionFixed ScopeDefinition = "Fixed"
	ScopeDefinitionConfigurable ScopeDefinition = "Configurable"
)

type SearchState string

const (
	SearchStateQueued SearchState = "Queued"
	SearchStateSearching SearchState = "Searching"
	SearchStateCompleted SearchState = "Completed"
	SearchStateUnknown SearchState = "Unknown"
)

type SetDateTimeType string

const (
	SetDateTimeTypeManual SetDateTimeType = "Manual"
	SetDateTimeTypeNTP SetDateTimeType = "NTP"
)

type StreamType string

const (
	StreamTypeRTP_Unicast StreamType = "RTP-Unicast"
	StreamTypeRTP_Multicast StreamType = "RTP-Multicast"
)

type StringAttrList []string

type StringList []string

// Enumeration describing the available system log modes.
type SystemLogType string

const (
	SystemLogTypeSystem SystemLogType = "System"
	SystemLogTypeAccess SystemLogType = "Access"
)

type TargetFormat string

const (
	TargetFormatMP4 TargetFormat = "MP4"
	TargetFormatCMAF TargetFormat = "CMAF"
)

type ToneCompensationMode string

const (
	ToneCompensationModeOFF ToneCompensationMode = "OFF"
	ToneCompensationModeON ToneCompensationMode = "ON"
	ToneCompensationModeAUTO ToneCompensationMode = "AUTO"
)

type TrackReference ReferenceToken

type TrackType string

const (
	TrackTypeVideo TrackType = "Video"
	TrackTypeAudio TrackType = "Audio"
	TrackTypeMetadata TrackType = "Metadata"
	TrackTypeExtended TrackType = "Extended"
)

type TransportProtocol string

const (
	TransportProtocolUDP TransportProtocol = "UDP"
	TransportProtocolTCP TransportProtocol = "TCP"
	TransportProtocolRTSP TransportProtocol = "RTSP"
	TransportProtocolHTTP TransportProtocol = "HTTP"
)

type UserLevel string

const (
	UserLevelAdministrator UserLevel = "Administrator"
	UserLevelOperator UserLevel = "Operator"
	UserLevelUser UserLevel = "User"
	UserLevelAnonymous UserLevel = "Anonymous"
	UserLevelExtended UserLevel = "Extended"
)

type VideoEncoding string

const (
	VideoEncodingJPEG VideoEncoding = "JPEG"
	VideoEncodingMPEG4 VideoEncoding = "MPEG4"
	VideoEncodingH264 VideoEncoding = "H264"
)

// Video Media Subtypes as referenced by IANA (without the leading "video/" Video Media Type).  See also .
type VideoEncodingMimeNames string

const (
	VideoEncodingMimeNamesJPEG VideoEncodingMimeNames = "JPEG"
	VideoEncodingMimeNamesMPV4_ES VideoEncodingMimeNames = "MPV4-ES"
	VideoEncodingMimeNamesH264 VideoEncodingMimeNames = "H264"
	VideoEncodingMimeNamesH265 VideoEncodingMimeNames = "H265"
)

type VideoEncodingProfiles string

const (
	VideoEncodingProfilesSimple VideoEncodingProfiles = "Simple"
	VideoEncodingProfilesAdvancedSimple VideoEncodingProfiles = "AdvancedSimple"
	VideoEncodingProfilesBaseline VideoEncodingProfiles = "Baseline"
	VideoEncodingProfilesMain VideoEncodingProfiles = "Main"
	VideoEncodingProfilesMain10 VideoEncodingProfiles = "Main10"
	VideoEncodingProfilesExtended VideoEncodingProfiles = "Extended"
	VideoEncodingProfilesHigh VideoEncodingProfiles = "High"
)

// Source view modes supported by device.
type ViewModes string

const (
	ViewModesTt_Fisheye ViewModes = "tt:Fisheye"
	ViewModesTt_360Panorama ViewModes = "tt:360Panorama"
	ViewModesTt_180Panorama ViewModes = "tt:180Panorama"
	ViewModesTt_Quad ViewModes = "tt:Quad"
	ViewModesTt_Original ViewModes = "tt:Original"
	ViewModesTt_LeftHalf ViewModes = "tt:LeftHalf"
	ViewModesTt_RightHalf ViewModes = "tt:RightHalf"
	ViewModesTt_Dewarp ViewModes = "tt:Dewarp"
)

type WhiteBalanceMode string

const (
	WhiteBalanceModeAUTO WhiteBalanceMode = "AUTO"
	WhiteBalanceModeMANUAL WhiteBalanceMode = "MANUAL"
)

type WideDynamicMode string

const (
	WideDynamicModeOFF WideDynamicMode = "OFF"
	WideDynamicModeON WideDynamicMode = "ON"
)

type XPathExpression string

