package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/furrysalamander/onvif-go/internal/onvifgen/ir"
)

// Generator emits Go source files into a file map (relative path → contents).
type Generator struct {
	Tab          *SymTab
	EmitPackages []string // package ids to emit (e.g. "tt", "tds")
	OutBase      string   // repository-relative base dir, e.g. "onvif/schema"
}

// Generate returns the file map for all EmitPackages.
func (g *Generator) Generate() (map[string]string, error) {
	out := map[string]string{}
	for _, pkg := range g.EmitPackages {
		ns, ok := PkgNS[pkg]
		if !ok {
			return nil, fmt.Errorf("codegen: unknown package %q", pkg)
		}
		simple, complex, elements, _, _, _ := g.Tab.GroupedByKind(ns)

		r := &resolver{tab: g.Tab, curPkg: pkg}
		sortSimple(simple)
		sortComplex(complex)
		sortElements(elements)

		// Each file gets its own import set so unused imports don't bleed
		// across simpletypes/complextypes/elements.
		simpleImports := newImportSet()
		simpleImports.curPkg = pkg
		complexImports := newImportSet()
		complexImports.curPkg = pkg
		elementImports := newImportSet()
		elementImports.curPkg = pkg

		simpleSrc, simpleUses := g.emitSimple(simple, r, simpleImports)
		complexSrc, complexUses := g.emitComplex(complex, r, complexImports)
		elementSrc, elementUses := g.emitElements(elements, r, elementImports)

		_ = simpleUses
		_ = complexUses
		_ = elementUses

		files := []struct {
			name    string
			body    string
			imports *importSet
		}{
			{"simpletypes_gen.go", simpleSrc, simpleImports},
			{"complextypes_gen.go", complexSrc, complexImports},
			{"elements_gen.go", elementSrc, elementImports},
		}
		base := strings.TrimRight(g.OutBase, "/") + "/" + pkg
		for _, f := range files {
			if f.body == "" {
				continue
			}
			path := base + "/" + f.name
			out[path] = renderFile(pkg, f.body, f.imports)
		}
		out[base+"/doc_gen.go"] = renderDocFile(pkg, ns)
	}
	return out, nil
}

func (g *Generator) emitSimple(types []*ir.SimpleType, r *resolver, imports *importSet) (string, bool) {
	var b strings.Builder
	for _, st := range types {
		b.WriteString(emitSimpleType(st, r))
	}
	scanImports(b.String(), imports)
	return b.String(), b.Len() > 0
}

func (g *Generator) emitComplex(types []*ir.ComplexType, r *resolver, imports *importSet) (string, bool) {
	var b strings.Builder
	for _, ct := range types {
		src := emitComplexType(ct, r)
		if src == "" {
			continue
		}
		b.WriteString(src)
	}
	scanImports(b.String(), imports)
	return b.String(), b.Len() > 0
}

func (g *Generator) emitElements(els []*ir.Element, r *resolver, imports *importSet) (string, bool) {
	var b strings.Builder
	for _, e := range els {
		src := emitElement(e, r)
		if src == "" {
			continue
		}
		b.WriteString(src)
	}
	scanImports(b.String(), imports)
	return b.String(), b.Len() > 0
}

// scanImports inspects emitted source and toggles import flags for every
// onvif schema package and stdlib import it references.
func scanImports(src string, imports *importSet) {
	for id := range PkgNS {
		if id == "" {
			continue
		}
		needle := id + "."
		if strings.Contains(src, needle) {
			if id == imports.curPkg {
				continue // same-package ref needs no import
			}
			imports.addOnvif(id)
		}
	}
	if strings.Contains(src, "xml.") || strings.Contains(src, "[]xml.Attr") {
		imports.addStd("encoding/xml")
	}
	if strings.Contains(src, "time.Time") {
		imports.addStd("time")
	}
}

// importSet tracks which imports a generated file needs.
type importSet struct {
	std    map[string]struct{}
	onvif  map[string]struct{} // pkg id → path
	usesTT bool
	curPkg string
}

func newImportSet() *importSet {
	return &importSet{std: map[string]struct{}{}, onvif: map[string]struct{}{}}
}

func (s *importSet) addStd(p string) { s.std[p] = struct{}{} }
func (s *importSet) addOnvif(id string) {
	if id == "" {
		return
	}
	s.onvif[id] = struct{}{}
	s.usesTT = s.usesTT || id == "tt"
}

// renderFile wraps body with the DO NOT EDIT header, package clause, and
// sorted imports (stdlib group first, then onvif schema group).
func renderFile(pkg, body string, imports *importSet) string {
	var b strings.Builder
	b.WriteString("// Code generated by onvifgen; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	std := make([]string, 0, len(imports.std))
	for p := range imports.std {
		std = append(std, p)
	}
	sort.Strings(std)
	onvifPkgs := make([]string, 0, len(imports.onvif))
	for id := range imports.onvif {
		onvifPkgs = append(onvifPkgs, id)
	}
	sort.Strings(onvifPkgs)
	if len(std) == 0 && len(onvifPkgs) == 0 {
		b.WriteString(body)
		return b.String()
	}
	b.WriteString("import (\n")
	for _, p := range std {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	if len(std) > 0 && len(onvifPkgs) > 0 {
		b.WriteByte('\n')
	}
	for _, id := range onvifPkgs {
		fmt.Fprintf(&b, "\t%q\n", importPath(id))
	}
	b.WriteString(")\n\n")
	b.WriteString(body)
	return b.String()
}

// renderDocFile emits the package doc comment.
func renderDocFile(pkg, ns string) string {
	var b strings.Builder
	b.WriteString("// Code generated by onvifgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// Package %s contains ONVIF-generated types for the\n", pkg)
	fmt.Fprintf(&b, "// %s namespace.\n", ns)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Generated from vendored WSDL/XSD schemas committed under\n")
	fmt.Fprintf(&b, "// internal/catalog/. See the catalog NOTICE.md for provenance.\n")
	fmt.Fprintf(&b, "package %s\n\nconst NS = %q\n", pkg, ns)
	return b.String()
}

func sortSimple(s []*ir.SimpleType) {
	sort.SliceStable(s, func(i, j int) bool { return s[i].Name < s[j].Name })
}

func sortElements(s []*ir.Element) {
	sort.SliceStable(s, func(i, j int) bool { return s[i].Name < s[j].Name })
}
