// Code generated by onvifgen; DO NOT EDIT.

package tac

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/pacs"
)

// The AccessPoint structure shall include all properties of the AccessPointInfo structure,
// a reference to an authentication profile instance, and optionally a number of input and output devices.
type AccessPoint struct {
	Base53 AccessPointInfo `xml:",omitempty"`
	AuthenticationProfileToken *pacs.ReferenceToken `xml:"AuthenticationProfileToken,omitempty"`
	Extension *AccessPointExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The AccessPoint capabilities reflect optional functionality of a particular physical entity.
// Different AccessPoint instances may have different set of capabilities. This information may
// change during device operation, e.g. if hardware settings are changed.
// The following capabilities are available:
type AccessPointCapabilities struct {
	SupportedSecurityLevels []pacs.ReferenceToken `xml:"SupportedSecurityLevels,omitempty"`
	Extension *SupportedSecurityLevelsExtension `xml:"Extension,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	DisableAccessPoint bool `xml:"DisableAccessPoint,attr"`
	Duress bool `xml:"Duress,omitempty,attr"`
	AnonymousAccess bool `xml:"AnonymousAccess,omitempty,attr"`
	AccessTaken bool `xml:"AccessTaken,omitempty,attr"`
	ExternalAuthorization bool `xml:"ExternalAuthorization,omitempty,attr"`
	SupportedRecognitionTypes pacs.StringList `xml:"SupportedRecognitionTypes,omitempty,attr"`
	IdentifierAccess bool `xml:"IdentifierAccess,omitempty,attr"`
	SupportedFeedbackTypes pacs.StringList `xml:"SupportedFeedbackTypes,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type AccessPointExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

// The AccessPointInfo structure contains basic information about an access point instance.
// An access point defines an entity a credential can be granted or denied access to.
// The AccessPointInfo structure provides basic information on how access is controlled
// in one direction for a door (from which area to which area).
// Multiple access points may cover the same door. A typical case is one access point for
// entry and another for exit, both referencing the same door.
type AccessPointInfo struct {
	Base54 AccessPointInfoBase `xml:",omitempty"`
	Capabilities AccessPointCapabilities `xml:"Capabilities"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// Used as extension base for AccessPointInfo.
type AccessPointInfoBase struct {
	Base55 pacs.DataEntity `xml:",omitempty"`
	Name pacs.Name `xml:"Name"`
	Description *pacs.Description `xml:"Description,omitempty"`
	AreaFrom *pacs.ReferenceToken `xml:"AreaFrom,omitempty"`
	AreaTo *pacs.ReferenceToken `xml:"AreaTo,omitempty"`
	EntityType **core.QName `xml:"EntityType,omitempty"`
	Entity pacs.ReferenceToken `xml:"Entity"`
}

// The AccessPointState contains state information for an AccessPoint.
// An ONVIF compliant device shall provide the following fields for each AccessPoint instance:
type AccessPointState struct {
	Enabled bool `xml:"Enabled"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// The Area structure shall include all properties of the AreaInfo structure and optionally
// a parent area token, an OccupancyControl structure and/or an Antipassback structure.
type Area struct {
	Base56 AreaInfo `xml:",omitempty"`
	Extension *AreaExtension `xml:"Extension,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type AreaExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

// The AreaInfo structure contains basic information about an Area.
// An ONVIF compliant device shall provide the following fields for each Area:
type AreaInfo struct {
	Base57 AreaInfoBase `xml:",omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// Basic information about an Area. Used as extension base.
type AreaInfoBase struct {
	Base58 pacs.DataEntity `xml:",omitempty"`
	Name pacs.Name `xml:"Name"`
	Description *pacs.Description `xml:"Description,omitempty"`
}

// The service capabilities reflect optional functionality of a service.
// The information is static and does not change during device operation.
// The following capabilities are available:
type ServiceCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MaxLimit int64 `xml:"MaxLimit,attr"`
	MaxAccessPoints int64 `xml:"MaxAccessPoints,omitempty,attr"`
	MaxAreas int64 `xml:"MaxAreas,omitempty,attr"`
	ClientSuppliedTokenSupported bool `xml:"ClientSuppliedTokenSupported,omitempty,attr"`
	AccessPointManagementSupported bool `xml:"AccessPointManagementSupported,omitempty,attr"`
	AreaManagementSupported bool `xml:"AreaManagementSupported,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type SupportedSecurityLevelsExtension struct {
	Any core.Extension `xml:"Any,omitempty"`
}

