// Code generated by onvifgen; DO NOT EDIT.

package trt

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type AddAudioDecoderConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddAudioDecoderConfigurationResponse struct {
}

type AddAudioEncoderConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddAudioEncoderConfigurationResponse struct {
}

type AddAudioOutputConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddAudioOutputConfigurationResponse struct {
}

type AddAudioSourceConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddAudioSourceConfigurationResponse struct {
}

type AddMetadataConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddMetadataConfigurationResponse struct {
}

type AddPTZConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddPTZConfigurationResponse struct {
}

type AddVideoAnalyticsConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddVideoAnalyticsConfigurationResponse struct {
}

type AddVideoEncoderConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddVideoEncoderConfigurationResponse struct {
}

type AddVideoSourceConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type AddVideoSourceConfigurationResponse struct {
}

type CreateOSD struct {
	OSD tt.OSDConfiguration `xml:"OSD"`
	Any core.Extension `xml:"Any,omitempty"`
}

type CreateOSDResponse struct {
	OSDToken tt.ReferenceToken `xml:"OSDToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type CreateProfile struct {
	Name tt.Name `xml:"Name"`
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
}

type CreateProfileResponse struct {
	Profile tt.Profile `xml:"Profile"`
}

type DeleteOSD struct {
	OSDToken tt.ReferenceToken `xml:"OSDToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type DeleteOSDResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type DeleteProfile struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type DeleteProfileResponse struct {
}

type GetAudioDecoderConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetAudioDecoderConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetAudioDecoderConfigurationOptionsResponse struct {
	Options tt.AudioDecoderConfigurationOptions `xml:"Options"`
}

type GetAudioDecoderConfigurationResponse struct {
	Configuration tt.AudioDecoderConfiguration `xml:"Configuration"`
}

type GetAudioDecoderConfigurations struct {
}

type GetAudioDecoderConfigurationsResponse struct {
	Configurations []tt.AudioDecoderConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioEncoderConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetAudioEncoderConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetAudioEncoderConfigurationOptionsResponse struct {
	Options tt.AudioEncoderConfigurationOptions `xml:"Options"`
}

type GetAudioEncoderConfigurationResponse struct {
	Configuration tt.AudioEncoderConfiguration `xml:"Configuration"`
}

type GetAudioEncoderConfigurations struct {
}

type GetAudioEncoderConfigurationsResponse struct {
	Configurations []tt.AudioEncoderConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioOutputConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetAudioOutputConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetAudioOutputConfigurationOptionsResponse struct {
	Options tt.AudioOutputConfigurationOptions `xml:"Options"`
}

type GetAudioOutputConfigurationResponse struct {
	Configuration tt.AudioOutputConfiguration `xml:"Configuration"`
}

type GetAudioOutputConfigurations struct {
}

type GetAudioOutputConfigurationsResponse struct {
	Configurations []tt.AudioOutputConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioOutputs struct {
}

type GetAudioOutputsResponse struct {
	AudioOutputs []tt.AudioOutput `xml:"AudioOutputs,omitempty"`
}

type GetAudioSourceConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetAudioSourceConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetAudioSourceConfigurationOptionsResponse struct {
	Options tt.AudioSourceConfigurationOptions `xml:"Options"`
}

type GetAudioSourceConfigurationResponse struct {
	Configuration tt.AudioSourceConfiguration `xml:"Configuration"`
}

type GetAudioSourceConfigurations struct {
}

type GetAudioSourceConfigurationsResponse struct {
	Configurations []tt.AudioSourceConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioSources struct {
}

type GetAudioSourcesResponse struct {
	AudioSources []tt.AudioSource `xml:"AudioSources,omitempty"`
}

type GetCompatibleAudioDecoderConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleAudioDecoderConfigurationsResponse struct {
	Configurations []tt.AudioDecoderConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleAudioEncoderConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleAudioEncoderConfigurationsResponse struct {
	Configurations []tt.AudioEncoderConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleAudioOutputConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleAudioOutputConfigurationsResponse struct {
	Configurations []tt.AudioOutputConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleAudioSourceConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleAudioSourceConfigurationsResponse struct {
	Configurations []tt.AudioSourceConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleMetadataConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleMetadataConfigurationsResponse struct {
	Configurations []tt.MetadataConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleVideoAnalyticsConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleVideoAnalyticsConfigurationsResponse struct {
	Configurations []tt.VideoAnalyticsConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleVideoEncoderConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleVideoEncoderConfigurationsResponse struct {
	Configurations []tt.VideoEncoderConfiguration `xml:"Configurations,omitempty"`
}

type GetCompatibleVideoSourceConfigurations struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetCompatibleVideoSourceConfigurationsResponse struct {
	Configurations []tt.VideoSourceConfiguration `xml:"Configurations,omitempty"`
}

type GetGuaranteedNumberOfVideoEncoderInstances struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetGuaranteedNumberOfVideoEncoderInstancesResponse struct {
	TotalNumber int32 `xml:"TotalNumber"`
	JPEG *int32 `xml:"JPEG,omitempty"`
	H264 *int32 `xml:"H264,omitempty"`
	MPEG4 *int32 `xml:"MPEG4,omitempty"`
}

type GetMetadataConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetMetadataConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetMetadataConfigurationOptionsResponse struct {
	Options tt.MetadataConfigurationOptions `xml:"Options"`
}

type GetMetadataConfigurationResponse struct {
	Configuration tt.MetadataConfiguration `xml:"Configuration"`
}

type GetMetadataConfigurations struct {
}

type GetMetadataConfigurationsResponse struct {
	Configurations []tt.MetadataConfiguration `xml:"Configurations,omitempty"`
}

type GetOSD struct {
	OSDToken tt.ReferenceToken `xml:"OSDToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetOSDOptions struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetOSDOptionsResponse struct {
	OSDOptions tt.OSDConfigurationOptions `xml:"OSDOptions"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetOSDResponse struct {
	OSD tt.OSDConfiguration `xml:"OSD"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetOSDs struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
}

type GetOSDsResponse struct {
	OSDs []tt.OSDConfiguration `xml:"OSDs,omitempty"`
}

type GetProfile struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetProfileResponse struct {
	Profile tt.Profile `xml:"Profile"`
}

type GetProfiles struct {
}

type GetProfilesResponse struct {
	Profiles []tt.Profile `xml:"Profiles,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type GetSnapshotUri struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetSnapshotUriResponse struct {
	MediaUri tt.MediaUri `xml:"MediaUri"`
}

type GetStreamUri struct {
	StreamSetup tt.StreamSetup `xml:"StreamSetup"`
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetStreamUriResponse struct {
	MediaUri tt.MediaUri `xml:"MediaUri"`
}

type GetVideoAnalyticsConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetVideoAnalyticsConfigurationResponse struct {
	Configuration tt.VideoAnalyticsConfiguration `xml:"Configuration"`
}

type GetVideoAnalyticsConfigurations struct {
}

type GetVideoAnalyticsConfigurationsResponse struct {
	Configurations []tt.VideoAnalyticsConfiguration `xml:"Configurations,omitempty"`
}

type GetVideoEncoderConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetVideoEncoderConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetVideoEncoderConfigurationOptionsResponse struct {
	Options tt.VideoEncoderConfigurationOptions `xml:"Options"`
}

type GetVideoEncoderConfigurationResponse struct {
	Configuration tt.VideoEncoderConfiguration `xml:"Configuration"`
}

type GetVideoEncoderConfigurations struct {
}

type GetVideoEncoderConfigurationsResponse struct {
	Configurations []tt.VideoEncoderConfiguration `xml:"Configurations,omitempty"`
}

type GetVideoSourceConfiguration struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetVideoSourceConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type GetVideoSourceConfigurationOptionsResponse struct {
	Options tt.VideoSourceConfigurationOptions `xml:"Options"`
}

type GetVideoSourceConfigurationResponse struct {
	Configuration tt.VideoSourceConfiguration `xml:"Configuration"`
}

type GetVideoSourceConfigurations struct {
}

type GetVideoSourceConfigurationsResponse struct {
	Configurations []tt.VideoSourceConfiguration `xml:"Configurations,omitempty"`
}

type GetVideoSourceModes struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetVideoSourceModesResponse struct {
	VideoSourceModes []VideoSourceMode `xml:"VideoSourceModes,omitempty"`
}

type GetVideoSources struct {
}

type GetVideoSourcesResponse struct {
	VideoSources []tt.VideoSource `xml:"VideoSources,omitempty"`
}

type RemoveAudioDecoderConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveAudioDecoderConfigurationResponse struct {
}

type RemoveAudioEncoderConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveAudioEncoderConfigurationResponse struct {
}

type RemoveAudioOutputConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveAudioOutputConfigurationResponse struct {
}

type RemoveAudioSourceConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveAudioSourceConfigurationResponse struct {
}

type RemoveMetadataConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveMetadataConfigurationResponse struct {
}

type RemovePTZConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemovePTZConfigurationResponse struct {
}

type RemoveVideoAnalyticsConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveVideoAnalyticsConfigurationResponse struct {
}

type RemoveVideoEncoderConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveVideoEncoderConfigurationResponse struct {
}

type RemoveVideoSourceConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type RemoveVideoSourceConfigurationResponse struct {
}

type SetAudioDecoderConfiguration struct {
	Configuration tt.AudioDecoderConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetAudioDecoderConfigurationResponse struct {
}

type SetAudioEncoderConfiguration struct {
	Configuration tt.AudioEncoderConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetAudioEncoderConfigurationResponse struct {
}

type SetAudioOutputConfiguration struct {
	Configuration tt.AudioOutputConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetAudioOutputConfigurationResponse struct {
}

type SetAudioSourceConfiguration struct {
	Configuration tt.AudioSourceConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetAudioSourceConfigurationResponse struct {
}

type SetMetadataConfiguration struct {
	Configuration tt.MetadataConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetMetadataConfigurationResponse struct {
}

type SetOSD struct {
	OSD tt.OSDConfiguration `xml:"OSD"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetOSDResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type SetSynchronizationPoint struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type SetSynchronizationPointResponse struct {
}

type SetVideoAnalyticsConfiguration struct {
	Configuration tt.VideoAnalyticsConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetVideoAnalyticsConfigurationResponse struct {
}

type SetVideoEncoderConfiguration struct {
	Configuration tt.VideoEncoderConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetVideoEncoderConfigurationResponse struct {
}

type SetVideoSourceConfiguration struct {
	Configuration tt.VideoSourceConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
}

type SetVideoSourceConfigurationResponse struct {
}

type SetVideoSourceMode struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	VideoSourceModeToken tt.ReferenceToken `xml:"VideoSourceModeToken"`
}

type SetVideoSourceModeResponse struct {
	Reboot bool `xml:"Reboot"`
}

type StartMulticastStreaming struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type StartMulticastStreamingResponse struct {
}

type StopMulticastStreaming struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type StopMulticastStreamingResponse struct {
}

