// Code generated by onvifgen; DO NOT EDIT.

package accessrules

import (
	"context"
	"net/http"

	"github.com/furrysalamander/onvif-go/onvif/soaphdr"
	"github.com/furrysalamander/onvif-go/onvif/schema/tar"
)

const actionBase = "http://www.onvif.org/ver10/accessrules/wsdl"

type Client struct {
	c *soaphdr.Client
}

func NewClient(endpoint, username, password string) *Client {
	return &Client{c: soaphdr.New(endpoint, username, password)}
}

func NewClientWithTransport(c *soaphdr.Client) *Client {
	return &Client{c: c}
}

func (c *Client) HTTP() *http.Client { return c.c.HTTP }
func (c *Client) SetHTTP(h *http.Client) { c.c.HTTP = h }

func (c *Client) CreateAccessProfile(ctx context.Context) (*tar.CreateAccessProfileResponse, error) {
	out := &tar.CreateAccessProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/CreateAccessProfile", &tar.CreateAccessProfile{}, out)
	return out, err
}

func (c *Client) DeleteAccessProfile(ctx context.Context) (*tar.DeleteAccessProfileResponse, error) {
	out := &tar.DeleteAccessProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/DeleteAccessProfile", &tar.DeleteAccessProfile{}, out)
	return out, err
}

func (c *Client) GetAccessProfileInfo(ctx context.Context) (*tar.GetAccessProfileInfoResponse, error) {
	out := &tar.GetAccessProfileInfoResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfileInfo", &tar.GetAccessProfileInfo{}, out)
	return out, err
}

func (c *Client) GetAccessProfileInfoList(ctx context.Context) (*tar.GetAccessProfileInfoListResponse, error) {
	out := &tar.GetAccessProfileInfoListResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfileInfoList", &tar.GetAccessProfileInfoList{}, out)
	return out, err
}

func (c *Client) GetAccessProfileList(ctx context.Context) (*tar.GetAccessProfileListResponse, error) {
	out := &tar.GetAccessProfileListResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfileList", &tar.GetAccessProfileList{}, out)
	return out, err
}

func (c *Client) GetAccessProfiles(ctx context.Context) (*tar.GetAccessProfilesResponse, error) {
	out := &tar.GetAccessProfilesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/GetAccessProfiles", &tar.GetAccessProfiles{}, out)
	return out, err
}

func (c *Client) GetServiceCapabilities(ctx context.Context) (*tar.GetServiceCapabilitiesResponse, error) {
	out := &tar.GetServiceCapabilitiesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/GetServiceCapabilities", &tar.GetServiceCapabilities{}, out)
	return out, err
}

func (c *Client) ModifyAccessProfile(ctx context.Context) (*tar.ModifyAccessProfileResponse, error) {
	out := &tar.ModifyAccessProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/ModifyAccessProfile", &tar.ModifyAccessProfile{}, out)
	return out, err
}

func (c *Client) SetAccessProfile(ctx context.Context) (*tar.SetAccessProfileResponse, error) {
	out := &tar.SetAccessProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/accessrules/wsdl/SetAccessProfile", &tar.SetAccessProfile{}, out)
	return out, err
}

