// Code generated by onvifgen; DO NOT EDIT.

package tmd

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type GetAudioOutputConfiguration struct {
	AudioOutputToken tt.ReferenceToken `xml:"AudioOutputToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioOutputConfigurationOptions struct {
	AudioOutputToken tt.ReferenceToken `xml:"AudioOutputToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioOutputConfigurationOptionsResponse struct {
	AudioOutputOptions tt.AudioOutputConfigurationOptions `xml:"AudioOutputOptions"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioOutputConfigurationResponse struct {
	AudioOutputConfiguration tt.AudioOutputConfiguration `xml:"AudioOutputConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioOutputs Get

type GetAudioOutputsResponse GetResponse

type GetAudioSourceConfiguration struct {
	AudioSourceToken tt.ReferenceToken `xml:"AudioSourceToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioSourceConfigurationOptions struct {
	AudioSourceToken tt.ReferenceToken `xml:"AudioSourceToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioSourceConfigurationOptionsResponse struct {
	AudioSourceOptions tt.AudioSourceConfigurationOptions `xml:"AudioSourceOptions"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioSourceConfigurationResponse struct {
	AudioSourceConfiguration tt.AudioSourceConfiguration `xml:"AudioSourceConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetAudioSources Get

type GetAudioSourcesResponse GetResponse

type GetDigitalInputConfigurationOptions struct {
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
}

type GetDigitalInputConfigurationOptionsResponse struct {
	DigitalInputOptions DigitalInputConfigurationOptions `xml:"DigitalInputOptions"`
}

// Get the available digital inputs of a device.
type GetDigitalInputs struct {
}

// Requested digital inputs.
type GetDigitalInputsResponse struct {
	DigitalInputs []tt.DigitalInput `xml:"DigitalInputs,omitempty"`
}

type GetRelayOutputOptions struct {
	RelayOutputToken *tt.ReferenceToken `xml:"RelayOutputToken,omitempty"`
}

type GetRelayOutputOptionsResponse struct {
	RelayOutputOptions []RelayOutputOptions `xml:"RelayOutputOptions,omitempty"`
}

// Gets the configuration that relates to serial port configuration.
type GetSerialPortConfiguration struct {
	SerialPortToken tt.ReferenceToken `xml:"SerialPortToken"`
}

// Gets the configuration options that relates to serial port configuration.
type GetSerialPortConfigurationOptions struct {
	SerialPortToken tt.ReferenceToken `xml:"SerialPortToken"`
}

// Requested serial port configuration options.
type GetSerialPortConfigurationOptionsResponse struct {
	SerialPortOptions SerialPortConfigurationOptions `xml:"SerialPortOptions"`
}

// Requested serial port configuration.
type GetSerialPortConfigurationResponse struct {
	SerialPortConfiguration SerialPortConfiguration `xml:"SerialPortConfiguration"`
}

// The physical serial port on the device that allows serial data to be read and written.
type GetSerialPorts struct {
}

// Requested serial ports.
type GetSerialPortsResponse struct {
	SerialPort []SerialPort `xml:"SerialPort,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type GetVideoOutputConfiguration struct {
	VideoOutputToken tt.ReferenceToken `xml:"VideoOutputToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoOutputConfigurationOptions struct {
	VideoOutputToken tt.ReferenceToken `xml:"VideoOutputToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoOutputConfigurationOptionsResponse struct {
	VideoOutputConfigurationOptions tt.VideoOutputConfigurationOptions `xml:"VideoOutputConfigurationOptions"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoOutputConfigurationResponse struct {
	VideoOutputConfiguration tt.VideoOutputConfiguration `xml:"VideoOutputConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoOutputs struct {
}

type GetVideoOutputsResponse struct {
	VideoOutputs []tt.VideoOutput `xml:"VideoOutputs,omitempty"`
}

type GetVideoSourceConfiguration struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoSourceConfigurationOptions struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoSourceConfigurationOptionsResponse struct {
	VideoSourceConfigurationOptions tt.VideoSourceConfigurationOptions `xml:"VideoSourceConfigurationOptions"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoSourceConfigurationResponse struct {
	VideoSourceConfiguration tt.VideoSourceConfiguration `xml:"VideoSourceConfiguration"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetVideoSources Get

type GetVideoSourcesResponse GetResponse

// Transmitting arbitrary data to the connected serial device and then receiving its response data.
type SendReceiveSerialCommand struct {
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
	SerialData *SerialData `xml:"SerialData,omitempty"`
	TimeOut **core.Duration `xml:"TimeOut,omitempty"`
	DataLength *int32 `xml:"DataLength,omitempty"`
	Delimiter *string `xml:"Delimiter,omitempty"`
}

// Receiving the response data.
type SendReceiveSerialCommandResponse struct {
	SerialData *SerialData `xml:"SerialData,omitempty"`
}

type SetAudioOutputConfiguration struct {
	Configuration tt.AudioOutputConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetAudioOutputConfigurationResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type SetAudioSourceConfiguration struct {
	Configuration tt.AudioSourceConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetAudioSourceConfigurationResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type SetDigitalInputConfigurations struct {
	DigitalInputs []tt.DigitalInput `xml:"DigitalInputs,omitempty"`
}

type SetDigitalInputConfigurationsResponse struct {
}

type SetRelayOutputSettings struct {
	RelayOutput tt.RelayOutput `xml:"RelayOutput"`
}

type SetRelayOutputSettingsResponse struct {
}

// Sets the configuration that relates to serial port configuration.
type SetSerialPortConfiguration struct {
	SerialPortConfiguration SerialPortConfiguration `xml:"SerialPortConfiguration"`
	ForcePersistance bool `xml:"ForcePersistance"`
}

type SetSerialPortConfigurationResponse struct {
}

type SetVideoOutputConfiguration struct {
	Configuration tt.VideoOutputConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetVideoOutputConfigurationResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type SetVideoSourceConfiguration struct {
	Configuration tt.VideoSourceConfiguration `xml:"Configuration"`
	ForcePersistence bool `xml:"ForcePersistence"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SetVideoSourceConfigurationResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

