// Code generated by onvifgen; DO NOT EDIT.

package tac

// The Decision enumeration represents a choice of two available options for an access request:
type Decision string

const (
	DecisionGranted Decision = "Granted"
	DecisionDenied Decision = "Denied"
)

// Non-normative enum that describes the various reasons for denying access.
// The following strings shall be used for the reason field:
type DenyReason string

const (
	DenyReasonCredentialNotEnabled DenyReason = "CredentialNotEnabled"
	DenyReasonCredentialNotActive DenyReason = "CredentialNotActive"
	DenyReasonCredentialExpired DenyReason = "CredentialExpired"
	DenyReasonInvalidPIN DenyReason = "InvalidPIN"
	DenyReasonNotPermittedAtThisTime DenyReason = "NotPermittedAtThisTime"
	DenyReasonUnauthorized DenyReason = "Unauthorized"
	DenyReasonOther DenyReason = "Other"
)

// Non-normative enumeration that describes the ONVIF defined feedback types.
// These types are used in string fields where extendibility is desired.
// Strings starting with the prefix pt: are reserved to define ONVIF-specific types.
// For custom defined feedback types, free text can be used.
// The following types are defined by ONVIF:
type FeedbackType string

const (
	FeedbackTypePt_Disabled FeedbackType = "pt:Disabled"
	FeedbackTypePt_Idle FeedbackType = "pt:Idle"
	FeedbackTypePt_DoorLocked FeedbackType = "pt:DoorLocked"
	FeedbackTypePt_DoorUnlocked FeedbackType = "pt:DoorUnlocked"
	FeedbackTypePt_DoorOpenTooLong FeedbackType = "pt:DoorOpenTooLong"
	FeedbackTypePt_DoorPreAlarmWarning FeedbackType = "pt:DoorPreAlarmWarning"
	FeedbackTypePt_RequireIdentifier FeedbackType = "pt:RequireIdentifier"
	FeedbackTypePt_TextMessage FeedbackType = "pt:TextMessage"
	FeedbackTypePt_Processing FeedbackType = "pt:Processing"
	FeedbackTypePt_RetryIdentifier FeedbackType = "pt:RetryIdentifier"
	FeedbackTypePt_AccessGranted FeedbackType = "pt:AccessGranted"
	FeedbackTypePt_AccessDenied FeedbackType = "pt:AccessDenied"
	FeedbackTypePt_Ok FeedbackType = "pt:Ok"
	FeedbackTypePt_Fault FeedbackType = "pt:Fault"
	FeedbackTypePt_Warning FeedbackType = "pt:Warning"
	FeedbackTypePt_Alarm FeedbackType = "pt:Alarm"
)

