// Code generated by onvifgen; DO NOT EDIT.

package tr2

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type AudioClip struct {
	Enabled bool `xml:"Enabled"`
	Name string `xml:"Name"`
	AudioOutputToken []tt.ReferenceToken `xml:"AudioOutputToken,omitempty"`
	Type string `xml:"Type"`
	RepeatCycles int32 `xml:"RepeatCycles"`
	RepeatInterval *int32 `xml:"RepeatInterval,omitempty"`
	AudioOutputLevel *int32 `xml:"AudioOutputLevel,omitempty"`
	ScheduleToken *tt.ReferenceToken `xml:"ScheduleToken,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type AudioClipCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MaxAudioClipLimit int32 `xml:"MaxAudioClipLimit,omitempty,attr"`
	MaxAudioClipSize float32 `xml:"MaxAudioClipSize,omitempty,attr"`
	SupportedAudioClipFormat tt.StringAttrList `xml:"SupportedAudioClipFormat,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Capabilities2 struct {
	ProfileCapabilities ProfileCapabilities `xml:"ProfileCapabilities"`
	StreamingCapabilities StreamingCapabilities `xml:"StreamingCapabilities"`
	MediaSigningCapabilities *MediaSigningCapabilities `xml:"MediaSigningCapabilities,omitempty"`
	AudioClipCapabilities *AudioClipCapabilities `xml:"AudioClipCapabilities,omitempty"`
	MulticastAudioDecoderCapabilities *MulticastAudioDecoderCapabilities `xml:"MulticastAudioDecoderCapabilities,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	SnapshotUri bool `xml:"SnapshotUri,omitempty,attr"`
	Rotation bool `xml:"Rotation,omitempty,attr"`
	VideoSourceMode bool `xml:"VideoSourceMode,omitempty,attr"`
	OSD bool `xml:"OSD,omitempty,attr"`
	TemporaryOSDText bool `xml:"TemporaryOSDText,omitempty,attr"`
	Mask bool `xml:"Mask,omitempty,attr"`
	SourceMask bool `xml:"SourceMask,omitempty,attr"`
	WebRTC int32 `xml:"WebRTC,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type ConfigurationRef struct {
	Type string `xml:"Type"`
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
}

// A set of media configurations.
type ConfigurationSet struct {
	VideoSource *tt.VideoSourceConfiguration `xml:"VideoSource,omitempty"`
	AudioSource *tt.AudioSourceConfiguration `xml:"AudioSource,omitempty"`
	VideoEncoder *tt.VideoEncoder2Configuration `xml:"VideoEncoder,omitempty"`
	AudioEncoder *tt.AudioEncoder2Configuration `xml:"AudioEncoder,omitempty"`
	Analytics *tt.VideoAnalyticsConfiguration `xml:"Analytics,omitempty"`
	PTZ *tt.PTZConfiguration `xml:"PTZ,omitempty"`
	Metadata *tt.MetadataConfiguration `xml:"Metadata,omitempty"`
	AudioOutput *tt.AudioOutputConfiguration `xml:"AudioOutput,omitempty"`
	AudioDecoder *tt.AudioDecoderConfiguration `xml:"AudioDecoder,omitempty"`
	Receiver *ReceiverConfiguration `xml:"Receiver,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type EncoderInstance struct {
	Encoding string `xml:"Encoding"`
	Number int32 `xml:"Number"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type EncoderInstanceInfo struct {
	Codec []EncoderInstance `xml:"Codec,omitempty"`
	Total int32 `xml:"Total"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type GetAudioClipsResponseItem struct {
	Token tt.ReferenceToken `xml:"Token"`
	Configuration AudioClip `xml:"Configuration"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type GetConfiguration struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
	ProfileToken *tt.ReferenceToken `xml:"ProfileToken,omitempty"`
}

type Mask struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	Polygon tt.Polygon `xml:"Polygon"`
	Type string `xml:"Type"`
	Color *tt.Color `xml:"Color,omitempty"`
	Enabled bool `xml:"Enabled"`
	Any core.Extension `xml:"Any,omitempty"`
	Xtoken tt.ReferenceToken `xml:"token,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type MaskOptions struct {
	MaxMasks int32 `xml:"MaxMasks"`
	MaxPoints int32 `xml:"MaxPoints"`
	Types []string `xml:"Types,omitempty"`
	Color tt.ColorOptions `xml:"Color"`
	Any core.Extension `xml:"Any,omitempty"`
	RectangleOnly bool `xml:"RectangleOnly,omitempty,attr"`
	SingleColorOnly bool `xml:"SingleColorOnly,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

// A media profile consists of a set of media configurations.
type MediaProfile struct {
	Name tt.Name `xml:"Name"`
	Configurations *ConfigurationSet `xml:"Configurations,omitempty"`
	Xtoken tt.ReferenceToken `xml:"token,attr"`
	Xfixed bool `xml:"fixed,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type MediaSigningCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MediaSigningSupported bool `xml:"MediaSigningSupported,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type MulticastAudioDecoderCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MulticastAudioDecoder bool `xml:"MulticastAudioDecoder,omitempty,attr"`
	SRTP bool `xml:"SRTP,omitempty,attr"`
	IPv6 bool `xml:"IPv6,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type PlayingAudioClips struct {
	Token tt.ReferenceToken `xml:"Token"`
	Name string `xml:"Name"`
	AudioOutputToken []tt.ReferenceToken `xml:"AudioOutputToken,omitempty"`
	AudioOutputLevel int32 `xml:"AudioOutputLevel"`
	RepeatsLeft int32 `xml:"RepeatsLeft"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type ProfileCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	MaximumNumberOfProfiles int32 `xml:"MaximumNumberOfProfiles,omitempty,attr"`
	ConfigurationsSupported tt.StringAttrList `xml:"ConfigurationsSupported,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type ReceiverConfiguration struct {
	Base3 tt.ReceiverConfiguration `xml:",omitempty"`
	Xtoken tt.ReferenceToken `xml:"token,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type SetConfigurationResponse struct {
}

type StartStopMulticastStreaming struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type StreamingCapabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	RTSPStreaming bool `xml:"RTSPStreaming,omitempty,attr"`
	RTPMulticast bool `xml:"RTPMulticast,omitempty,attr"`
	RTP_RTSP_TCP bool `xml:"RTP_RTSP_TCP,omitempty,attr"`
	NonAggregateControl bool `xml:"NonAggregateControl,omitempty,attr"`
	RTSPWebSocketUri string `xml:"RTSPWebSocketUri,omitempty,attr"`
	AutoStartMulticast bool `xml:"AutoStartMulticast,omitempty,attr"`
	SecureRTSPStreaming bool `xml:"SecureRTSPStreaming,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type VideoSourceMode struct {
	MaxFramerate float32 `xml:"MaxFramerate"`
	MaxResolution tt.VideoResolution `xml:"MaxResolution"`
	Encodings tt.StringList `xml:"Encodings"`
	Reboot bool `xml:"Reboot"`
	Description *tt.Description `xml:"Description,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	Xtoken tt.ReferenceToken `xml:"token,attr"`
	Enabled bool `xml:"Enabled,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type WebRTCConfiguration struct {
	SignalingServer string `xml:"SignalingServer"`
	CertPathValidationPolicyID *string `xml:"CertPathValidationPolicyID,omitempty"`
	AuthorizationServer tt.ReferenceToken `xml:"AuthorizationServer"`
	DefaultProfile tt.ReferenceToken `xml:"DefaultProfile"`
	Enabled bool `xml:"Enabled"`
	Connected *bool `xml:"Connected,omitempty"`
	Error *string `xml:"Error,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

