// Code generated by onvifgen; DO NOT EDIT.

package xmlmime

type Xbase64Binary struct {
	Value []byte `xml:",chardata"`
	string `xml:",omitempty,attr"`
}

type XhexBinary struct {
	Value []byte `xml:",chardata"`
	string `xml:",omitempty,attr"`
}

