// Code generated by onvifgen; DO NOT EDIT.

// Package tas contains ONVIF-generated types for the
// http://www.onvif.org/ver10/advancedsecurity/wsdl namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package tas

const NS = "http://www.onvif.org/ver10/advancedsecurity/wsdl"
