// Code generated by onvifgen; DO NOT EDIT.

// Package pacs contains ONVIF-generated types for the
// http://www.onvif.org/ver10/pacs namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package pacs

const NS = "http://www.onvif.org/ver10/pacs"
