// Code generated by onvifgen; DO NOT EDIT.

package pacs

// Description is optional and the maximum length is device specific.
// If the length is more than maximum length, it is silently chopped to the maximum length
// supported by the device/service (which may be 0).
type Description string

// Type used for names of logical and physical entities.
type Name string

// Type used to represent the numbers from 1 ,2 , 3,...
type PositiveInteger int64

// Recognition/identification types supported by ONVIF.
type RecognitionType string

const (
	RecognitionTypePt_Card RecognitionType = "pt:Card"
	RecognitionTypePt_PIN RecognitionType = "pt:PIN"
	RecognitionTypePt_Fingerprint RecognitionType = "pt:Fingerprint"
	RecognitionTypePt_Face RecognitionType = "pt:Face"
	RecognitionTypePt_Iris RecognitionType = "pt:Iris"
	RecognitionTypePt_Vein RecognitionType = "pt:Vein"
	RecognitionTypePt_Palm RecognitionType = "pt:Palm"
	RecognitionTypePt_Retina RecognitionType = "pt:Retina"
	RecognitionTypePt_LicensePlate RecognitionType = "pt:LicensePlate"
	RecognitionTypePt_REX RecognitionType = "pt:REX"
)

// Type used to reference logical and physical entities.
// Token may be extended by intermediate terminal with adding prefix to make it global unique.
// The length should be within 36 characters for generating as a local token.
// See "Remote Token" section in Resource Query specification.
type ReferenceToken string

type StringList []string

