// Code generated by onvifgen; DO NOT EDIT.

package trp

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type GetReplayConfiguration struct {
}

type GetReplayConfigurationResponse struct {
	Configuration tt.ReplayConfiguration `xml:"Configuration"`
}

type GetReplayUri struct {
	StreamSetup tt.StreamSetup `xml:"StreamSetup"`
	RecordingToken tt.ReferenceToken `xml:"RecordingToken"`
}

type GetReplayUriResponse struct {
	Uri string `xml:"Uri"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type SetReplayConfiguration struct {
	Configuration tt.ReplayConfiguration `xml:"Configuration"`
}

type SetReplayConfigurationResponse struct {
}

