// Code generated by onvifgen; DO NOT EDIT.

// Package fc contains ONVIF-generated types for the
// http://www.onvif.org/ver20/analytics/humanface namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package fc

const NS = "http://www.onvif.org/ver20/analytics/humanface"
