// Code generated by onvifgen; DO NOT EDIT.

package tds

import (
	"encoding/xml"

	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type DeviceServiceCapabilities struct {
	Network NetworkCapabilities `xml:"Network"`
	Security SecurityCapabilities `xml:"Security"`
	System SystemCapabilities `xml:"System"`
	Misc *MiscCapabilities `xml:"Misc,omitempty"`
}

type MiscCapabilities struct {
	AuxiliaryCommands tt.StringAttrList `xml:"AuxiliaryCommands,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type NetworkCapabilities struct {
	IPFilter bool `xml:"IPFilter,omitempty,attr"`
	ZeroConfiguration bool `xml:"ZeroConfiguration,omitempty,attr"`
	IPVersion6 bool `xml:"IPVersion6,omitempty,attr"`
	DynDNS bool `xml:"DynDNS,omitempty,attr"`
	Dot11Configuration bool `xml:"Dot11Configuration,omitempty,attr"`
	Dot1XConfigurations int32 `xml:"Dot1XConfigurations,omitempty,attr"`
	HostnameFromDHCP bool `xml:"HostnameFromDHCP,omitempty,attr"`
	NTP int32 `xml:"NTP,omitempty,attr"`
	DHCPv6 bool `xml:"DHCPv6,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type SecurityCapabilities struct {
	TLS10 bool `xml:"TLS1.0,omitempty,attr"`
	TLS11 bool `xml:"TLS1.1,omitempty,attr"`
	TLS12 bool `xml:"TLS1.2,omitempty,attr"`
	OnboardKeyGeneration bool `xml:"OnboardKeyGeneration,omitempty,attr"`
	AccessPolicyConfig bool `xml:"AccessPolicyConfig,omitempty,attr"`
	DefaultAccessPolicy bool `xml:"DefaultAccessPolicy,omitempty,attr"`
	Dot1X bool `xml:"Dot1X,omitempty,attr"`
	RemoteUserHandling bool `xml:"RemoteUserHandling,omitempty,attr"`
	X509Token bool `xml:"X.509Token,omitempty,attr"`
	SAMLToken bool `xml:"SAMLToken,omitempty,attr"`
	KerberosToken bool `xml:"KerberosToken,omitempty,attr"`
	UsernameToken bool `xml:"UsernameToken,omitempty,attr"`
	HttpDigest bool `xml:"HttpDigest,omitempty,attr"`
	RELToken bool `xml:"RELToken,omitempty,attr"`
	JsonWebToken bool `xml:"JsonWebToken,omitempty,attr"`
	SupportedEAPMethods tt.IntList `xml:"SupportedEAPMethods,omitempty,attr"`
	MaxUsers int32 `xml:"MaxUsers,omitempty,attr"`
	MaxUserNameLength int32 `xml:"MaxUserNameLength,omitempty,attr"`
	MaxPasswordLength int32 `xml:"MaxPasswordLength,omitempty,attr"`
	SecurityPolicies tt.StringList `xml:"SecurityPolicies,omitempty,attr"`
	MaxPasswordHistory int32 `xml:"MaxPasswordHistory,omitempty,attr"`
	HashingAlgorithms tt.StringList `xml:"HashingAlgorithms,omitempty,attr"`
	MaxUserRoles int32 `xml:"MaxUserRoles,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Service struct {
	Namespace string `xml:"Namespace"`
	XAddr string `xml:"XAddr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type StorageConfiguration struct {
	tt.DeviceEntity `xml:",omitempty"`
	Data StorageConfigurationData `xml:"Data"`
}

type StorageConfigurationData struct {
	LocalPath *string `xml:"LocalPath,omitempty"`
	StorageUri *string `xml:"StorageUri,omitempty"`
	User *UserCredential `xml:"User,omitempty"`
	Xtype string `xml:"type,attr"`
	Region string `xml:"Region,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type SystemCapabilities struct {
	DiscoveryResolve bool `xml:"DiscoveryResolve,omitempty,attr"`
	DiscoveryBye bool `xml:"DiscoveryBye,omitempty,attr"`
	RemoteDiscovery bool `xml:"RemoteDiscovery,omitempty,attr"`
	SystemBackup bool `xml:"SystemBackup,omitempty,attr"`
	SystemLogging bool `xml:"SystemLogging,omitempty,attr"`
	FirmwareUpgrade bool `xml:"FirmwareUpgrade,omitempty,attr"`
	CloudFirmwareUpgrade bool `xml:"CloudFirmwareUpgrade,omitempty,attr"`
	HttpFirmwareUpgrade bool `xml:"HttpFirmwareUpgrade,omitempty,attr"`
	HttpSystemBackup bool `xml:"HttpSystemBackup,omitempty,attr"`
	HttpSystemLogging bool `xml:"HttpSystemLogging,omitempty,attr"`
	HttpSupportInformation bool `xml:"HttpSupportInformation,omitempty,attr"`
	StorageConfiguration bool `xml:"StorageConfiguration,omitempty,attr"`
	MaxStorageConfigurations int32 `xml:"MaxStorageConfigurations,omitempty,attr"`
	StorageConfigurationRenewal bool `xml:"StorageConfigurationRenewal,omitempty,attr"`
	GeoLocationEntries int32 `xml:"GeoLocationEntries,omitempty,attr"`
	AutoGeo tt.StringAttrList `xml:"AutoGeo,omitempty,attr"`
	StorageTypesSupported tt.StringAttrList `xml:"StorageTypesSupported,omitempty,attr"`
	DiscoveryNotSupported bool `xml:"DiscoveryNotSupported,omitempty,attr"`
	NetworkConfigNotSupported bool `xml:"NetworkConfigNotSupported,omitempty,attr"`
	UserConfigNotSupported bool `xml:"UserConfigNotSupported,omitempty,attr"`
	Addons tt.StringAttrList `xml:"Addons,omitempty,attr"`
	HardwareType string `xml:"HardwareType,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type UserCredential struct {
	UserName string `xml:"UserName"`
	Password *string `xml:"Password,omitempty"`
}

