// Code generated by onvifgen; DO NOT EDIT.

package credential

import (
	"context"
	"net/http"

	"github.com/furrysalamander/onvif-go/onvif/soaphdr"
	"github.com/furrysalamander/onvif-go/onvif/schema/tcr"
)

const actionBase = "http://www.onvif.org/ver10/credential/wsdl"

type Client struct {
	c *soaphdr.Client
}

func NewClient(endpoint, username, password string) *Client {
	return &Client{c: soaphdr.New(endpoint, username, password)}
}

func NewClientWithTransport(c *soaphdr.Client) *Client {
	return &Client{c: c}
}

func (c *Client) HTTP() *http.Client { return c.c.HTTP }
func (c *Client) SetHTTP(h *http.Client) { c.c.HTTP = h }

func (c *Client) AddToBlacklist(ctx context.Context) (*tcr.AddToBlacklistResponse, error) {
	out := &tcr.AddToBlacklistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/AddToBlacklist", &tcr.AddToBlacklist{}, out)
	return out, err
}

func (c *Client) AddToWhitelist(ctx context.Context) (*tcr.AddToWhitelistResponse, error) {
	out := &tcr.AddToWhitelistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/AddToWhitelist", &tcr.AddToWhitelist{}, out)
	return out, err
}

func (c *Client) CreateCredential(ctx context.Context) (*tcr.CreateCredentialResponse, error) {
	out := &tcr.CreateCredentialResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/CreateCredential", &tcr.CreateCredential{}, out)
	return out, err
}

func (c *Client) DeleteBlacklist(ctx context.Context) (*tcr.DeleteBlacklistResponse, error) {
	out := &tcr.DeleteBlacklistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/DeleteBlacklist", &tcr.DeleteBlacklist{}, out)
	return out, err
}

func (c *Client) DeleteCredential(ctx context.Context) (*tcr.DeleteCredentialResponse, error) {
	out := &tcr.DeleteCredentialResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/DeleteCredential", &tcr.DeleteCredential{}, out)
	return out, err
}

func (c *Client) DeleteCredentialAccessProfiles(ctx context.Context) (*tcr.DeleteCredentialAccessProfilesResponse, error) {
	out := &tcr.DeleteCredentialAccessProfilesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialAccessProfiles", &tcr.DeleteCredentialAccessProfiles{}, out)
	return out, err
}

func (c *Client) DeleteCredentialIdentifier(ctx context.Context) (*tcr.DeleteCredentialIdentifierResponse, error) {
	out := &tcr.DeleteCredentialIdentifierResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialIdentifier", &tcr.DeleteCredentialIdentifier{}, out)
	return out, err
}

func (c *Client) DeleteWhitelist(ctx context.Context) (*tcr.DeleteWhitelistResponse, error) {
	out := &tcr.DeleteWhitelistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/DeleteWhitelist", &tcr.DeleteWhitelist{}, out)
	return out, err
}

func (c *Client) DisableCredential(ctx context.Context) (*tcr.DisableCredentialResponse, error) {
	out := &tcr.DisableCredentialResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/DisableCredential", &tcr.DisableCredential{}, out)
	return out, err
}

func (c *Client) EnableCredential(ctx context.Context) (*tcr.EnableCredentialResponse, error) {
	out := &tcr.EnableCredentialResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/EnableCredential", &tcr.EnableCredential{}, out)
	return out, err
}

func (c *Client) GetBlacklist(ctx context.Context) (*tcr.GetBlacklistResponse, error) {
	out := &tcr.GetBlacklistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetBlacklist", &tcr.GetBlacklist{}, out)
	return out, err
}

func (c *Client) GetCredentialAccessProfiles(ctx context.Context) (*tcr.GetCredentialAccessProfilesResponse, error) {
	out := &tcr.GetCredentialAccessProfilesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentialAccessProfiles", &tcr.GetCredentialAccessProfiles{}, out)
	return out, err
}

func (c *Client) GetCredentialIdentifiers(ctx context.Context) (*tcr.GetCredentialIdentifiersResponse, error) {
	out := &tcr.GetCredentialIdentifiersResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentialIdentifiers", &tcr.GetCredentialIdentifiers{}, out)
	return out, err
}

func (c *Client) GetCredentialInfo(ctx context.Context) (*tcr.GetCredentialInfoResponse, error) {
	out := &tcr.GetCredentialInfoResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfo", &tcr.GetCredentialInfo{}, out)
	return out, err
}

func (c *Client) GetCredentialInfoList(ctx context.Context) (*tcr.GetCredentialInfoListResponse, error) {
	out := &tcr.GetCredentialInfoListResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfoList", &tcr.GetCredentialInfoList{}, out)
	return out, err
}

func (c *Client) GetCredentialList(ctx context.Context) (*tcr.GetCredentialListResponse, error) {
	out := &tcr.GetCredentialListResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentialList", &tcr.GetCredentialList{}, out)
	return out, err
}

func (c *Client) GetCredentialState(ctx context.Context) (*tcr.GetCredentialStateResponse, error) {
	out := &tcr.GetCredentialStateResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentialState", &tcr.GetCredentialState{}, out)
	return out, err
}

func (c *Client) GetCredentials(ctx context.Context) (*tcr.GetCredentialsResponse, error) {
	out := &tcr.GetCredentialsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetCredentials", &tcr.GetCredentials{}, out)
	return out, err
}

func (c *Client) GetServiceCapabilities(ctx context.Context) (*tcr.GetServiceCapabilitiesResponse, error) {
	out := &tcr.GetServiceCapabilitiesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetServiceCapabilities", &tcr.GetServiceCapabilities{}, out)
	return out, err
}

func (c *Client) GetSupportedFormatTypes(ctx context.Context) (*tcr.GetSupportedFormatTypesResponse, error) {
	out := &tcr.GetSupportedFormatTypesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetSupportedFormatTypes", &tcr.GetSupportedFormatTypes{}, out)
	return out, err
}

func (c *Client) GetWhitelist(ctx context.Context) (*tcr.GetWhitelistResponse, error) {
	out := &tcr.GetWhitelistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/GetWhitelist", &tcr.GetWhitelist{}, out)
	return out, err
}

func (c *Client) ModifyCredential(ctx context.Context) (*tcr.ModifyCredentialResponse, error) {
	out := &tcr.ModifyCredentialResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/ModifyCredential", &tcr.ModifyCredential{}, out)
	return out, err
}

func (c *Client) RemoveFromBlacklist(ctx context.Context) (*tcr.RemoveFromBlacklistResponse, error) {
	out := &tcr.RemoveFromBlacklistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/RemoveFromBlacklist", &tcr.RemoveFromBlacklist{}, out)
	return out, err
}

func (c *Client) RemoveFromWhitelist(ctx context.Context) (*tcr.RemoveFromWhitelistResponse, error) {
	out := &tcr.RemoveFromWhitelistResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/RemoveFromWhitelist", &tcr.RemoveFromWhitelist{}, out)
	return out, err
}

func (c *Client) ResetAntipassbackViolation(ctx context.Context) (*tcr.ResetAntipassbackViolationResponse, error) {
	out := &tcr.ResetAntipassbackViolationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/ResetAntipassbackViolation", &tcr.ResetAntipassbackViolation{}, out)
	return out, err
}

func (c *Client) SetCredential(ctx context.Context) (*tcr.SetCredentialResponse, error) {
	out := &tcr.SetCredentialResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/SetCredential", &tcr.SetCredential{}, out)
	return out, err
}

func (c *Client) SetCredentialAccessProfiles(ctx context.Context) (*tcr.SetCredentialAccessProfilesResponse, error) {
	out := &tcr.SetCredentialAccessProfilesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/SetCredentialAccessProfiles", &tcr.SetCredentialAccessProfiles{}, out)
	return out, err
}

func (c *Client) SetCredentialIdentifier(ctx context.Context) (*tcr.SetCredentialIdentifierResponse, error) {
	out := &tcr.SetCredentialIdentifierResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/credential/wsdl/SetCredentialIdentifier", &tcr.SetCredentialIdentifier{}, out)
	return out, err
}

