// Code generated by onvifgen; DO NOT EDIT.

package imaging

import (
	"context"
	"net/http"

	"github.com/furrysalamander/onvif-go/onvif/soaphdr"
	"github.com/furrysalamander/onvif-go/onvif/schema/timg"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

const actionBase = "http://www.onvif.org/ver20/imaging/wsdl"

type Client struct {
	c *soaphdr.Client
}

func NewClient(endpoint, username, password string) *Client {
	return &Client{c: soaphdr.New(endpoint, username, password)}
}

func NewClientWithTransport(c *soaphdr.Client) *Client {
	return &Client{c: c}
}

func (c *Client) HTTP() *http.Client { return c.c.HTTP }
func (c *Client) SetHTTP(h *http.Client) { c.c.HTTP = h }

func (c *Client) GetCurrentPreset(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.GetCurrentPresetResponse, error) {
	req := &timg.GetCurrentPreset{VideoSourceToken: videoSourceToken}
	out := &timg.GetCurrentPresetResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetCurrentPreset", req, out)
	return out, err
}

func (c *Client) GetImagingSettings(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.GetImagingSettingsResponse, error) {
	req := &timg.GetImagingSettings{VideoSourceToken: videoSourceToken}
	out := &timg.GetImagingSettingsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetImagingSettings", req, out)
	return out, err
}

func (c *Client) GetMoveOptions(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.GetMoveOptionsResponse, error) {
	req := &timg.GetMoveOptions{VideoSourceToken: videoSourceToken}
	out := &timg.GetMoveOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetMoveOptions", req, out)
	return out, err
}

func (c *Client) GetOptions(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.GetOptionsResponse, error) {
	req := &timg.GetOptions{VideoSourceToken: videoSourceToken}
	out := &timg.GetOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetOptions", req, out)
	return out, err
}

func (c *Client) GetPresets(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.GetPresetsResponse, error) {
	req := &timg.GetPresets{VideoSourceToken: videoSourceToken}
	out := &timg.GetPresetsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetPresets", req, out)
	return out, err
}

func (c *Client) GetServiceCapabilities(ctx context.Context) (*timg.GetServiceCapabilitiesResponse, error) {
	req := &timg.GetServiceCapabilities{}
	out := &timg.GetServiceCapabilitiesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetServiceCapabilities", req, out)
	return out, err
}

func (c *Client) GetStatus(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.GetStatusResponse, error) {
	req := &timg.GetStatus{VideoSourceToken: videoSourceToken}
	out := &timg.GetStatusResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/GetStatus", req, out)
	return out, err
}

func (c *Client) Move(ctx context.Context, videoSourceToken tt.ReferenceToken, focus tt.FocusMove) (*timg.MoveResponse, error) {
	req := &timg.Move{VideoSourceToken: videoSourceToken, Focus: focus}
	out := &timg.MoveResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/Move", req, out)
	return out, err
}

func (c *Client) SetCurrentPreset(ctx context.Context, videoSourceToken tt.ReferenceToken, presetToken tt.ReferenceToken) (*timg.SetCurrentPresetResponse, error) {
	req := &timg.SetCurrentPreset{VideoSourceToken: videoSourceToken, PresetToken: presetToken}
	out := &timg.SetCurrentPresetResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/SetCurrentPreset", req, out)
	return out, err
}

func (c *Client) SetImagingSettings(ctx context.Context, videoSourceToken tt.ReferenceToken, imagingSettings tt.ImagingSettings20, forcePersistence *bool) (*timg.SetImagingSettingsResponse, error) {
	req := &timg.SetImagingSettings{VideoSourceToken: videoSourceToken, ImagingSettings: imagingSettings, ForcePersistence: forcePersistence}
	out := &timg.SetImagingSettingsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/SetImagingSettings", req, out)
	return out, err
}

func (c *Client) Stop(ctx context.Context, videoSourceToken tt.ReferenceToken) (*timg.StopResponse, error) {
	req := &timg.Stop{VideoSourceToken: videoSourceToken}
	out := &timg.StopResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver20/imaging/wsdl/FocusStop", req, out)
	return out, err
}

