// Code generated by onvifgen; DO NOT EDIT.

package wsrf

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/wsrfbf"
)

type ResourceUnavailableFaultType struct {
	Base48 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type ResourceUnknownFaultType struct {
	Base49 wsrfbf.BaseFaultType `xml:",omitempty"`
}

