// Code generated by onvifgen; DO NOT EDIT.

package media

import (
	"context"
	"net/http"

	"github.com/furrysalamander/onvif-go/onvif/soaphdr"
	"github.com/furrysalamander/onvif-go/onvif/schema/trt"
)

const actionBase = "http://www.onvif.org/ver10/media/wsdl"

type Client struct {
	c *soaphdr.Client
}

func NewClient(endpoint, username, password string) *Client {
	return &Client{c: soaphdr.New(endpoint, username, password)}
}

func NewClientWithTransport(c *soaphdr.Client) *Client {
	return &Client{c: c}
}

func (c *Client) HTTP() *http.Client { return c.c.HTTP }
func (c *Client) SetHTTP(h *http.Client) { c.c.HTTP = h }

func (c *Client) AddAudioDecoderConfiguration(ctx context.Context) (*trt.AddAudioDecoderConfigurationResponse, error) {
	out := &trt.AddAudioDecoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddAudioDecoderConfiguration", &trt.AddAudioDecoderConfiguration{}, out)
	return out, err
}

func (c *Client) AddAudioEncoderConfiguration(ctx context.Context) (*trt.AddAudioEncoderConfigurationResponse, error) {
	out := &trt.AddAudioEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddAudioEncoderConfiguration", &trt.AddAudioEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) AddAudioOutputConfiguration(ctx context.Context) (*trt.AddAudioOutputConfigurationResponse, error) {
	out := &trt.AddAudioOutputConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddAudioOutputConfiguration", &trt.AddAudioOutputConfiguration{}, out)
	return out, err
}

func (c *Client) AddAudioSourceConfiguration(ctx context.Context) (*trt.AddAudioSourceConfigurationResponse, error) {
	out := &trt.AddAudioSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddAudioSourceConfiguration", &trt.AddAudioSourceConfiguration{}, out)
	return out, err
}

func (c *Client) AddMetadataConfiguration(ctx context.Context) (*trt.AddMetadataConfigurationResponse, error) {
	out := &trt.AddMetadataConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddMetadataConfiguration", &trt.AddMetadataConfiguration{}, out)
	return out, err
}

func (c *Client) AddPTZConfiguration(ctx context.Context) (*trt.AddPTZConfigurationResponse, error) {
	out := &trt.AddPTZConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddPTZConfiguration", &trt.AddPTZConfiguration{}, out)
	return out, err
}

func (c *Client) AddVideoAnalyticsConfiguration(ctx context.Context) (*trt.AddVideoAnalyticsConfigurationResponse, error) {
	out := &trt.AddVideoAnalyticsConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddVideoAnalyticsConfiguration", &trt.AddVideoAnalyticsConfiguration{}, out)
	return out, err
}

func (c *Client) AddVideoEncoderConfiguration(ctx context.Context) (*trt.AddVideoEncoderConfigurationResponse, error) {
	out := &trt.AddVideoEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddVideoEncoderConfiguration", &trt.AddVideoEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) AddVideoSourceConfiguration(ctx context.Context) (*trt.AddVideoSourceConfigurationResponse, error) {
	out := &trt.AddVideoSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/AddVideoSourceConfiguration", &trt.AddVideoSourceConfiguration{}, out)
	return out, err
}

func (c *Client) CreateOSD(ctx context.Context) (*trt.CreateOSDResponse, error) {
	out := &trt.CreateOSDResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/CreateOSD", &trt.CreateOSD{}, out)
	return out, err
}

func (c *Client) CreateProfile(ctx context.Context) (*trt.CreateProfileResponse, error) {
	out := &trt.CreateProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/CreateProfile", &trt.CreateProfile{}, out)
	return out, err
}

func (c *Client) DeleteOSD(ctx context.Context) (*trt.DeleteOSDResponse, error) {
	out := &trt.DeleteOSDResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/DeleteOSD", &trt.DeleteOSD{}, out)
	return out, err
}

func (c *Client) DeleteProfile(ctx context.Context) (*trt.DeleteProfileResponse, error) {
	out := &trt.DeleteProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/DeleteProfile", &trt.DeleteProfile{}, out)
	return out, err
}

func (c *Client) GetAudioDecoderConfiguration(ctx context.Context) (*trt.GetAudioDecoderConfigurationResponse, error) {
	out := &trt.GetAudioDecoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfiguration", &trt.GetAudioDecoderConfiguration{}, out)
	return out, err
}

func (c *Client) GetAudioDecoderConfigurationOptions(ctx context.Context) (*trt.GetAudioDecoderConfigurationOptionsResponse, error) {
	out := &trt.GetAudioDecoderConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfigurationOptions", &trt.GetAudioDecoderConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetAudioDecoderConfigurations(ctx context.Context) (*trt.GetAudioDecoderConfigurationsResponse, error) {
	out := &trt.GetAudioDecoderConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfigurations", &trt.GetAudioDecoderConfigurations{}, out)
	return out, err
}

func (c *Client) GetAudioEncoderConfiguration(ctx context.Context) (*trt.GetAudioEncoderConfigurationResponse, error) {
	out := &trt.GetAudioEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfiguration", &trt.GetAudioEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) GetAudioEncoderConfigurationOptions(ctx context.Context) (*trt.GetAudioEncoderConfigurationOptionsResponse, error) {
	out := &trt.GetAudioEncoderConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfigurationOptions", &trt.GetAudioEncoderConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetAudioEncoderConfigurations(ctx context.Context) (*trt.GetAudioEncoderConfigurationsResponse, error) {
	out := &trt.GetAudioEncoderConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfigurations", &trt.GetAudioEncoderConfigurations{}, out)
	return out, err
}

func (c *Client) GetAudioOutputConfiguration(ctx context.Context) (*trt.GetAudioOutputConfigurationResponse, error) {
	out := &trt.GetAudioOutputConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfiguration", &trt.GetAudioOutputConfiguration{}, out)
	return out, err
}

func (c *Client) GetAudioOutputConfigurationOptions(ctx context.Context) (*trt.GetAudioOutputConfigurationOptionsResponse, error) {
	out := &trt.GetAudioOutputConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfigurationOptions", &trt.GetAudioOutputConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetAudioOutputConfigurations(ctx context.Context) (*trt.GetAudioOutputConfigurationsResponse, error) {
	out := &trt.GetAudioOutputConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfigurations", &trt.GetAudioOutputConfigurations{}, out)
	return out, err
}

func (c *Client) GetAudioOutputs(ctx context.Context) (*trt.GetAudioOutputsResponse, error) {
	out := &trt.GetAudioOutputsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputs", &trt.GetAudioOutputs{}, out)
	return out, err
}

func (c *Client) GetAudioSourceConfiguration(ctx context.Context) (*trt.GetAudioSourceConfigurationResponse, error) {
	out := &trt.GetAudioSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioSourceConfiguration", &trt.GetAudioSourceConfiguration{}, out)
	return out, err
}

func (c *Client) GetAudioSourceConfigurationOptions(ctx context.Context) (*trt.GetAudioSourceConfigurationOptionsResponse, error) {
	out := &trt.GetAudioSourceConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioSourceConfigurationOptions", &trt.GetAudioSourceConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetAudioSourceConfigurations(ctx context.Context) (*trt.GetAudioSourceConfigurationsResponse, error) {
	out := &trt.GetAudioSourceConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdlGetAudioSourceConfigurations/", &trt.GetAudioSourceConfigurations{}, out)
	return out, err
}

func (c *Client) GetAudioSources(ctx context.Context) (*trt.GetAudioSourcesResponse, error) {
	out := &trt.GetAudioSourcesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetAudioSources", &trt.GetAudioSources{}, out)
	return out, err
}

func (c *Client) GetCompatibleAudioDecoderConfigurations(ctx context.Context) (*trt.GetCompatibleAudioDecoderConfigurationsResponse, error) {
	out := &trt.GetCompatibleAudioDecoderConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioDecoderConfigurations", &trt.GetCompatibleAudioDecoderConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleAudioEncoderConfigurations(ctx context.Context) (*trt.GetCompatibleAudioEncoderConfigurationsResponse, error) {
	out := &trt.GetCompatibleAudioEncoderConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioEncoderConfigurations", &trt.GetCompatibleAudioEncoderConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleAudioOutputConfigurations(ctx context.Context) (*trt.GetCompatibleAudioOutputConfigurationsResponse, error) {
	out := &trt.GetCompatibleAudioOutputConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioOutputConfigurations", &trt.GetCompatibleAudioOutputConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleAudioSourceConfigurations(ctx context.Context) (*trt.GetCompatibleAudioSourceConfigurationsResponse, error) {
	out := &trt.GetCompatibleAudioSourceConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioSourceConfigurations", &trt.GetCompatibleAudioSourceConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleMetadataConfigurations(ctx context.Context) (*trt.GetCompatibleMetadataConfigurationsResponse, error) {
	out := &trt.GetCompatibleMetadataConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleMetadataConfigurations", &trt.GetCompatibleMetadataConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleVideoAnalyticsConfigurations(ctx context.Context) (*trt.GetCompatibleVideoAnalyticsConfigurationsResponse, error) {
	out := &trt.GetCompatibleVideoAnalyticsConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoAnalyticsConfigurations", &trt.GetCompatibleVideoAnalyticsConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleVideoEncoderConfigurations(ctx context.Context) (*trt.GetCompatibleVideoEncoderConfigurationsResponse, error) {
	out := &trt.GetCompatibleVideoEncoderConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoEncoderConfigurations", &trt.GetCompatibleVideoEncoderConfigurations{}, out)
	return out, err
}

func (c *Client) GetCompatibleVideoSourceConfigurations(ctx context.Context) (*trt.GetCompatibleVideoSourceConfigurationsResponse, error) {
	out := &trt.GetCompatibleVideoSourceConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoSourceConfigurations", &trt.GetCompatibleVideoSourceConfigurations{}, out)
	return out, err
}

func (c *Client) GetGuaranteedNumberOfVideoEncoderInstances(ctx context.Context) (*trt.GetGuaranteedNumberOfVideoEncoderInstancesResponse, error) {
	out := &trt.GetGuaranteedNumberOfVideoEncoderInstancesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetGuaranteedNumberOfVideoEncoderInstances", &trt.GetGuaranteedNumberOfVideoEncoderInstances{}, out)
	return out, err
}

func (c *Client) GetMetadataConfiguration(ctx context.Context) (*trt.GetMetadataConfigurationResponse, error) {
	out := &trt.GetMetadataConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfiguration", &trt.GetMetadataConfiguration{}, out)
	return out, err
}

func (c *Client) GetMetadataConfigurationOptions(ctx context.Context) (*trt.GetMetadataConfigurationOptionsResponse, error) {
	out := &trt.GetMetadataConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfigurationOptions", &trt.GetMetadataConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetMetadataConfigurations(ctx context.Context) (*trt.GetMetadataConfigurationsResponse, error) {
	out := &trt.GetMetadataConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfigurations", &trt.GetMetadataConfigurations{}, out)
	return out, err
}

func (c *Client) GetOSD(ctx context.Context) (*trt.GetOSDResponse, error) {
	out := &trt.GetOSDResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetOSD", &trt.GetOSD{}, out)
	return out, err
}

func (c *Client) GetOSDOptions(ctx context.Context) (*trt.GetOSDOptionsResponse, error) {
	out := &trt.GetOSDOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetOSDOptions", &trt.GetOSDOptions{}, out)
	return out, err
}

func (c *Client) GetOSDs(ctx context.Context) (*trt.GetOSDsResponse, error) {
	out := &trt.GetOSDsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetOSDs", &trt.GetOSDs{}, out)
	return out, err
}

func (c *Client) GetProfile(ctx context.Context) (*trt.GetProfileResponse, error) {
	out := &trt.GetProfileResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdlGetProfile/", &trt.GetProfile{}, out)
	return out, err
}

func (c *Client) GetProfiles(ctx context.Context) (*trt.GetProfilesResponse, error) {
	out := &trt.GetProfilesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetProfiles", &trt.GetProfiles{}, out)
	return out, err
}

func (c *Client) GetServiceCapabilities(ctx context.Context) (*trt.GetServiceCapabilitiesResponse, error) {
	out := &trt.GetServiceCapabilitiesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetServiceCapabilities", &trt.GetServiceCapabilities{}, out)
	return out, err
}

func (c *Client) GetSnapshotUri(ctx context.Context) (*trt.GetSnapshotUriResponse, error) {
	out := &trt.GetSnapshotUriResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetSnapshotUri", &trt.GetSnapshotUri{}, out)
	return out, err
}

func (c *Client) GetStreamUri(ctx context.Context) (*trt.GetStreamUriResponse, error) {
	out := &trt.GetStreamUriResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetStreamUri", &trt.GetStreamUri{}, out)
	return out, err
}

func (c *Client) GetVideoAnalyticsConfiguration(ctx context.Context) (*trt.GetVideoAnalyticsConfigurationResponse, error) {
	out := &trt.GetVideoAnalyticsConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoAnalyticsConfiguration", &trt.GetVideoAnalyticsConfiguration{}, out)
	return out, err
}

func (c *Client) GetVideoAnalyticsConfigurations(ctx context.Context) (*trt.GetVideoAnalyticsConfigurationsResponse, error) {
	out := &trt.GetVideoAnalyticsConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoAnalyticsConfigurations", &trt.GetVideoAnalyticsConfigurations{}, out)
	return out, err
}

func (c *Client) GetVideoEncoderConfiguration(ctx context.Context) (*trt.GetVideoEncoderConfigurationResponse, error) {
	out := &trt.GetVideoEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfiguration", &trt.GetVideoEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) GetVideoEncoderConfigurationOptions(ctx context.Context) (*trt.GetVideoEncoderConfigurationOptionsResponse, error) {
	out := &trt.GetVideoEncoderConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurationOptions", &trt.GetVideoEncoderConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetVideoEncoderConfigurations(ctx context.Context) (*trt.GetVideoEncoderConfigurationsResponse, error) {
	out := &trt.GetVideoEncoderConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurations", &trt.GetVideoEncoderConfigurations{}, out)
	return out, err
}

func (c *Client) GetVideoSourceConfiguration(ctx context.Context) (*trt.GetVideoSourceConfigurationResponse, error) {
	out := &trt.GetVideoSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfiguration", &trt.GetVideoSourceConfiguration{}, out)
	return out, err
}

func (c *Client) GetVideoSourceConfigurationOptions(ctx context.Context) (*trt.GetVideoSourceConfigurationOptionsResponse, error) {
	out := &trt.GetVideoSourceConfigurationOptionsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdlGetVideoSourceConfigurationOptions/", &trt.GetVideoSourceConfigurationOptions{}, out)
	return out, err
}

func (c *Client) GetVideoSourceConfigurations(ctx context.Context) (*trt.GetVideoSourceConfigurationsResponse, error) {
	out := &trt.GetVideoSourceConfigurationsResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfigurations", &trt.GetVideoSourceConfigurations{}, out)
	return out, err
}

func (c *Client) GetVideoSourceModes(ctx context.Context) (*trt.GetVideoSourceModesResponse, error) {
	out := &trt.GetVideoSourceModesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceModes", &trt.GetVideoSourceModes{}, out)
	return out, err
}

func (c *Client) GetVideoSources(ctx context.Context) (*trt.GetVideoSourcesResponse, error) {
	out := &trt.GetVideoSourcesResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdlGetVideoSources/", &trt.GetVideoSources{}, out)
	return out, err
}

func (c *Client) RemoveAudioDecoderConfiguration(ctx context.Context) (*trt.RemoveAudioDecoderConfigurationResponse, error) {
	out := &trt.RemoveAudioDecoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveAudioDecoderConfiguration", &trt.RemoveAudioDecoderConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveAudioEncoderConfiguration(ctx context.Context) (*trt.RemoveAudioEncoderConfigurationResponse, error) {
	out := &trt.RemoveAudioEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveAudioEncoderConfiguration", &trt.RemoveAudioEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveAudioOutputConfiguration(ctx context.Context) (*trt.RemoveAudioOutputConfigurationResponse, error) {
	out := &trt.RemoveAudioOutputConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveAudioOutputConfiguration", &trt.RemoveAudioOutputConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveAudioSourceConfiguration(ctx context.Context) (*trt.RemoveAudioSourceConfigurationResponse, error) {
	out := &trt.RemoveAudioSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveAudioSourceConfiguration", &trt.RemoveAudioSourceConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveMetadataConfiguration(ctx context.Context) (*trt.RemoveMetadataConfigurationResponse, error) {
	out := &trt.RemoveMetadataConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveMetadataConfiguration", &trt.RemoveMetadataConfiguration{}, out)
	return out, err
}

func (c *Client) RemovePTZConfiguration(ctx context.Context) (*trt.RemovePTZConfigurationResponse, error) {
	out := &trt.RemovePTZConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemovePTZConfiguration", &trt.RemovePTZConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveVideoAnalyticsConfiguration(ctx context.Context) (*trt.RemoveVideoAnalyticsConfigurationResponse, error) {
	out := &trt.RemoveVideoAnalyticsConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveVideoAnalyticsConfiguration", &trt.RemoveVideoAnalyticsConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveVideoEncoderConfiguration(ctx context.Context) (*trt.RemoveVideoEncoderConfigurationResponse, error) {
	out := &trt.RemoveVideoEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveVideoEncoderConfiguration", &trt.RemoveVideoEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) RemoveVideoSourceConfiguration(ctx context.Context) (*trt.RemoveVideoSourceConfigurationResponse, error) {
	out := &trt.RemoveVideoSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/RemoveVideoSourceConfiguration", &trt.RemoveVideoSourceConfiguration{}, out)
	return out, err
}

func (c *Client) SetAudioDecoderConfiguration(ctx context.Context) (*trt.SetAudioDecoderConfigurationResponse, error) {
	out := &trt.SetAudioDecoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetAudioDecoderConfiguration", &trt.SetAudioDecoderConfiguration{}, out)
	return out, err
}

func (c *Client) SetAudioEncoderConfiguration(ctx context.Context) (*trt.SetAudioEncoderConfigurationResponse, error) {
	out := &trt.SetAudioEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetAudioEncoderConfiguration", &trt.SetAudioEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) SetAudioOutputConfiguration(ctx context.Context) (*trt.SetAudioOutputConfigurationResponse, error) {
	out := &trt.SetAudioOutputConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetAudioOutputConfiguration", &trt.SetAudioOutputConfiguration{}, out)
	return out, err
}

func (c *Client) SetAudioSourceConfiguration(ctx context.Context) (*trt.SetAudioSourceConfigurationResponse, error) {
	out := &trt.SetAudioSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetAudioSourceConfiguration", &trt.SetAudioSourceConfiguration{}, out)
	return out, err
}

func (c *Client) SetMetadataConfiguration(ctx context.Context) (*trt.SetMetadataConfigurationResponse, error) {
	out := &trt.SetMetadataConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetMetadataConfiguration", &trt.SetMetadataConfiguration{}, out)
	return out, err
}

func (c *Client) SetOSD(ctx context.Context) (*trt.SetOSDResponse, error) {
	out := &trt.SetOSDResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetOSD", &trt.SetOSD{}, out)
	return out, err
}

func (c *Client) SetSynchronizationPoint(ctx context.Context) (*trt.SetSynchronizationPointResponse, error) {
	out := &trt.SetSynchronizationPointResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetSynchronizationPoint", &trt.SetSynchronizationPoint{}, out)
	return out, err
}

func (c *Client) SetVideoAnalyticsConfiguration(ctx context.Context) (*trt.SetVideoAnalyticsConfigurationResponse, error) {
	out := &trt.SetVideoAnalyticsConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetVideoAnalyticsConfiguration", &trt.SetVideoAnalyticsConfiguration{}, out)
	return out, err
}

func (c *Client) SetVideoEncoderConfiguration(ctx context.Context) (*trt.SetVideoEncoderConfigurationResponse, error) {
	out := &trt.SetVideoEncoderConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetVideoEncoderConfiguration", &trt.SetVideoEncoderConfiguration{}, out)
	return out, err
}

func (c *Client) SetVideoSourceConfiguration(ctx context.Context) (*trt.SetVideoSourceConfigurationResponse, error) {
	out := &trt.SetVideoSourceConfigurationResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetVideoSourceConfiguration", &trt.SetVideoSourceConfiguration{}, out)
	return out, err
}

func (c *Client) SetVideoSourceMode(ctx context.Context) (*trt.SetVideoSourceModeResponse, error) {
	out := &trt.SetVideoSourceModeResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/SetVideoSourceMode", &trt.SetVideoSourceMode{}, out)
	return out, err
}

func (c *Client) StartMulticastStreaming(ctx context.Context) (*trt.StartMulticastStreamingResponse, error) {
	out := &trt.StartMulticastStreamingResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/StartMulticastStreaming", &trt.StartMulticastStreaming{}, out)
	return out, err
}

func (c *Client) StopMulticastStreaming(ctx context.Context) (*trt.StopMulticastStreamingResponse, error) {
	out := &trt.StopMulticastStreamingResponse{}
	err := c.c.Do(ctx, "http://www.onvif.org/ver10/media/wsdl/StopMulticastStreaming", &trt.StopMulticastStreaming{}, out)
	return out, err
}

