// Code generated by onvifgen; DO NOT EDIT.

package tar

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/pacs"
)

type Capabilities ServiceCapabilities

type CreateAccessProfile struct {
	AccessProfile AccessProfile `xml:"AccessProfile"`
}

type CreateAccessProfileResponse struct {
	Token pacs.ReferenceToken `xml:"Token"`
}

type DeleteAccessProfile struct {
	Token pacs.ReferenceToken `xml:"Token"`
}

type DeleteAccessProfileResponse struct {
}

type GetAccessProfileInfo struct {
	Token []pacs.ReferenceToken `xml:"Token,omitempty"`
}

type GetAccessProfileInfoList struct {
	Limit *int32 `xml:"Limit,omitempty"`
	StartReference *string `xml:"StartReference,omitempty"`
}

type GetAccessProfileInfoListResponse struct {
	NextStartReference *string `xml:"NextStartReference,omitempty"`
	AccessProfileInfo []AccessProfileInfo `xml:"AccessProfileInfo,omitempty"`
}

type GetAccessProfileInfoResponse struct {
	AccessProfileInfo []AccessProfileInfo `xml:"AccessProfileInfo,omitempty"`
}

type GetAccessProfileList struct {
	Limit *int32 `xml:"Limit,omitempty"`
	StartReference *string `xml:"StartReference,omitempty"`
}

type GetAccessProfileListResponse struct {
	NextStartReference *string `xml:"NextStartReference,omitempty"`
	AccessProfile []AccessProfile `xml:"AccessProfile,omitempty"`
}

type GetAccessProfiles struct {
	Token []pacs.ReferenceToken `xml:"Token,omitempty"`
}

type GetAccessProfilesResponse struct {
	AccessProfile []AccessProfile `xml:"AccessProfile,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities ServiceCapabilities `xml:"Capabilities"`
}

type ModifyAccessProfile struct {
	AccessProfile AccessProfile `xml:"AccessProfile"`
}

type ModifyAccessProfileResponse struct {
}

type SetAccessProfile struct {
	AccessProfile AccessProfile `xml:"AccessProfile"`
}

type SetAccessProfileResponse struct {
}

