// Code generated by onvifgen; DO NOT EDIT.

package tmd

// The parity for the data error detection.
type ParityBit string

const (
	ParityBitNone ParityBit = "None"
	ParityBitEven ParityBit = "Even"
	ParityBitOdd ParityBit = "Odd"
	ParityBitMark ParityBit = "Mark"
	ParityBitSpace ParityBit = "Space"
	ParityBitExtended ParityBit = "Extended"
)

// The type of serial port.Generic can be signaled as a vendor specific serial port type.
type SerialPortType string

const (
	SerialPortTypeRS232 SerialPortType = "RS232"
	SerialPortTypeRS422HalfDuplex SerialPortType = "RS422HalfDuplex"
	SerialPortTypeRS422FullDuplex SerialPortType = "RS422FullDuplex"
	SerialPortTypeRS485HalfDuplex SerialPortType = "RS485HalfDuplex"
	SerialPortTypeRS485FullDuplex SerialPortType = "RS485FullDuplex"
	SerialPortTypeGeneric SerialPortType = "Generic"
)

