// Code generated by onvifgen; DO NOT EDIT.

package tan

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type CreateAnalyticsModules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	AnalyticsModule []tt.Config `xml:"AnalyticsModule,omitempty"`
}

type CreateAnalyticsModulesResponse struct {
}

type CreateRules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	Rule []tt.Config `xml:"Rule,omitempty"`
}

type CreateRulesResponse struct {
}

type DeleteAnalyticsModules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	AnalyticsModuleName []string `xml:"AnalyticsModuleName,omitempty"`
}

type DeleteAnalyticsModulesResponse struct {
}

type DeleteRules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	RuleName []string `xml:"RuleName,omitempty"`
}

type DeleteRulesResponse struct {
}

type GetAnalyticsModuleOptions struct {
	Type **core.QName `xml:"Type,omitempty"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetAnalyticsModuleOptionsResponse struct {
	Options []ConfigOptions `xml:"Options,omitempty"`
}

type GetAnalyticsModules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetAnalyticsModulesResponse struct {
	AnalyticsModule []tt.Config `xml:"AnalyticsModule,omitempty"`
}

type GetRuleOptions struct {
	RuleType **core.QName `xml:"RuleType,omitempty"`
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetRuleOptionsResponse struct {
	RuleOptions []ConfigOptions `xml:"RuleOptions,omitempty"`
}

type GetRules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetRulesResponse struct {
	Rule []tt.Config `xml:"Rule,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type GetSupportedAnalyticsModules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetSupportedAnalyticsModulesResponse struct {
	SupportedAnalyticsModules tt.SupportedAnalyticsModules `xml:"SupportedAnalyticsModules"`
}

type GetSupportedMetadata struct {
	Type **core.QName `xml:"Type,omitempty"`
}

type GetSupportedMetadataResponse struct {
	AnalyticsModule []MetadataInfo `xml:"AnalyticsModule,omitempty"`
}

type GetSupportedRules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetSupportedRulesResponse struct {
	SupportedRules tt.SupportedRules `xml:"SupportedRules"`
}

type ModifyAnalyticsModules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	AnalyticsModule []tt.Config `xml:"AnalyticsModule,omitempty"`
}

type ModifyAnalyticsModulesResponse struct {
}

type ModifyRules struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
	Rule []tt.Config `xml:"Rule,omitempty"`
}

type ModifyRulesResponse struct {
}

