// Code generated by onvifgen; DO NOT EDIT.

package wsn

import (
	"encoding/xml"
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsa"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsrfbf"
)

type FilterType struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type InvalidFilterFaultType struct {
	Base21 wsrfbf.BaseFaultType `xml:",omitempty"`
	UnknownFilter []*core.QName `xml:"UnknownFilter,omitempty"`
}

type InvalidMessageContentExpressionFaultType struct {
	Base22 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type InvalidProducerPropertiesExpressionFaultType struct {
	Base23 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type InvalidTopicExpressionFaultType struct {
	Base24 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type MultipleTopicsSpecifiedFaultType struct {
	Base25 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type NoCurrentMessageOnTopicFaultType struct {
	Base26 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type NotificationMessageHolderType struct {
	Base27 *wsa.EndpointReferenceType `xml:",omitempty"`
	Base28 *TopicExpressionType `xml:",omitempty"`
	Base29 *wsa.EndpointReferenceType `xml:",omitempty"`
}

type NotifyMessageNotSupportedFaultType struct {
	Base30 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type PauseFailedFaultType struct {
	Base31 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type QueryExpressionType struct {
	Any core.Extension `xml:"Any,omitempty"`
	Dialect string `xml:"Dialect,attr"`
}

type ResumeFailedFaultType struct {
	Base32 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type SubscribeCreationFailedFaultType struct {
	Base33 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type SubscriptionPolicyType struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type TopicExpressionDialectUnknownFaultType struct {
	Base34 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type TopicExpressionType struct {
	Any core.Extension `xml:"Any,omitempty"`
	Dialect string `xml:"Dialect,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type TopicNotSupportedFaultType struct {
	Base35 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToCreatePullPointFaultType struct {
	Base36 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToDestroyPullPointFaultType struct {
	Base37 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToDestroySubscriptionFaultType struct {
	Base38 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToGetMessagesFaultType struct {
	Base39 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnacceptableInitialTerminationTimeFaultType struct {
	Base40 wsrfbf.BaseFaultType `xml:",omitempty"`
	MinimumTime time.Time `xml:"MinimumTime"`
	MaximumTime *time.Time `xml:"MaximumTime,omitempty"`
}

type UnacceptableTerminationTimeFaultType struct {
	Base41 wsrfbf.BaseFaultType `xml:",omitempty"`
	MinimumTime time.Time `xml:"MinimumTime"`
	MaximumTime *time.Time `xml:"MaximumTime,omitempty"`
}

type UnrecognizedPolicyRequestFaultType struct {
	Base42 wsrfbf.BaseFaultType `xml:",omitempty"`
	UnrecognizedPolicy []*core.QName `xml:"UnrecognizedPolicy,omitempty"`
}

type UnsupportedPolicyRequestFaultType struct {
	Base43 wsrfbf.BaseFaultType `xml:",omitempty"`
	UnsupportedPolicy []*core.QName `xml:"UnsupportedPolicy,omitempty"`
}

