// Code generated by onvifgen; DO NOT EDIT.

package trc

import (
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type CreateRecording struct {
	RecordingConfiguration tt.RecordingConfiguration `xml:"RecordingConfiguration"`
}

type CreateRecordingJob struct {
	JobConfiguration tt.RecordingJobConfiguration `xml:"JobConfiguration"`
}

type CreateRecordingJobResponse struct {
	JobToken tt.RecordingJobReference `xml:"JobToken"`
	JobConfiguration tt.RecordingJobConfiguration `xml:"JobConfiguration"`
}

type CreateRecordingResponse struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
}

type CreateTrack struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
	TrackConfiguration tt.TrackConfiguration `xml:"TrackConfiguration"`
}

type CreateTrackResponse struct {
	TrackToken tt.TrackReference `xml:"TrackToken"`
}

type DeleteRecording struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
}

type DeleteRecordingJob struct {
	JobToken tt.RecordingJobReference `xml:"JobToken"`
}

type DeleteRecordingJobResponse struct {
}

type DeleteRecordingResponse struct {
}

type DeleteTrack struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
	TrackToken tt.TrackReference `xml:"TrackToken"`
}

type DeleteTrackResponse struct {
}

type ExportRecordedData struct {
	StartPoint *time.Time `xml:"StartPoint,omitempty"`
	EndPoint *time.Time `xml:"EndPoint,omitempty"`
	SearchScope tt.SearchScope `xml:"SearchScope"`
	FileFormat string `xml:"FileFormat"`
	StorageDestination tt.StorageReferencePath `xml:"StorageDestination"`
}

type ExportRecordedDataResponse struct {
	OperationToken tt.ReferenceToken `xml:"OperationToken"`
	FileNames []string `xml:"FileNames,omitempty"`
}

type GetExportRecordedDataState struct {
	OperationToken tt.ReferenceToken `xml:"OperationToken"`
}

type GetExportRecordedDataStateResponse struct {
	Progress float32 `xml:"Progress"`
	FileProgressStatus tt.ArrayOfFileProgress `xml:"FileProgressStatus"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetRecordingConfiguration struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
}

type GetRecordingConfigurationResponse struct {
	RecordingConfiguration tt.RecordingConfiguration `xml:"RecordingConfiguration"`
}

type GetRecordingJobConfiguration struct {
	JobToken tt.RecordingJobReference `xml:"JobToken"`
}

type GetRecordingJobConfigurationResponse struct {
	JobConfiguration tt.RecordingJobConfiguration `xml:"JobConfiguration"`
}

type GetRecordingJobState struct {
	JobToken tt.RecordingJobReference `xml:"JobToken"`
}

type GetRecordingJobStateResponse struct {
	State tt.RecordingJobStateInformation `xml:"State"`
}

type GetRecordingJobs struct {
}

type GetRecordingJobsResponse struct {
	JobItem []tt.GetRecordingJobsResponseItem `xml:"JobItem,omitempty"`
}

type GetRecordingOptions struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
}

type GetRecordingOptionsResponse struct {
	Options RecordingOptions `xml:"Options"`
}

type GetRecordings struct {
}

type GetRecordingsResponse struct {
	RecordingItem []tt.GetRecordingsResponseItem `xml:"RecordingItem,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities `xml:"Capabilities"`
}

type GetTrackConfiguration struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
	TrackToken tt.TrackReference `xml:"TrackToken"`
}

type GetTrackConfigurationResponse struct {
	TrackConfiguration tt.TrackConfiguration `xml:"TrackConfiguration"`
}

type OverrideSegmentDuration struct {
	TargetSegmentDuration *core.Duration `xml:"TargetSegmentDuration"`
	Expiration *core.Duration `xml:"Expiration"`
	RecordingConfiguration tt.RecordingReference `xml:"RecordingConfiguration"`
}

type OverrideSegmentDurationResponse struct {
}

type SetRecordingConfiguration struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
	RecordingConfiguration tt.RecordingConfiguration `xml:"RecordingConfiguration"`
}

type SetRecordingConfigurationResponse struct {
}

type SetRecordingJobConfiguration struct {
	JobToken tt.RecordingJobReference `xml:"JobToken"`
	JobConfiguration tt.RecordingJobConfiguration `xml:"JobConfiguration"`
}

type SetRecordingJobConfigurationResponse struct {
	JobConfiguration tt.RecordingJobConfiguration `xml:"JobConfiguration"`
}

type SetRecordingJobMode struct {
	JobToken tt.RecordingJobReference `xml:"JobToken"`
	Mode tt.RecordingJobMode `xml:"Mode"`
}

type SetRecordingJobModeResponse struct {
}

type SetTrackConfiguration struct {
	RecordingToken tt.RecordingReference `xml:"RecordingToken"`
	TrackToken tt.TrackReference `xml:"TrackToken"`
	TrackConfiguration tt.TrackConfiguration `xml:"TrackConfiguration"`
}

type SetTrackConfigurationResponse struct {
}

type StopExportRecordedData struct {
	OperationToken tt.ReferenceToken `xml:"OperationToken"`
}

type StopExportRecordedDataResponse struct {
	Progress float32 `xml:"Progress"`
	FileProgressStatus tt.ArrayOfFileProgress `xml:"FileProgressStatus"`
	Any core.Extension `xml:"Any,omitempty"`
}

