// Code generated by onvifgen; DO NOT EDIT.

package wsnt

import (
	"github.com/furrysalamander/onvif-go/onvif/schema/core"
)

type ConcreteTopicExpression string

type FullTopicExpression string

type SimpleTopicExpression *core.QName

