// Code generated by onvifgen; DO NOT EDIT.

package tr2

import (
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type AddAudioClip struct {
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
	Configuration AudioClip `xml:"Configuration"`
}

type AddAudioClipResponse struct {
	Token tt.ReferenceToken `xml:"Token"`
	UploadUri string `xml:"UploadUri"`
	ExpiryTime time.Time `xml:"ExpiryTime"`
}

type AddConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	Name *tt.Name `xml:"Name,omitempty"`
	Configuration []ConfigurationRef `xml:"Configuration,omitempty"`
}

type AddConfigurationResponse struct {
}

type Capabilities Capabilities2

type CreateMask struct {
	Mask Mask `xml:"Mask"`
}

type CreateMaskResponse struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type CreateOSD struct {
	OSD tt.OSDConfiguration `xml:"OSD"`
}

type CreateOSDResponse struct {
	OSDToken tt.ReferenceToken `xml:"OSDToken"`
}

type CreateProfile struct {
	Name tt.Name `xml:"Name"`
	Configuration []ConfigurationRef `xml:"Configuration,omitempty"`
}

type CreateProfileResponse struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type DeleteAudioClip struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type DeleteAudioClipResponse struct {
}

type DeleteMask struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type DeleteMaskResponse SetConfigurationResponse

type DeleteOSD struct {
	OSDToken tt.ReferenceToken `xml:"OSDToken"`
}

type DeleteOSDResponse SetConfigurationResponse

type DeleteProfile struct {
	Token tt.ReferenceToken `xml:"Token"`
}

type DeleteProfileResponse struct {
}

type GetAnalyticsConfigurations GetConfiguration

type GetAnalyticsConfigurationsResponse struct {
	Configurations []tt.VideoAnalyticsConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioClips struct {
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
}

type GetAudioClipsResponse struct {
	AudioClipItem []GetAudioClipsResponseItem `xml:"AudioClipItem,omitempty"`
}

type GetAudioDecoderConfigurationOptions GetConfiguration

type GetAudioDecoderConfigurationOptionsResponse struct {
	Options []tt.AudioEncoder2ConfigurationOptions `xml:"Options,omitempty"`
}

type GetAudioDecoderConfigurations GetConfiguration

type GetAudioDecoderConfigurationsResponse struct {
	Configurations []tt.AudioDecoderConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioEncoderConfigurationOptions GetConfiguration

type GetAudioEncoderConfigurationOptionsResponse struct {
	Options []tt.AudioEncoder2ConfigurationOptions `xml:"Options,omitempty"`
}

type GetAudioEncoderConfigurations GetConfiguration

type GetAudioEncoderConfigurationsResponse struct {
	Configurations []tt.AudioEncoder2Configuration `xml:"Configurations,omitempty"`
}

type GetAudioOutputConfigurationOptions GetConfiguration

type GetAudioOutputConfigurationOptionsResponse struct {
	Options tt.AudioOutputConfigurationOptions `xml:"Options"`
}

type GetAudioOutputConfigurations GetConfiguration

type GetAudioOutputConfigurationsResponse struct {
	Configurations []tt.AudioOutputConfiguration `xml:"Configurations,omitempty"`
}

type GetAudioSourceConfigurationOptions GetConfiguration

type GetAudioSourceConfigurationOptionsResponse struct {
	Options tt.AudioSourceConfigurationOptions `xml:"Options"`
}

type GetAudioSourceConfigurations GetConfiguration

type GetAudioSourceConfigurationsResponse struct {
	Configurations []tt.AudioSourceConfiguration `xml:"Configurations,omitempty"`
}

type GetMaskOptions struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetMaskOptionsResponse struct {
	Options MaskOptions `xml:"Options"`
}

type GetMasks struct {
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
}

type GetMasksResponse struct {
	Masks []Mask `xml:"Masks,omitempty"`
}

type GetMetadataConfigurationOptions GetConfiguration

type GetMetadataConfigurationOptionsResponse struct {
	Options tt.MetadataConfigurationOptions `xml:"Options"`
}

type GetMetadataConfigurations GetConfiguration

type GetMetadataConfigurationsResponse struct {
	Configurations []tt.MetadataConfiguration `xml:"Configurations,omitempty"`
}

type GetMulticastAudioDecoderConfigurationOptions struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
}

type GetMulticastAudioDecoderConfigurationOptionsResponse struct {
	Options []tt.MulticastAudioDecoderConfigurationOptions `xml:"Options,omitempty"`
}

type GetMulticastAudioDecoderConfigurations struct {
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
}

type GetMulticastAudioDecoderConfigurationsResponse struct {
	Configurations []tt.MulticastAudioDecoderConfiguration `xml:"Configurations,omitempty"`
}

type GetOSDOptions struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetOSDOptionsResponse struct {
	OSDOptions tt.OSDConfigurationOptions `xml:"OSDOptions"`
}

type GetOSDs struct {
	OSDToken *tt.ReferenceToken `xml:"OSDToken,omitempty"`
	ConfigurationToken *tt.ReferenceToken `xml:"ConfigurationToken,omitempty"`
}

type GetOSDsResponse struct {
	OSDs []tt.OSDConfiguration `xml:"OSDs,omitempty"`
}

type GetPlayingAudioClips struct {
}

type GetPlayingAudioClipsResponse struct {
	PlayingAudioClips []PlayingAudioClips `xml:"PlayingAudioClips,omitempty"`
}

type GetProfiles struct {
	Token *tt.ReferenceToken `xml:"Token,omitempty"`
	Type []string `xml:"Type,omitempty"`
}

type GetProfilesResponse struct {
	Profiles []MediaProfile `xml:"Profiles,omitempty"`
}

type GetServiceCapabilities struct {
}

type GetServiceCapabilitiesResponse struct {
	Capabilities Capabilities2 `xml:"Capabilities"`
}

type GetSnapshotUri struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetSnapshotUriResponse struct {
	Uri string `xml:"Uri"`
}

type GetStreamUri struct {
	Protocol string `xml:"Protocol"`
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type GetStreamUriResponse struct {
	Uri string `xml:"Uri"`
}

type GetVideoEncoderConfigurationOptions GetConfiguration

type GetVideoEncoderConfigurationOptionsResponse struct {
	Options []tt.VideoEncoder2ConfigurationOptions `xml:"Options,omitempty"`
}

type GetVideoEncoderConfigurations GetConfiguration

type GetVideoEncoderConfigurationsResponse struct {
	Configurations []tt.VideoEncoder2Configuration `xml:"Configurations,omitempty"`
}

type GetVideoEncoderInstances struct {
	ConfigurationToken tt.ReferenceToken `xml:"ConfigurationToken"`
}

type GetVideoEncoderInstancesResponse struct {
	Info EncoderInstanceInfo `xml:"Info"`
}

type GetVideoSourceConfigurationOptions GetConfiguration

type GetVideoSourceConfigurationOptionsResponse struct {
	Options tt.VideoSourceConfigurationOptions `xml:"Options"`
}

type GetVideoSourceConfigurations GetConfiguration

type GetVideoSourceConfigurationsResponse struct {
	Configurations []tt.VideoSourceConfiguration `xml:"Configurations,omitempty"`
}

type GetVideoSourceModes struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
}

type GetVideoSourceModesResponse struct {
	VideoSourceModes []VideoSourceMode `xml:"VideoSourceModes,omitempty"`
}

type GetWebRTCConfigurations struct {
}

type GetWebRTCConfigurationsResponse struct {
	WebRTCConfiguration []WebRTCConfiguration `xml:"WebRTCConfiguration,omitempty"`
}

type PlayAudioClip struct {
	Token tt.ReferenceToken `xml:"Token"`
	AudioOutputToken []tt.ReferenceToken `xml:"AudioOutputToken,omitempty"`
	Play bool `xml:"Play"`
	RepeatCycles *int32 `xml:"RepeatCycles,omitempty"`
}

type PlayAudioClipResponse struct {
}

type RemoveConfiguration struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
	Configuration []ConfigurationRef `xml:"Configuration,omitempty"`
}

type RemoveConfigurationResponse struct {
}

type SetAudioClip struct {
	Token tt.ReferenceToken `xml:"Token"`
	Configuration AudioClip `xml:"Configuration"`
}

type SetAudioClipResponse struct {
}

type SetAudioDecoderConfiguration struct {
	Configuration tt.AudioDecoderConfiguration `xml:"Configuration"`
}

type SetAudioDecoderConfigurationResponse SetConfigurationResponse

type SetAudioEncoderConfiguration struct {
	Configuration tt.AudioEncoder2Configuration `xml:"Configuration"`
}

type SetAudioEncoderConfigurationResponse SetConfigurationResponse

type SetAudioOutputConfiguration struct {
	Configuration tt.AudioOutputConfiguration `xml:"Configuration"`
}

type SetAudioOutputConfigurationResponse SetConfigurationResponse

type SetAudioSourceConfiguration struct {
	Configuration tt.AudioSourceConfiguration `xml:"Configuration"`
}

type SetAudioSourceConfigurationResponse SetConfigurationResponse

type SetEQPresetConfiguration struct {
	Configuration tt.EQPreset `xml:"Configuration"`
}

type SetEQPresetConfigurationResponse SetConfigurationResponse

type SetMask struct {
	Mask Mask `xml:"Mask"`
}

type SetMaskResponse SetConfigurationResponse

type SetMetadataConfiguration struct {
	Configuration tt.MetadataConfiguration `xml:"Configuration"`
}

type SetMetadataConfigurationResponse SetConfigurationResponse

type SetMulticastAudioDecoderConfiguration struct {
	Configuration tt.MulticastAudioDecoderConfiguration `xml:"Configuration"`
}

type SetMulticastAudioDecoderConfigurationResponse SetConfigurationResponse

type SetOSD struct {
	OSD tt.OSDConfiguration `xml:"OSD"`
}

type SetOSDResponse SetConfigurationResponse

type SetSynchronizationPoint struct {
	ProfileToken tt.ReferenceToken `xml:"ProfileToken"`
}

type SetSynchronizationPointResponse struct {
}

type SetVideoEncoderConfiguration struct {
	Configuration tt.VideoEncoder2Configuration `xml:"Configuration"`
}

type SetVideoEncoderConfigurationResponse SetConfigurationResponse

type SetVideoSourceConfiguration struct {
	Configuration tt.VideoSourceConfiguration `xml:"Configuration"`
}

type SetVideoSourceConfigurationResponse SetConfigurationResponse

type SetVideoSourceMode struct {
	VideoSourceToken tt.ReferenceToken `xml:"VideoSourceToken"`
	VideoSourceModeToken tt.ReferenceToken `xml:"VideoSourceModeToken"`
}

type SetVideoSourceModeResponse struct {
	Reboot bool `xml:"Reboot"`
}

type SetWebRTCConfigurations struct {
	WebRTCConfiguration []WebRTCConfiguration `xml:"WebRTCConfiguration,omitempty"`
}

type SetWebRTCConfigurationsResponse struct {
}

type StartMulticastStreaming StartStopMulticastStreaming

type StartMulticastStreamingResponse SetConfigurationResponse

type StopMulticastStreaming StartStopMulticastStreaming

type StopMulticastStreamingResponse SetConfigurationResponse

