// Code generated by onvifgen; DO NOT EDIT.

package tr2

type ConfigurationEnumeration string

const (
	ConfigurationEnumerationAll ConfigurationEnumeration = "All"
	ConfigurationEnumerationVideoSource ConfigurationEnumeration = "VideoSource"
	ConfigurationEnumerationVideoEncoder ConfigurationEnumeration = "VideoEncoder"
	ConfigurationEnumerationAudioSource ConfigurationEnumeration = "AudioSource"
	ConfigurationEnumerationAudioEncoder ConfigurationEnumeration = "AudioEncoder"
	ConfigurationEnumerationAudioOutput ConfigurationEnumeration = "AudioOutput"
	ConfigurationEnumerationAudioDecoder ConfigurationEnumeration = "AudioDecoder"
	ConfigurationEnumerationMetadata ConfigurationEnumeration = "Metadata"
	ConfigurationEnumerationAnalytics ConfigurationEnumeration = "Analytics"
	ConfigurationEnumerationPTZ ConfigurationEnumeration = "PTZ"
	ConfigurationEnumerationReceiver ConfigurationEnumeration = "Receiver"
)

type MaskType string

const (
	MaskTypeColor MaskType = "Color"
	MaskTypePixelated MaskType = "Pixelated"
	MaskTypeBlurred MaskType = "Blurred"
)

type SupportedAudioClipFormat string

const (
	SupportedAudioClipFormatAudio_vnd_wave_codec_1 SupportedAudioClipFormat = "audio/vnd.wave;codec=1"
	SupportedAudioClipFormatAudio_vnd_wave_codec_7 SupportedAudioClipFormat = "audio/vnd.wave;codec=7"
	SupportedAudioClipFormatAudio_mpeg SupportedAudioClipFormat = "audio/mpeg"
	SupportedAudioClipFormatAudio_ogg_codecs_opus SupportedAudioClipFormat = "audio/ogg;codecs=opus"
	SupportedAudioClipFormatAudio_ogg_codecs_vorbis SupportedAudioClipFormat = "audio/ogg;codecs=vorbis"
	SupportedAudioClipFormatAudio_ogg_codecs_flac SupportedAudioClipFormat = "audio/ogg;codecs=flac"
	SupportedAudioClipFormatAudio_ogg_codecs_speex SupportedAudioClipFormat = "audio/ogg;codecs=speex"
)

type TransportProtocol string

const (
	TransportProtocolRtspUnicast TransportProtocol = "RtspUnicast"
	TransportProtocolRtspMulticast TransportProtocol = "RtspMulticast"
	TransportProtocolRtspsUnicast TransportProtocol = "RtspsUnicast"
	TransportProtocolRtspsMulticast TransportProtocol = "RtspsMulticast"
	TransportProtocolRTSP TransportProtocol = "RTSP"
	TransportProtocolRtspOverHttp TransportProtocol = "RtspOverHttp"
)

