// Code generated by onvifgen; DO NOT EDIT.

package ans

import (
	"encoding/xml"
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/tt"
)

type AppInfo struct {
	AppID string `xml:"AppID"`
	Name string `xml:"Name"`
	Version string `xml:"Version"`
	Licenses []LicenseInfo `xml:"Licenses,omitempty"`
	Privileges []string `xml:"Privileges,omitempty"`
	InstallationDate time.Time `xml:"InstallationDate"`
	LastUpdate time.Time `xml:"LastUpdate"`
	State AppState `xml:"State"`
	Status string `xml:"Status"`
	Autostart bool `xml:"Autostart"`
	Website string `xml:"Website"`
	OpenSource *string `xml:"OpenSource,omitempty"`
	Configuration *string `xml:"Configuration,omitempty"`
	InterfaceDescription []string `xml:"InterfaceDescription,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Capabilities struct {
	Any core.Extension `xml:"Any,omitempty"`
	FormatsSupported tt.StringAttrList `xml:"FormatsSupported,omitempty,attr"`
	Licensing bool `xml:"Licensing,omitempty,attr"`
	UploadPath string `xml:"UploadPath,omitempty,attr"`
	EventTopicPrefix string `xml:"EventTopicPrefix,omitempty,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type LicenseInfo struct {
	Name string `xml:"Name"`
	ValidFrom *time.Time `xml:"ValidFrom,omitempty"`
	ValidUntil *time.Time `xml:"ValidUntil,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

