// Code generated by onvifgen; DO NOT EDIT.

package ans

type AppState string

const (
	AppStateActive AppState = "Active"
	AppStateInactive AppState = "Inactive"
	AppStateInstalling AppState = "Installing"
	AppStateUninstalling AppState = "Uninstalling"
	AppStateRemoved AppState = "Removed"
	AppStateInstallationFailed AppState = "InstallationFailed"
)

