// Code generated by onvifgen; DO NOT EDIT.

package wsn

import (
	"encoding/xml"
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsa"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsrfbf"
)

type FilterType struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type InvalidFilterFaultType struct {
	Base66 wsrfbf.BaseFaultType `xml:",omitempty"`
	UnknownFilter []*core.QName `xml:"UnknownFilter,omitempty"`
}

type InvalidMessageContentExpressionFaultType struct {
	Base67 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type InvalidProducerPropertiesExpressionFaultType struct {
	Base68 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type InvalidTopicExpressionFaultType struct {
	Base69 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type MultipleTopicsSpecifiedFaultType struct {
	Base70 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type NoCurrentMessageOnTopicFaultType struct {
	Base71 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type NotificationMessageHolderType struct {
	Base72 *wsa.EndpointReferenceType `xml:",omitempty"`
	Base73 *TopicExpressionType `xml:",omitempty"`
	Base74 *wsa.EndpointReferenceType `xml:",omitempty"`
}

type NotifyMessageNotSupportedFaultType struct {
	Base75 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type PauseFailedFaultType struct {
	Base76 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type QueryExpressionType struct {
	Any core.Extension `xml:"Any,omitempty"`
	Dialect string `xml:"Dialect,attr"`
}

type ResumeFailedFaultType struct {
	Base77 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type SubscribeCreationFailedFaultType struct {
	Base78 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type SubscriptionPolicyType struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type TopicExpressionDialectUnknownFaultType struct {
	Base79 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type TopicExpressionType struct {
	Any core.Extension `xml:"Any,omitempty"`
	Dialect string `xml:"Dialect,attr"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type TopicNotSupportedFaultType struct {
	Base80 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToCreatePullPointFaultType struct {
	Base81 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToDestroyPullPointFaultType struct {
	Base82 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToDestroySubscriptionFaultType struct {
	Base83 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnableToGetMessagesFaultType struct {
	Base84 wsrfbf.BaseFaultType `xml:",omitempty"`
}

type UnacceptableInitialTerminationTimeFaultType struct {
	Base85 wsrfbf.BaseFaultType `xml:",omitempty"`
	MinimumTime time.Time `xml:"MinimumTime"`
	MaximumTime *time.Time `xml:"MaximumTime,omitempty"`
}

type UnacceptableTerminationTimeFaultType struct {
	Base86 wsrfbf.BaseFaultType `xml:",omitempty"`
	MinimumTime time.Time `xml:"MinimumTime"`
	MaximumTime *time.Time `xml:"MaximumTime,omitempty"`
}

type UnrecognizedPolicyRequestFaultType struct {
	Base87 wsrfbf.BaseFaultType `xml:",omitempty"`
	UnrecognizedPolicy []*core.QName `xml:"UnrecognizedPolicy,omitempty"`
}

type UnsupportedPolicyRequestFaultType struct {
	Base88 wsrfbf.BaseFaultType `xml:",omitempty"`
	UnsupportedPolicy []*core.QName `xml:"UnsupportedPolicy,omitempty"`
}

