// Code generated by onvifgen; DO NOT EDIT.

// Package wsn contains ONVIF-generated types for the
// http://docs.oasis-open.org/wsn/b-2 namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package wsn

const NS = "http://docs.oasis-open.org/wsn/b-2"
