// Code generated by onvifgen; DO NOT EDIT.

package wsn

import (
	"encoding/xml"
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsa"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsnt"
)

type ConsumerReference wsa.EndpointReferenceType

type CreatePullPoint struct {
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CreatePullPointResponse struct {
	PullPoint wsa.EndpointReferenceType `xml:"PullPoint"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type CreationTime time.Time

type CurrentTime time.Time

type DestroyPullPoint struct {
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type DestroyPullPointResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type Filter FilterType

type FixedTopicSet bool

type GetCurrentMessage struct {
	Topic TopicExpressionType `xml:"Topic"`
	Any core.Extension `xml:"Any,omitempty"`
}

type GetCurrentMessageResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type GetMessages struct {
	MaximumNumber *int32 `xml:"MaximumNumber,omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type GetMessagesResponse struct {
	Base32 []NotificationMessageHolderType `xml:",omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

type InvalidFilterFault InvalidFilterFaultType

type InvalidMessageContentExpressionFault InvalidMessageContentExpressionFaultType

type InvalidProducerPropertiesExpressionFault InvalidProducerPropertiesExpressionFaultType

type InvalidTopicExpressionFault InvalidTopicExpressionFaultType

type MessageContent QueryExpressionType

type MultipleTopicsSpecifiedFault MultipleTopicsSpecifiedFaultType

type NoCurrentMessageOnTopicFault NoCurrentMessageOnTopicFaultType

type NotificationMessage NotificationMessageHolderType

type NotificationProducerRP struct {
	Base33 []TopicExpressionType `xml:",omitempty"`
	Base34 *bool `xml:",omitempty"`
	Base35 []string `xml:",omitempty"`
	Base36 *wsnt.TopicSetType `xml:",omitempty"`
}

type Notify struct {
	Base37 []NotificationMessageHolderType `xml:",omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
}

type NotifyMessageNotSupportedFault NotifyMessageNotSupportedFaultType

type PauseFailedFault PauseFailedFaultType

type PauseSubscription struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type PauseSubscriptionResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type ProducerProperties QueryExpressionType

type ProducerReference wsa.EndpointReferenceType

type Renew struct {
	TerminationTime AbsoluteOrRelativeTimeType `xml:"TerminationTime"`
	Any core.Extension `xml:"Any,omitempty"`
}

type RenewResponse struct {
	Base38 time.Time `xml:""`
	Base39 *time.Time `xml:",omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
}

type ResumeFailedFault ResumeFailedFaultType

type ResumeSubscription struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type ResumeSubscriptionResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type Subscribe struct {
	ConsumerReference wsa.EndpointReferenceType `xml:"ConsumerReference"`
	Filter *FilterType `xml:"Filter,omitempty"`
	InitialTerminationTime *AbsoluteOrRelativeTimeType `xml:"InitialTerminationTime,omitempty"`
}

type SubscribeCreationFailedFault SubscribeCreationFailedFaultType

type SubscribeResponse struct {
	SubscriptionReference wsa.EndpointReferenceType `xml:"SubscriptionReference"`
	Base40 *time.Time `xml:",omitempty"`
	Base41 *time.Time `xml:",omitempty"`
	Any core.Extension `xml:"Any,omitempty"`
}

type SubscriptionManagerRP struct {
	Base42 wsa.EndpointReferenceType `xml:""`
	Base43 *FilterType `xml:",omitempty"`
	Base44 *SubscriptionPolicyType `xml:",omitempty"`
	Base45 *time.Time `xml:",omitempty"`
}

type SubscriptionPolicy SubscriptionPolicyType

type SubscriptionReference wsa.EndpointReferenceType

type TerminationTime time.Time

type Topic TopicExpressionType

type TopicExpression TopicExpressionType

type TopicExpressionDialect string

type TopicExpressionDialectUnknownFault TopicExpressionDialectUnknownFaultType

type TopicNotSupportedFault TopicNotSupportedFaultType

type UnableToCreatePullPointFault UnableToCreatePullPointFaultType

type UnableToDestroyPullPointFault UnableToDestroyPullPointFaultType

type UnableToDestroySubscriptionFault UnableToDestroySubscriptionFaultType

type UnableToGetMessagesFault UnableToGetMessagesFaultType

type UnacceptableInitialTerminationTimeFault UnacceptableInitialTerminationTimeFaultType

type UnacceptableTerminationTimeFault UnacceptableTerminationTimeFaultType

type UnrecognizedPolicyRequestFault UnrecognizedPolicyRequestFaultType

type Unsubscribe struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type UnsubscribeResponse struct {
	Any core.Extension `xml:"Any,omitempty"`
}

type UnsupportedPolicyRequestFault UnsupportedPolicyRequestFaultType

type UseRaw struct {
}

