// Code generated by onvifgen; DO NOT EDIT.

package tev

type ConnectionStatus string

const (
	ConnectionStatusOffline ConnectionStatus = "Offline"
	ConnectionStatusConnecting ConnectionStatus = "Connecting"
	ConnectionStatusConnected ConnectionStatus = "Connected"
)

type EventBrokerProtocol string

const (
	EventBrokerProtocolMqtt EventBrokerProtocol = "mqtt"
	EventBrokerProtocolMqtts EventBrokerProtocol = "mqtts"
	EventBrokerProtocolWs EventBrokerProtocol = "ws"
	EventBrokerProtocolWss EventBrokerProtocol = "wss"
)

