// Code generated by onvifgen; DO NOT EDIT.

package tth

// Describes standard Color Palette types, used to facilitate Multi-language support and client display.
// "Custom" Type shall be used when Color Palette Name does not match any of the types included in the standard classification.
type ColorPaletteType string

const (
	ColorPaletteTypeCustom ColorPaletteType = "Custom"
	ColorPaletteTypeGrayscale ColorPaletteType = "Grayscale"
	ColorPaletteTypeBlackHot ColorPaletteType = "BlackHot"
	ColorPaletteTypeWhiteHot ColorPaletteType = "WhiteHot"
	ColorPaletteTypeSepia ColorPaletteType = "Sepia"
	ColorPaletteTypeRed ColorPaletteType = "Red"
	ColorPaletteTypeIron ColorPaletteType = "Iron"
	ColorPaletteTypeRain ColorPaletteType = "Rain"
	ColorPaletteTypeRainbow ColorPaletteType = "Rainbow"
	ColorPaletteTypeIsotherm ColorPaletteType = "Isotherm"
)

type Polarity string

const (
	PolarityWhiteHot Polarity = "WhiteHot"
	PolarityBlackHot Polarity = "BlackHot"
)

