// Code generated by onvifgen; DO NOT EDIT.

package wsrfbf

import (
	"encoding/xml"
	"time"

	"github.com/furrysalamander/onvif-go/onvif/schema/core"
	"github.com/furrysalamander/onvif-go/onvif/schema/wsa"
)

type BaseFaultType struct {
	Any core.Extension `xml:"Any,omitempty"`
	Timestamp time.Time `xml:"Timestamp"`
	Originator *wsa.EndpointReferenceType `xml:"Originator,omitempty"`
	AnyAttributes []xml.Attr `xml:",any,attr,omitempty"`
}

