// Code generated by onvifgen; DO NOT EDIT.

// Package wsrfbf contains ONVIF-generated types for the
// http://docs.oasis-open.org/wsrf/bf-2 namespace.
//
// Generated from vendored WSDL/XSD schemas committed under
// internal/catalog/. See the catalog NOTICE.md for provenance.
package wsrfbf

const NS = "http://docs.oasis-open.org/wsrf/bf-2"
